//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Operations.Test.Domain.Rates
{
    using System;
    using System.Collections.Generic;
    
    using OB.Domain;
    using System.CodeDom.Compiler;

    public partial class CancellationPolicy
    { 
    
        public long UID { get; set; }
        public string CancellationPolicy_Name { get; set; }
        public string CancellationPolicy_Description { get; set; }
        public int Days { get; set; }
        public Nullable<long> Property_UID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsCancellationAllowed { get; set; }
        public bool CancellationCosts { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> PaymentModel { get; set; }
        public Nullable<int> NrNights { get; set; }
        public byte[] Revision { get; set; }
  
        public List<RateCancellationPolicy> RateCancellationPolicies { get; set; }

    }
}
