//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Operations.Test.Domain.CRM
{
    using System;
    using System.Collections.Generic;
    
    using OB.Domain;
    using System.CodeDom.Compiler;
        
    [GeneratedCode("OB TM T4 Domain Object template","1.0")]
    public partial class PropertyEventSetting : DomainObject
    {

    
        public PropertyEventSetting()
        {
            this.PropertyEventSettingLanguages = new HashSet<PropertyEventSettingLanguage>();
        }
    
        public long UID { get; set; }
        public long PropertyEvent_UID { get; set; }
        public string IntroductoryText { get; set; }
        public bool IncludeCalender { get; set; }
        public bool IncludePromotionCode { get; set; }
        public bool IncludePackages { get; set; }
        public Nullable<int> CalenderEventMonth { get; set; }
        public Nullable<int> PromotionCodeMonth { get; set; }
        public Nullable<int> PackagesMonth { get; set; }
        public bool IncludeReview { get; set; }
        public bool IncludeGuestName { get; set; }
        public Nullable<long> Survey_UID { get; set; }
        public bool IncludeReservationSummary { get; set; }
        public bool IncludeReservationCompletedetails { get; set; }
    
        public virtual PropertyEvent PropertyEvent { get; set; }
        public virtual ICollection<PropertyEventSettingLanguage> PropertyEventSettingLanguages { get; set; }
    }
}
