//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Operations.Test.Domain.Rates
{
    using System;
    using System.Collections.Generic;
    
    using OB.Domain;
    using System.CodeDom.Compiler;
        
    [GeneratedCode("OB TM T4 Domain Object template","1.0")]
    public partial class RatesChannel
    {
        public RatesChannel()
        {
            //this.RateChannelsRoomTypes = new HashSet<RateChannelsRoomType>();
            this.RatesChannelsPaymentMethods = new HashSet<RatesChannelsPaymentMethod>();
        }
    
        public long UID { get; set; }
        public long Rate_UID { get; set; }
        public long Channel_UID { get; set; }
        public string RateCode { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<bool> IsPercentage { get; set; }
        public Nullable<long> RateModel_UID { get; set; }
        public Nullable<long> ChannelCommissionCategory_UID { get; set; }
        public Nullable<long> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string ContractName { get; set; }
        public string IncomingOfficeCode { get; set; }
        public string Sequence { get; set; }
        public Nullable<bool> PriceAddOnIsPercentage { get; set; }
        public Nullable<bool> PriceAddOnIsValueDecrease { get; set; }
        public Nullable<decimal> PriceAddOnValue { get; set; }
        public byte[] Revision { get; set; }
        public Nullable<long> Currency_UID { get; set; }
        public Nullable<decimal> CustomExchangeRate { get; set; }
        public Nullable<bool> IsCustomExchangeRateSelected { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Markup { get; set; }
        public Nullable<decimal> Package { get; set; }
        public bool IsBEMobileExclusive { get; set; }
    
        //public virtual ICollection<RateChannelsRoomType> RateChannelsRoomTypes { get; set; }
        //public virtual Rate Rate { get; set; }
        public ICollection<RatesChannelsPaymentMethod> RatesChannelsPaymentMethods { get; set; }
    }
}
