//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Operations.Test.Domain.Rates
{
    using System;
    using System.Collections.Generic;
    
    using OB.Domain;
    using System.CodeDom.Compiler;
        
    public partial class RateCancellationPolicy 
    {
    
        public long UID { get; set; }
        public long Rate_UID { get; set; }
        public long CancellationPolicy_UID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
 
        public List<RateCancellationPoliciesPeriod> RateCancellationPoliciesPeriods { get; set; }
        public CancellationPolicy CancellationPolicy { get; set; }
    }
}
