//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Operations.Test.Domain.CRM
{
    using System;
    using System.Collections.Generic;
    using System.CodeDom.Compiler;
        
    [GeneratedCode("OB TM T4 Domain Object template","1.0")]
    public partial class SalesmanThirdPartyIntermediariesComission 
    {
        public long UID { get; set; }
        public long SalesmanUID { get; set; }
        public long ThirdPartyIntermediariesUID { get; set; }
        public Nullable<bool> SalesmanIsBaseCommissionPercentage { get; set; }
        public Nullable<decimal> SalesmanBaseCommission { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Salesman Salesman { get; set; }
        //public virtual ThirdPartyIntermediary ThirdPartyIntermediary { get; set; }
    }
}
