//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Operations.Test.Domain.CRM
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    [GeneratedCode("OB TM T4 Domain Object template","1.0")]
    public partial class Salesman 
    {
        public Salesman()
        {
            this.SalesmanThirdPartyIntermediariesComissions = new HashSet<SalesmanThirdPartyIntermediariesComission>();
        }
    
        public long UID { get; set; }
        public Nullable<long> Prefix_UID { get; set; }
        public Nullable<long> Property_UID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Phone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostalCode { get; set; }
        public Nullable<long> Country_UID { get; set; }
        public Nullable<long> State_UID { get; set; }
        public Nullable<long> City_UID { get; set; }
        public int Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public ICollection<SalesmanThirdPartyIntermediariesComission> SalesmanThirdPartyIntermediariesComissions { get; set; }
    }
}
