//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Operations.Test.Domain.CRM
{
    using System;
    using System.Collections.Generic;
    
    using OB.Domain;
    using System.CodeDom.Compiler;
        
    [GeneratedCode("OB TM T4 Domain Object template","1.0")]
    public partial class SystemTemplatesCategory : DomainObject
    {
    
        public SystemTemplatesCategory()
        {
            this.SystemTemplatesCategoryLanguages = new HashSet<SystemTemplatesCategoryLanguage>();
        }
    
        public long UID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> EventCode { get; set; }
    
        public virtual ICollection<SystemTemplatesCategoryLanguage> SystemTemplatesCategoryLanguages { get; set; }
    }
}
