//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Operations.Test.Domain.CRM
{
    using System;
    using System.Collections.Generic;
    
    using OB.Domain;
    using System.CodeDom.Compiler;
        
    [GeneratedCode("OB TM T4 Domain Object template","1.0")]
    public partial class SystemTemplate : DomainObject
    {
        public SystemTemplate()
        {
            this.PropertyEvents = new HashSet<PropertyEvent>();
            this.SystemDefaultEvents = new HashSet<SystemDefaultEvent>();
            this.SystemTemplatesLanguages = new HashSet<SystemTemplatesLanguage>();
        }
    
        public long UID { get; set; }
        public string Name { get; set; }
        public string HtmlContent { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> SystemTemplatesCategory_UID { get; set; }
        public int Code { get; set; }
    
        public virtual ICollection<PropertyEvent> PropertyEvents { get; set; }
        public virtual ICollection<SystemDefaultEvent> SystemDefaultEvents { get; set; }
        public virtual ICollection<SystemTemplatesLanguage> SystemTemplatesLanguages { get; set; }
    }
}
