//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Operations.Test.Domain.CRM
{
    using System;
    using System.Collections.Generic;
    
    using OB.Domain;
    using System.CodeDom.Compiler;
        
    [GeneratedCode("OB TM T4 Domain Object template","1.0")]
    public partial class SystemAction : DomainObject
    {
    
        public SystemAction()
        {
            this.PropertyEvents = new HashSet<PropertyEvent>();
            this.SystemActionsLanguages = new HashSet<SystemActionsLanguage>();
            this.SystemDefaultEvents = new HashSet<SystemDefaultEvent>();
        }
    
        public long UID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<PropertyEvent> PropertyEvents { get; set; }
        public virtual ICollection<SystemActionsLanguage> SystemActionsLanguages { get; set; }
        public virtual ICollection<SystemDefaultEvent> SystemDefaultEvents { get; set; }
    }
}
