//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Operations.Test.Domain.CRM
{
    using System;
    using System.CodeDom.Compiler;
        
    [GeneratedCode("OB TM T4 Domain Object template","1.0")]
    public partial class ThirdPartyIntermediary
    {
        public ThirdPartyIntermediary()
        {

        }
    
        public long UID { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public long Country_UID { get; set; }
        public long Language_UID { get; set; }
        public long Currency_UID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string IATA { get; set; }
        public Nullable<long> TPICategory_UID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> Property_UID { get; set; }
        public Nullable<bool> AllowsMarketing { get; set; }
        public bool IsCompany { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> Question_UID { get; set; }
        public string CommercialName { get; set; }
        public string VATNumber { get; set; }
        public string WebSite { get; set; }
        public string State { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DirectContactName { get; set; }
        public string DirectContactPhone { get; set; }
        public string DirectContactMobile { get; set; }
        public Nullable<long> PromotionalCode_UID { get; set; }
        public string CompanyCode { get; set; }
        public string PseudoCityCode { get; set; }
        public byte[] Revision { get; set; }
        public Nullable<long> TravelAgent_UID { get; set; }
        public Nullable<long> Company_UID { get; set; }
        public Nullable<long> Client_UID { get; set; }
        public string DirectContactEmail { get; set; }
        public Nullable<byte> TPIType { get; set; }
        public Nullable<long> ExternalSource_UID { get; set; }
  
    }
}
