//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(OB.DL.Model.Payments.PaymentsContext),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets69966d9d9fc740f834476a9162e4d50a56f6f6ebdc3b3cccf9a67719bb0f3ad7))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework 6 Power Tools", "0.9.2.0")]
    internal sealed class ViewsForBaseEntitySets69966d9d9fc740f834476a9162e4d50a56f6f6ebdc3b3cccf9a67719bb0f3ad7 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "69966d9d9fc740f834476a9162e4d50a56f6f6ebdc3b3cccf9a67719bb0f3ad7"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "OBDLModelPaymentsStoreContainer.PaymentGatewayTransactionsDetails")
            {
                return GetView0();
            }

            if (extentName == "OBDLModelPaymentsStoreContainer.PaymentGatewayTransactions")
            {
                return GetView1();
            }

            if (extentName == "PaymentsContext.PaymentGatewayTransactionsDetails")
            {
                return GetView2();
            }

            if (extentName == "PaymentsContext.PaymentGatewayTransactions")
            {
                return GetView3();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for OBDLModelPaymentsStoreContainer.PaymentGatewayTransactionsDetails.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaymentGatewayTransactionsDetails
        [OB.DL.Model.Payments.Store.PaymentGatewayTransactionsDetails](T1.PaymentGatewayTransactionsDetails_UID, T1.PaymentGatewayTransactionsDetails_ResponseCode, T1.PaymentGatewayTransactionsDetails_RequestJson, T1.PaymentGatewayTransactionsDetails_ResponseJson, T1.PaymentGatewayTransactionsDetails_PaymentGatewayTransactionId, T1.PaymentGatewayTransactionsDetails_RequestType, T1.PaymentGatewayTransactionsDetails_RefundTransactionID)
    FROM (
        SELECT 
            T.UID AS PaymentGatewayTransactionsDetails_UID, 
            T.ResponseCode AS PaymentGatewayTransactionsDetails_ResponseCode, 
            T.RequestJson AS PaymentGatewayTransactionsDetails_RequestJson, 
            T.ResponseJson AS PaymentGatewayTransactionsDetails_ResponseJson, 
            T.PaymentGatewayTransactionId AS PaymentGatewayTransactionsDetails_PaymentGatewayTransactionId, 
            T.RequestType AS PaymentGatewayTransactionsDetails_RequestType, 
            T.RefundTransactionID AS PaymentGatewayTransactionsDetails_RefundTransactionID, 
            True AS _from0
        FROM PaymentsContext.PaymentGatewayTransactionsDetails AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OBDLModelPaymentsStoreContainer.PaymentGatewayTransactions.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaymentGatewayTransactions
        [OB.DL.Model.Payments.Store.PaymentGatewayTransactions](T1.PaymentGatewayTransactions_UID, T1.PaymentGatewayTransactions_PaymentGatewayName, T1.PaymentGatewayTransactions_Property, T1.PaymentGatewayTransactions_PaymentGatewayOrderID, T1.PaymentGatewayTransactions_PaymentGatewayAutoGeneratedUID, T1.PaymentGatewayTransactions_OrderCaptured, T1.PaymentGatewayTransactions_OrderType, T1.PaymentGatewayTransactions_TransactionID, T1.PaymentGatewayTransactions_TransactionCode, T1.PaymentGatewayTransactions_TransactionStatus, T1.PaymentGatewayTransactions_TransactionMessage, T1.PaymentGatewayTransactions_TransactionErrorMessage, T1.PaymentGatewayTransactions_XmlMessage, T1.PaymentGatewayTransactions_TransactionType, T1.PaymentGatewayTransactions_TransactionEnviroment, T1.PaymentGatewayTransactions_ServerDate, T1.PaymentGatewayTransactions_GuestInformation, T1.PaymentGatewayTransactions_RefundTransactionID, T1.PaymentGatewayTransactions_PaypalProfileID, T1.PaymentGatewayTransactions_TransactionRequest)
    FROM (
        SELECT 
            T.UID AS PaymentGatewayTransactions_UID, 
            T.PaymentGatewayName AS PaymentGatewayTransactions_PaymentGatewayName, 
            T.Property AS PaymentGatewayTransactions_Property, 
            T.PaymentGatewayOrderID AS PaymentGatewayTransactions_PaymentGatewayOrderID, 
            T.PaymentGatewayAutoGeneratedUID AS PaymentGatewayTransactions_PaymentGatewayAutoGeneratedUID, 
            T.OrderCaptured AS PaymentGatewayTransactions_OrderCaptured, 
            T.OrderType AS PaymentGatewayTransactions_OrderType, 
            T.TransactionID AS PaymentGatewayTransactions_TransactionID, 
            T.TransactionCode AS PaymentGatewayTransactions_TransactionCode, 
            T.TransactionStatus AS PaymentGatewayTransactions_TransactionStatus, 
            T.TransactionMessage AS PaymentGatewayTransactions_TransactionMessage, 
            T.TransactionErrorMessage AS PaymentGatewayTransactions_TransactionErrorMessage, 
            T.XmlMessage AS PaymentGatewayTransactions_XmlMessage, 
            T.TransactionType AS PaymentGatewayTransactions_TransactionType, 
            T.TransactionEnviroment AS PaymentGatewayTransactions_TransactionEnviroment, 
            T.ServerDate AS PaymentGatewayTransactions_ServerDate, 
            T.GuestInformation AS PaymentGatewayTransactions_GuestInformation, 
            T.RefundTransactionID AS PaymentGatewayTransactions_RefundTransactionID, 
            T.PaypalProfileID AS PaymentGatewayTransactions_PaypalProfileID, 
            T.TransactionRequest AS PaymentGatewayTransactions_TransactionRequest, 
            True AS _from0
        FROM PaymentsContext.PaymentGatewayTransactions AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for PaymentsContext.PaymentGatewayTransactionsDetails.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaymentGatewayTransactionsDetails
        [OB.DL.Model.Payments.PaymentGatewayTransactionsDetail](T1.PaymentGatewayTransactionsDetail_UID, T1.PaymentGatewayTransactionsDetail_ResponseCode, T1.PaymentGatewayTransactionsDetail_RequestJson, T1.PaymentGatewayTransactionsDetail_ResponseJson, T1.PaymentGatewayTransactionsDetail_PaymentGatewayTransactionId, T1.PaymentGatewayTransactionsDetail_RequestType, T1.PaymentGatewayTransactionsDetail_RefundTransactionID)
    FROM (
        SELECT 
            T.UID AS PaymentGatewayTransactionsDetail_UID, 
            T.ResponseCode AS PaymentGatewayTransactionsDetail_ResponseCode, 
            T.RequestJson AS PaymentGatewayTransactionsDetail_RequestJson, 
            T.ResponseJson AS PaymentGatewayTransactionsDetail_ResponseJson, 
            T.PaymentGatewayTransactionId AS PaymentGatewayTransactionsDetail_PaymentGatewayTransactionId, 
            T.RequestType AS PaymentGatewayTransactionsDetail_RequestType, 
            T.RefundTransactionID AS PaymentGatewayTransactionsDetail_RefundTransactionID, 
            True AS _from0
        FROM OBDLModelPaymentsStoreContainer.PaymentGatewayTransactionsDetails AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for PaymentsContext.PaymentGatewayTransactions.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PaymentGatewayTransactions
        [OB.DL.Model.Payments.PaymentGatewayTransaction](T1.PaymentGatewayTransaction_UID, T1.PaymentGatewayTransaction_PaymentGatewayName, T1.PaymentGatewayTransaction_Property, T1.PaymentGatewayTransaction_PaymentGatewayOrderID, T1.PaymentGatewayTransaction_PaymentGatewayAutoGeneratedUID, T1.PaymentGatewayTransaction_OrderCaptured, T1.PaymentGatewayTransaction_OrderType, T1.PaymentGatewayTransaction_TransactionID, T1.PaymentGatewayTransaction_TransactionCode, T1.PaymentGatewayTransaction_TransactionStatus, T1.PaymentGatewayTransaction_TransactionMessage, T1.PaymentGatewayTransaction_TransactionErrorMessage, T1.PaymentGatewayTransaction_XmlMessage, T1.PaymentGatewayTransaction_TransactionType, T1.PaymentGatewayTransaction_TransactionEnviroment, T1.PaymentGatewayTransaction_ServerDate, T1.PaymentGatewayTransaction_GuestInformation, T1.PaymentGatewayTransaction_RefundTransactionID, T1.PaymentGatewayTransaction_PaypalProfileID, T1.PaymentGatewayTransaction_TransactionRequest)
    FROM (
        SELECT 
            T.UID AS PaymentGatewayTransaction_UID, 
            T.PaymentGatewayName AS PaymentGatewayTransaction_PaymentGatewayName, 
            T.Property AS PaymentGatewayTransaction_Property, 
            T.PaymentGatewayOrderID AS PaymentGatewayTransaction_PaymentGatewayOrderID, 
            T.PaymentGatewayAutoGeneratedUID AS PaymentGatewayTransaction_PaymentGatewayAutoGeneratedUID, 
            T.OrderCaptured AS PaymentGatewayTransaction_OrderCaptured, 
            T.OrderType AS PaymentGatewayTransaction_OrderType, 
            T.TransactionID AS PaymentGatewayTransaction_TransactionID, 
            T.TransactionCode AS PaymentGatewayTransaction_TransactionCode, 
            T.TransactionStatus AS PaymentGatewayTransaction_TransactionStatus, 
            T.TransactionMessage AS PaymentGatewayTransaction_TransactionMessage, 
            T.TransactionErrorMessage AS PaymentGatewayTransaction_TransactionErrorMessage, 
            T.XmlMessage AS PaymentGatewayTransaction_XmlMessage, 
            T.TransactionType AS PaymentGatewayTransaction_TransactionType, 
            T.TransactionEnviroment AS PaymentGatewayTransaction_TransactionEnviroment, 
            T.ServerDate AS PaymentGatewayTransaction_ServerDate, 
            T.GuestInformation AS PaymentGatewayTransaction_GuestInformation, 
            T.RefundTransactionID AS PaymentGatewayTransaction_RefundTransactionID, 
            T.PaypalProfileID AS PaymentGatewayTransaction_PaypalProfileID, 
            T.TransactionRequest AS PaymentGatewayTransaction_TransactionRequest, 
            True AS _from0
        FROM OBDLModelPaymentsStoreContainer.PaymentGatewayTransactions AS T
    ) AS T1");
        }
    }
}
