//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.DL.Model.Payments
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using OB.Domain.Payments;
    using System.CodeDom.Compiler;
        
    [GeneratedCode("OB TM T4 Domain Object template","1.0")]
    internal partial class PaymentsContext : DbContext
    {
        public PaymentsContext()
            : base("name=PaymentsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PaymentGatewayTransactionsDetail> PaymentGatewayTransactionsDetails { get; set; }
        public virtual DbSet<PaymentGatewayTransaction> PaymentGatewayTransactions { get; set; }
    }
}
