
using OB.BL.Contracts.Requests;
using OB.DL.Common.Criteria;
using OB.DL.Common.Filter;
using OB.Reservation.BL.Contracts.Requests;
using System;
using System.Collections.Generic;
using System.Linq;
using static OB.Reservation.BL.Constants;
using commonFilter = OB.DL.Common.Filter;
using domains = OB.Domain.Reservations;

namespace OB.BL.Operations.Internal.TypeConverters
{
    public class RequestToCriteriaConverters
    {
        //TODO: Passar toda a logica nova da OB.API para a Reservation.API
            //Base Filters
            //Base Orders
            //Base Requests to Base Criteria


        #region List PaymentGateway transactions Criteria 
        public static ListPaymentGatewayTransactionsCriteria Convert(ListPaymentGatewayTransactionsRequest obj)
        {
            var newObj = new ListPaymentGatewayTransactionsCriteria();

            Map(obj, newObj);

            return newObj;
        }

        public static void Map(ListPaymentGatewayTransactionsRequest obj, ListPaymentGatewayTransactionsCriteria objDestination)
        {
            //TODO: descomentar o mapbase quando tivermos a nova logica Base filters e base orders na reservation.api
            //MapBase(obj, objDestination);

            objDestination.Ids = obj.UIDs;
            objDestination.PaymentGatewayAutoGeneratedIds = obj.PaymentGatewayAutoGeneratedUIDs;
            objDestination.PaymentGatewayNames = obj.PaymentGatewayNames;
            objDestination.PaymentGatewayOrderIds = obj.PaymentGatewayOrderIDs;
            objDestination.PaypalProfileIds = obj.PaypalProfileIDs;
            objDestination.PropertyIds = obj.PropertyUIDs;
            objDestination.RefundTransactionIds = obj.RefundTransactionIDs;
            objDestination.TransactionCodes = obj.TransactionCodes;
            objDestination.TransactionIds = obj.TransactionIDs;
            objDestination.TransactionRequests = obj.TransactionRequests;
            objDestination.TransactionStatus = obj.TransactionStatus;
            objDestination.TransactionTypes = obj.TransactionTypes;

        }
        #endregion

        public static GetGroupRuleCriteria ConvertToGroupRuleCriteria(OB.Reservation.BL.Contracts.Requests.RequestBase obj)
        {
            var convertedObj = new GetGroupRuleCriteria
            {
                RuleType = Enum.TryParse<domains.RuleType>(obj.RuleType.ToString(), out var ruleType) ? ruleType : default(domains.RuleType)
            };

            if (obj.BusinessRules == null)
                return convertedObj;

            // Remove all rules
            if (obj.BusinessRules.RemovedRules == BusinessRuleFlags.All)
            {
                convertedObj.BusinessRulesToRemove = 0;
                foreach (domains.BusinessRules rule in Enum.GetValues(typeof(domains.BusinessRules)))
                    convertedObj.BusinessRulesToRemove |= rule;
            }

            // Remove specific rules
            else if (obj.BusinessRules.RemovedRules.HasValue && Enum.TryParse<domains.BusinessRules>(obj.BusinessRules.RemovedRules.ToString(), out var rulesToRemove))
                convertedObj.BusinessRulesToRemove = rulesToRemove;


            // Add all rules
            if (obj.BusinessRules.AddedRules == BusinessRuleFlags.All)
            {
                convertedObj.BusinessRulesToAdd = 0;
                foreach (domains.BusinessRules rule in Enum.GetValues(typeof(domains.BusinessRules)))
                    convertedObj.BusinessRulesToAdd |= rule;
            }

            // Add specific rules
            else if (obj.BusinessRules.AddedRules.HasValue && Enum.TryParse<domains.BusinessRules>(obj.BusinessRules.AddedRules.ToString(), out var rulesToAdd))
                convertedObj.BusinessRulesToAdd = rulesToAdd;

            return convertedObj;
        }
    }
}
