using MaxiPago.DataContract.Transactional;
using OB.BL.Contracts.Data.Payments;
using OB.BL.Operations.Helper;
using OB.BL.Operations.Helper.Interfaces;
using OB.BL.Operations.Interfaces;
using OB.DL.Common.QueryResultObjects;
using OB.Domain;
using OB.Domain.Payments;
using PaymentGatewaysLibrary;
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using OB.BL.Operations.Internal.TypeConverters;
using OB.Reservation.BL.Contracts.Requests;
using OB.Reservation.BL.Contracts.Responses;
using ResponseBase = MaxiPago.DataContract.ResponseBase;
using reservationContracts = OB.Reservation.BL.Contracts.Data.Reservations;
using OB.BL.Operations.Extensions;
using OB.Domain.Reservations;
using Newtonsoft.Json;

namespace OB.BL.Operations.Impl
{
    public class PaymentGatewayManagerPOCO : BusinessPOCOBase, IPaymentGatewayManagerPOCO
    {
        private void LogInformation(string systemOrderID, string transactionEnviroment, string transactionType, decimal chargeTotal, PaymentGatewayConfiguration config, ResponseBase response, string guestInfo)
        {
            try
            {
                var svc = this.Resolve<IPaymentGatewayManagerPOCO>();

                PaymentGatewayTransaction trans = new PaymentGatewayTransaction();

                if (response.IsTransactionResponse)
                {
                    TransactionResponse result = response as TransactionResponse;
                    if (result.ResponseCode == "0")
                        trans.OrderCaptured = chargeTotal;

                    trans.OrderType = transactionType;
                    trans.PaymentGatewayAutoGeneratedUID = result.ProcessorReferenceNumber;
                    trans.PaymentGatewayName = config.GatewayName;
                    trans.PaymentGatewayOrderID = result.OrderId;
                    trans.Property = config.PropertyUID;
                    trans.TransactionCode = result.ResponseCode;
                    trans.TransactionEnviroment = transactionEnviroment;
                    trans.TransactionID = result.TransactionId;
                    trans.TransactionMessage = result.ResponseMessage;
                    trans.TransactionErrorMessage = result.ErrorMessage;
                    trans.TransactionStatus = result.ResponseCode;
                    trans.TransactionType = transactionType;
                    trans.PaymentGatewayAutoGeneratedUID = systemOrderID;
                    trans.XmlMessage = this.Resolve<IProjectGeneral>().SerializeAnObject(result);
                    trans.ServerDate = DateTime.UtcNow;
                    trans.GuestInformation = guestInfo;

                }
                else
                {
                    ErrorResponse result = response as ErrorResponse;
                    trans.OrderCaptured = 0;
                    trans.OrderType = transactionType;
                    trans.PaymentGatewayName = config.GatewayName;
                    trans.Property = config.PropertyUID;
                    trans.TransactionCode = result.ErrorCode;
                    trans.TransactionEnviroment = transactionEnviroment;
                    trans.TransactionMessage = "ERROR";
                    trans.TransactionErrorMessage = result.ErrorMsg;
                    trans.TransactionStatus = result.ErrorCode;
                    trans.TransactionType = transactionType;

                    trans.XmlMessage = this.Resolve<IProjectGeneral>().SerializeAnObject(result);
                    trans.ServerDate = DateTime.UtcNow;
                    trans.GuestInformation = guestInfo;
                }

                using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Payments))
                {
                    var paymentsRepo = RepositoryFactory.GetRepository<PaymentGatewayTransaction>(unitOfWork);

                    paymentsRepo.Add(trans);
                    unitOfWork.Save();
                }
            }
            catch
            {

            }
        }

        /// <summary>
        /// Log payment transaction information
        /// </summary>
        /// <param name="config"></param>
        /// <param name="result"></param>
        /// <param name="guestInfo"></param>
        public void LogPaymentTransactionInformationCustom(OB.BL.Contracts.Data.Payments.PaymentGatewayConfiguration config, PaymentMessageResult result, string guestInfo)
        {
            try
            {
                PaymentGatewayTransaction trans = new PaymentGatewayTransaction();

                trans.OrderCaptured = result.PaymentAmountCaptured;
                trans.OrderType = result.PaymentGatewayTransactionType;
                trans.PaymentGatewayAutoGeneratedUID = result.PaymentGatewayAutoGeneratedUID;
                trans.PaymentGatewayName = config.GatewayName;
                trans.PaymentGatewayOrderID = result.PaymentGatewayOrderID;
                trans.Property = config.PropertyUID;
                trans.TransactionCode = result.PaymentGatewayTransactionStatusCode;
                trans.TransactionEnviroment = result.TransactionEnvironment;
                trans.TransactionID = result.PaymentGatewayTransactionID;
                trans.TransactionMessage = result.TransactionMessage;
                trans.TransactionErrorMessage = result.ErrorMessage;
                trans.TransactionStatus = result.PaymentGatewayTransactionStatusDescription;
                trans.TransactionType = result.PaymentGatewayTransactionType;
                trans.XmlMessage = result.PaymentGatewayResponseXml;
                trans.TransactionRequest = result.PaymentGatewayRequestXml;
                trans.ServerDate = DateTime.UtcNow;
                trans.GuestInformation = guestInfo;

                using (var scope = TransactionManager.BeginTransactionScope(Domain.Payments.PaymentGatewayTransaction.DomainScope, System.Transactions.TransactionScopeOption.Suppress))
                using (var unitOfWork = SessionFactory.GetUnitOfWork())
                {
                    var paymentsRepo = RepositoryFactory.GetPaymentGatewayTransactionRepository(unitOfWork);
                    paymentsRepo.Add(trans);
                    unitOfWork.Save();
                    scope.Complete();
                }
            }
            catch (Exception ex)
            {
                // Error Saving Transaction Log
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("PaymentGatewayConfiguration", config);
                arguments.Add("PaymentGatewayMessageResult", result);
                arguments.Add("GuestInfo", guestInfo);

                Logger.Error(ex, "LogPaymentTransactionInformationCustom wasn't created. Params: {0}", arguments.ToJSON());
            }
        }

#region PAYPAL

        /// <summary>
        /// Get Hotel Paypal account information
        /// </summary>
        /// <param name="propertyId"></param>
        /// <param name="isTestMode"></param>
        /// <returns></returns>
        public Dictionary<string, string> GetPaypalConfig(long propertyId, bool isTestMode)
        {
            var config = new Dictionary<string, string>();
            var propertyRepo = RepositoryFactory.GetOBPropertyRepository();

            if (isTestMode)
                config.Add("mode", "sandbox");
            else
                config.Add("mode", "live");

            var gatewayCode = ((int)Constants.PaymentGateway.Paypal).ToString();
            var gateway = propertyRepo.ListPaymentGatewayConfiguration(new Contracts.Requests.ListPaymentGatewayConfigurationRequest { PropertyIds = new List<long> { propertyId }, GatewayCodes = new List<string> { gatewayCode } }).FirstOrDefault();

            if (gateway != null && !string.IsNullOrEmpty(gateway.MerchantID) && !string.IsNullOrEmpty(gateway.MerchantKey) && !string.IsNullOrEmpty(gateway.ApiSignatureKey))
            {
                config.Add("account1.apiUsername", gateway.MerchantID);
                config.Add("account1.apiPassword", gateway.MerchantKey);
                config.Add("account1.apiSignature", gateway.ApiSignatureKey);
                config.Add("requestRetries", "2");

                return config;
            }
            else
                return null;
        }

        /// <summary>
        /// Get Payment Gateway Transaction by PaymentGatewayAutoGeneratedUID
        /// </summary>
        /// <param name="transaction"></param>
        /// <returns>TransactionId</returns>
        public PaymentGatewayTransaction GetPaymentGatewayTransactionByPaymentGatewayAutoGeneratedUID(string paymentGatewayAutoGeneratedUID)
        {
            PaymentGatewayTransaction paymentGatewayTransaction = null;

            using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Payments))
            {
                var request = new ListPaymentGatewayTransactionsRequest
                {
                    PaymentGatewayAutoGeneratedUIDs = new List<string> {
                        paymentGatewayAutoGeneratedUID
                    }
                };

                var criteria = RequestToCriteriaConverters.Convert(request);

                var paymentRepo = RepositoryFactory.GetPaymentGatewayTransactionRepository(unitOfWork);
                paymentGatewayTransaction = paymentRepo.FindByCriteria(criteria).FirstOrDefault();
            }

            return paymentGatewayTransaction;
        }

        public Dictionary<string, string> GetInfoForPaypalRequest(long rateId, long roomId, long languageId)
        {
            var result = new Dictionary<string, string>();
            var ratesRepo = RepositoryFactory.GetOBRateRepository();
            var propertyRepo = RepositoryFactory.GetOBPropertyRepository();

            // Get Product Name
            var productName = string.Empty;

            // Rate Name
            var rate = ratesRepo.ListRatesLight(new Contracts.Requests.ListRateLightRequest { UIDs = new List<long> { rateId }, LanguageUID = languageId, RateTranslate = true }).FirstOrDefault();

            if (rate != null)
                productName = rate.Name + " - ";

            // Room Name
            var room = propertyRepo.ListRoomTypes(new Contracts.Requests.ListRoomTypeRequest { UIDs = new List<long> { roomId }, LanguageUID = languageId, RoomTypeTranslate = true }).FirstOrDefault();

            productName += room.Name;

            result.Add("ProductName", productName);

            return result;
        }

#endregion

        public InsertPaymentGatewayTransationResponse InsertPaymentGatewayTransation(InsertPaymentGatewayTransationRequest request)
        {
            var response = new InsertPaymentGatewayTransationResponse();

            Contract.Requires(request != null, "Request object instance is expected");
            Contract.Requires(request.PaymentGatewayTransaction != null, "Request PaymentGatewayTransaction object instance is expected");
            response.RequestId = request.RequestId;

            try
            {
                using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Payments))
                {
                    var paymentsRepo = RepositoryFactory.GetRepository<PaymentGatewayTransaction>(unitOfWork);
                    var reservationsRepo = RepositoryFactory.GetReservationsRepository(unitOfWork);

                    if(request.PaymentGatewayTransaction.PaymentDetails != null && request.PaymentGatewayTransaction.PaymentDetails.Count > 0)
                    {
                        var isParsed = long.TryParse(request.PaymentGatewayTransaction.IdOnSource, out var reservationId);
                        if (isParsed && reservationId > 0)
                        {
                            var reservationAdditionalData = reservationsRepo.FindReservationsAdditionalDataByReservationsUIDs(new List<long> { reservationId }).FirstOrDefault();

                            if (reservationAdditionalData != null)
                            {
                                var contractReservationAdditionalData = JsonConvert.DeserializeObject<reservationContracts.ReservationsAdditionalData>(reservationAdditionalData.ReservationAdditionalDataJSON);
                                var paymentGatewayDetails = OtherConverter.Convert(request.PaymentGatewayTransaction, contractReservationAdditionalData);
                                var reservationAdditionalDataJson = JsonConvert.SerializeObject(paymentGatewayDetails);

                                reservationsRepo.UpdateReservationAdditionalDataJson(reservationAdditionalData.UID, reservationAdditionalDataJson);
                            }
                            else
                            {
                                var paymentGatewayDetails = OtherConverter.Convert(request.PaymentGatewayTransaction);
                                var reservationAdditionalDataJson = JsonConvert.SerializeObject(paymentGatewayDetails);
                                reservationsRepo.InsertReservationAdditionalDataJson(reservationId, reservationAdditionalDataJson);
                            }
                        }
                    }

                    var paymentGateway = BusinessObjectToDomainTypeConverter.Convert(request.PaymentGatewayTransaction);
                    
                    paymentsRepo.Add(paymentGateway);
                    unitOfWork.Save();
                }
                response.Succeed();
            }
            catch (Exception ex)
            {
                response.Failed();
                response.Errors.Add(new Error { Description = ex.Message });
                Logger.Error(ex, "PaymentGatewayTransation wasn't created. REQUEST:{0}", request.ToJSON());

                // Error Saving Transaction Log
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("InsertPaymentGatewayTransationRequest", request);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), ex, LogSeverity.Critical, arguments);
            }

            return response;
        }

        public UpdatePaymentGatewayTransationResponse UpdatePaymentGatewayTransation(UpdatePaymentGatewayTransationRequest request)
        {
            var response = new UpdatePaymentGatewayTransationResponse();

            Contract.Requires(request != null, "Request object instance is expected");
            Contract.Requires(request.PaymentGatewayTransaction != null, "Request PaymentGatewayTransaction object instance is expected");
            response.RequestId = request.RequestId;
            try
            {
                using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Payments))
                {
                    var paymentsRepo = RepositoryFactory.GetRepository<PaymentGatewayTransaction>(unitOfWork);

                    var domainPaymentTransaction = paymentsRepo.FirstOrDefault(x => x.TransactionID == request.PaymentGatewayTransaction.TransactionID);

                    BusinessObjectToDomainTypeConverter.Map(request.PaymentGatewayTransaction, domainPaymentTransaction, true);

                    unitOfWork.Save();
                }
                response.Succeed();
            }
            catch (Exception ex)
            {
                response.Failed();
                response.Errors.Add(new Error { Description = ex.Message });
                Logger.Error(ex, "PaymentGatewayTransation wasn't updated. REQUEST:{0}", request.ToJSON());

                // Error Saving Transaction Log
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("UpdatePaymentGatewayTransationRequest", request);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), ex, LogSeverity.Critical, arguments);
            }

            return response;
        }

        public InsertPaymentGatewayTransationDetailsResponse InsertPaymentGatewayTransationDetails(InsertPaymentGatewayTransationDetailsRequest request)
        {
            var response = new InsertPaymentGatewayTransationDetailsResponse();

            Contract.Requires(request != null, "Request object instance is expected");
            Contract.Requires(request.PaymentGatewayTransactionsDetail != null, "Request PaymentGatewayTransactionsDetail object instance is expected");
            response.RequestId = request.RequestId;
            try
            {
                using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Payments))
                {
                    var paymentsDetailRepo = RepositoryFactory.GetRepository<PaymentGatewayTransactionsDetail>(unitOfWork);

                    var paymentGatewayDetail = BusinessObjectToDomainTypeConverter.Convert(request.PaymentGatewayTransactionsDetail);

                    paymentsDetailRepo.Add(paymentGatewayDetail);
                    unitOfWork.Save();
                }
                response.Succeed();
            }
            catch (Exception ex)
            {
                response.Failed();
                response.Errors.Add(new Error { Description = ex.Message });
                Logger.Error(ex, "PaymentGatewayTransationsDetail wasn't created. REQUEST:{0}", request.ToJSON());

                // Error Saving Transaction Log
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("InsertPaymentGatewayTransationDetailsRequest", request);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), ex, LogSeverity.Critical, arguments);
            }

            return response;
        }

        public UpdatePaymentGatewayTransationDetailsResponse UpdatePaymentGatewayTransationDetails(UpdatePaymentGatewayTransationDetailsRequest request)
        {
            var response = new UpdatePaymentGatewayTransationDetailsResponse();

            Contract.Requires(request != null, "Request object instance is expected");
            Contract.Requires(request.PaymentGatewayTransactionsDetail != null, "Request PaymentGatewayTransactionsDetail object instance is expected");
            response.RequestId = request.RequestId;
            try
            {
                using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Payments))
                {
                    var paymentsDetailRepo = RepositoryFactory.GetRepository<PaymentGatewayTransactionsDetail>(unitOfWork);

                    var paymentGatewayDetail = BusinessObjectToDomainTypeConverter.Convert(request.PaymentGatewayTransactionsDetail);

                    paymentsDetailRepo.AttachAsModified(paymentGatewayDetail);
                    unitOfWork.Save();
                }
                response.Succeed();
            }
            catch (Exception ex)
            {
                response.Failed();
                response.Errors.Add(new Error { Description = ex.Message });
                Logger.Error(ex, "PaymentGatewayTransationsDetail wasn't updated. REQUEST:{0}", request.ToJSON());

                // Error Saving Transaction Log
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("UpdatePaymentGatewayTransationDetailsRequest", request);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), ex, LogSeverity.Critical, arguments);
            }

            return response;
        }

    }
}
