using OB.BL.Operations.Helper.Interfaces;
using OB.BL.Operations.Interfaces;
using OB.BL.Operations.Internal.TypeConverters;
using OB.Domain;
using OB.Domain.Payments;
using OB.Reservation.BL.Contracts.Requests;
using OB.Reservation.BL.Contracts.Responses;
using PaymentGatewaysLibrary;
using PaymentGatewaysLibrary.PaypalClasses;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Configuration;
using contractsReservations = OB.Reservation.BL.Contracts.Data.Reservations;
using OB.BL.Operations.Extensions;

namespace OB.BL.Operations.Helper
{
    internal class PaypalGatewayManagerPOCO : BusinessPOCOBase, IPaypalGatewayManagerPOCO
    {
        private readonly bool _isTestMode;
        private Dictionary<string, string> _config;
        private long _propertyId;
        private IPaymentGatewayManagerPOCO _paymentGatewayManagerPOCO;

        public PaypalGatewayManagerPOCO()
        {
            bool isTestMode = false;
            if (WebConfigurationManager.AppSettings["PaypalIsInTestMode"] != null)
                bool.TryParse(WebConfigurationManager.AppSettings["PaypalIsInTestMode"].ToString(), out isTestMode);

            _isTestMode = isTestMode;
        }

        public void Initialize(long propertyId)
        {
            _propertyId = propertyId;
            _paymentGatewayManagerPOCO = this.Resolve<IPaymentGatewayManagerPOCO>();
            _config = _paymentGatewayManagerPOCO.GetPaypalConfig(_propertyId, _isTestMode);
        }

        //TODO : validar novos parametros dos serviços expostos

        /// <summary>
        /// RESTful implementation of the CapturePayment operation.
        /// This operation capture Paypal PaymentInitialize(request.Reservation.Property_UID, request.LanguageUID.Value, request.Reservation.ReservationBaseCurrency_UID.Value);
        /// </summary>
        /// <remarks>
        /// <para>Required Parameters:</para>
        /// <para>- PayerId</para>
        /// <para>- Token</para>
        /// <para>- PaypalAutoGeneratedId</para>
        /// <para>- Reservation</para>
        /// <para>- ReservationRooms</para>
        /// </remarks>
        /// <param name="request">The request containing the criteria</param>
        /// <returns>An CreateRecurringBillingResponse that contains the PaypalTransation Id of the operation.</returns>
        public CapturePaymentResponse CapturePayment(CapturePaymentRequest request)
        {
            DoExpressCheckoutPaymentResponse responsePaypal = new DoExpressCheckoutPaymentResponse();
            CapturePaymentResponse response = new CapturePaymentResponse();

            ValidateCaptureRequest(response, request);
            if (response.Errors.Any())
                return response;

            Initialize(request.Reservation.Property_UID);

            try
            {
                using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Reservations))
                {                    
                    if (_config == null)
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("PropertyId", _propertyId);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.InvalidPayPalConfiguration.ToString()),
                                                    LogSeverity.High, arguments);

                        response.Errors.Add(Errors.InvalidPayPalConfiguration.ToContractError());
                        return response;
                    }

                    SetExpressCheckoutRequest DoExpressCheckoutRequest = this.FillExpressCheckoutRequest("", request.Reservation, request.ReservationRooms, request.LanguageUID.Value);
                    DoExpressCheckoutRequest.UniqueId = request.PaypalAutoGeneratedId;
                    DoExpressCheckoutRequest.PayerId = request.PayerId;
                    DoExpressCheckoutRequest.Token = request.Token;
                    var paymentGatewayFactory = Resolve<IPaymentGatewayFactory>().Paypal(_config);
                    responsePaypal = paymentGatewayFactory.DoExpressCheckoutPaymentAPIOperation(DoExpressCheckoutRequest);

                    // Get Transaction Id
                    var paypalTransationId = string.Empty;
                    if (responsePaypal.PaymentInfo != null && responsePaypal.PaymentInfo.Count > 0)
                        paypalTransationId = responsePaypal.PaymentInfo.FirstOrDefault().TransactionID;

                    // Amount Captured
                    decimal amountCaptured = 0;
                    Decimal.TryParse(DoExpressCheckoutRequest.TotalAmount, NumberStyles.Number, CultureInfo.InvariantCulture, out amountCaptured);

                    // Log Transation
                    var transaction = _paymentGatewayManagerPOCO.GetPaymentGatewayTransactionByPaymentGatewayAutoGeneratedUID(request.PaypalAutoGeneratedId);
                    if (transaction != null)
                    {
                        transaction.Property = request.Reservation.Property_UID;
                        transaction.TransactionID = paypalTransationId;
                        transaction.TransactionStatus = responsePaypal.Ack.Trim().ToUpper();
                        transaction.GuestInformation = "Name: " + request.Reservation.GuestFirstName + "- Email: " + request.Reservation.GuestEmail;
                        transaction.ServerDate = DateTime.Parse(responsePaypal.Timestamp);
                        transaction.OrderCaptured = amountCaptured;
                   
                        unitOfWork.Save();
                        this.LogTransactionDetails(transaction.UID, "DoExpressCheckout", responsePaypal.Ack.Trim().ToUpper(), responsePaypal.ResponseJson, responsePaypal.RequestJson);
                    }

                    if (responsePaypal.Ack.Trim().ToUpper().Equals("SUCCESS"))
                    {
                        response.PaypalTransationId = paypalTransationId;
                        response.Reservation = request.Reservation;
                        response.Reservation.PaymentGatewayTransactionUID = transaction?.UID;
                        response.Reservation.PaymentGatewayAutoGeneratedUID = request.PaypalAutoGeneratedId;
                        response.Reservation.PaymentAmountCaptured = amountCaptured;
                        response.Reservation.PaymentGatewayTransactionDateTime = DateTime.Parse(responsePaypal.Timestamp);
                        response.Reservation.PaymentGatewayName = "Paypal";
                        response.Reservation.PaymentGatewayOrderID = request.Token;
                        response.Reservation.PaymentGatewayTransactionID = paypalTransationId;
                        response.Reservation.PaymentGatewayTransactionMessage = "SUCCESS";
                        response.Reservation.PaymentGatewayTransactionStatusCode = "SUCCESS";

                        response.Succeed();
                    }
                    else
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("Paypal Object", responsePaypal);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.FailedCapturedPayment.ToString()),
                                                    LogSeverity.High, arguments);
                    }
                }
            }
            catch (Exception ex)
            {
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("objReservation", request.Reservation);
                arguments.Add("objReservationRoom", request.ReservationRooms);
                arguments.Add("PaypalObject", responsePaypal);
                arguments.Add("Exception", ex.StackTrace);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.FailedDoExpressCheckout.ToString()), LogSeverity.High, arguments);
            }

            return response;
        }

        /// <summary>
        /// RESTful implementation of the PaypalVerifyInstallmentsAuthorization operation.
        /// This operation verify if authorization was successfull
        /// </summary>
        /// <remarks>
        /// <para>Required Parameters:</para>
        /// <para>- Token</para>
        /// <para>- PaypalAutoGeneratedId</para>
        /// <para>Optional Parameters:</para>
        /// <para>- Reservation</para>
        /// <para>- ReservationRooms</para>
        /// </remarks>
        /// <param name="request">The request containing the criteria</param>
        /// <returns>An PaypalVerifyInstallmentsAuthorizationResponse that contains the status of the operation.</returns>
        public PaypalVerifyInstallmentsAuthorizationResponse PaypalVerifyInstallmentsAuthorization(PaypalVerifyInstallmentsAuthorizationRequest request)
        {
            GetExpressCheckoutResponse responseExpressCheck = new GetExpressCheckoutResponse();
            PaypalVerifyInstallmentsAuthorizationResponse response = new PaypalVerifyInstallmentsAuthorizationResponse();
            response.Result = false;

            ValidatePaypalInstallmentsAuthorizationRequest(response, request);
            if (response.Errors.Any())
                return response;

            Initialize(request.Reservation.Property_UID);

            try
            {
                if (_config == null)
                {
                    Dictionary<string, object> arguments = new Dictionary<string, object>();
                    arguments.Add("PropertyId", _propertyId);
                    this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.InvalidPayPalConfiguration.ToString()), LogSeverity.High, arguments);

                    response.Errors.Add(Errors.InvalidPayPalConfiguration.ToContractError());
                    return response;
                }

                var paymentGatewayFactory = Resolve<IPaymentGatewayFactory>().Paypal(_config);
                responseExpressCheck = paymentGatewayFactory.GetExpressCheckoutDetailsAPIOperation(request.Token);

                // Log Transation
                this.LogTransactionDetailsByPaypalAutoGeneratedId(request?.PaypalAutoGeneratedId, "GetExpressCheckout", responseExpressCheck.Ack.Trim().ToUpper(), responseExpressCheck.ResponseJson, responseExpressCheck.RequestJson);

                if (responseExpressCheck.Ack.Trim().ToUpper().Equals("SUCCESS") && responseExpressCheck.BillingAgreementAcceptedStatus.HasValue && responseExpressCheck.BillingAgreementAcceptedStatus.Value)
                {
                    response.Result = responseExpressCheck.BillingAgreementAcceptedStatus.HasValue && responseExpressCheck.BillingAgreementAcceptedStatus.Value;
                    response.Succeed();

                    return response;
                }
            }
            catch (Exception ex)
            {
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("objReservation", request.Reservation);
                arguments.Add("objReservationRoom", request.ReservationRooms);
                arguments.Add("PaypalObject", response);
                arguments.Add("Exception", ex.StackTrace);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - GetExpressCheckout Error"), LogSeverity.High, arguments);
            }

            return response;
        }

        /// <summary>
        /// RESTful implementation of the CreateRecurringBilling operation.
        /// This operation create a recurring billing 
        /// </summary>
        /// <remarks>
        /// <para>Required Parameters:</para>
        /// <para>- Token</para>
        /// <para>- PropertyName</para>
        /// <para>- PaypalAutoGeneratedId</para> 
        /// <para>- Reservation</para>
        /// <para>- ReservationRooms</para>
        /// </remarks>
        /// <param name="request">The request containing the criteria</param>
        /// <returns>An CreateRecurringBillingResponse that contains the Profile Id of the operation.</returns>
        public CreateRecurringBillingResponse CreateRecurringBilling(CreateRecurringBillingRequest request)
        {
            var responsePaypal = new CreateRecurringPaymentsProfileResponse();
            CreateRecurringBillingResponse response = new CreateRecurringBillingResponse();

            ValidateRecurringBillingRequest(response, request);
            if (response.Errors.Any())
                return response;

            Initialize(request.Reservation.Property_UID);

            try
            {
                using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Reservations))
                {
                    var currencyRepo = RepositoryFactory.GetOBCurrencyRepository();

                    if (_config == null)
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("PropertyId", _propertyId);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.InvalidPayPalConfiguration.ToString()),
                                                    LogSeverity.High, arguments);

                        response.Errors.Add(Errors.InvalidPayPalConfiguration.ToContractError());
                        return response;
                    }

                    // Get Paypal CurrencyCode
                    var paypalCurrencyId = string.Empty;
                    var currencyId = (long)request.Reservation.ReservationBaseCurrency_UID;
                    var currency = currencyRepo.ListCurrencies(new Contracts.Requests.ListCurrencyRequest { UIDs = new List<long> { currencyId } }).FirstOrDefault();
                    if (currency != null && !string.IsNullOrEmpty(currency.PaypalCurrencyCode))
                        paypalCurrencyId = currency.PaypalCurrencyCode;
                    else
                        paypalCurrencyId = "174";

                    var reservationInfo = this.FillExpressCheckoutRequest(request.PropertyName, request.Reservation, request.ReservationRooms, request.LanguageUID.Value);

                    var interestRate = request.Reservation.InterestRate != null ? (decimal)(request.Reservation.InterestRate / 100) + 1 : 1;
                    var noOfInstallment = request.Reservation.NoOfInstallment ?? 1;
                    decimal installmentAmount = (decimal)(((request.Reservation.TotalAmount / request.Reservation.PropertyBaseCurrencyExchangeRate) * interestRate) / noOfInstallment);

                    var paymentGatewayFactory = Resolve<IPaymentGatewayFactory>().Paypal(_config);
                    responsePaypal = paymentGatewayFactory.CreateRecurringPaymentsProfileAPIOperation(request.Token, paypalCurrencyId, noOfInstallment.ToString(),
                                                    (installmentAmount).ToString("0.00", CultureInfo.InvariantCulture), reservationInfo);

                    // Log Transation
                    var transaction = _paymentGatewayManagerPOCO.GetPaymentGatewayTransactionByPaymentGatewayAutoGeneratedUID(request.PaypalAutoGeneratedId);
                    if (transaction != null)
                    {
                        transaction.TransactionID = responsePaypal.TransactionID;
                        transaction.PaypalProfileID = responsePaypal.ProfileID;
                        transaction.TransactionStatus = responsePaypal.Ack.Trim().ToUpper();

                        unitOfWork.Save();
                        this.LogTransactionDetails(transaction.UID, "RecurringPaymentsProfileTransaction", responsePaypal.Ack.Trim().ToUpper(), responsePaypal.ResponseJson, responsePaypal.RequestJson);
                    }

                    if (responsePaypal.Ack.Trim().ToUpper().Equals("SUCCESS") && responsePaypal.ProfileStatus.Trim().ToUpper().Equals("ACTIVEPROFILE"))
                    {
                        response.ProfileId = responsePaypal.ProfileID;
                        response.Reservation = request.Reservation;
                        response.Reservation.PaymentGatewayTransactionUID = transaction?.UID;
                        response.Reservation.PaymentGatewayTransactionID = responsePaypal.ProfileID;
                        response.Reservation.PaymentGatewayOrderID = request.Token;
                        response.Reservation.PaymentGatewayAutoGeneratedUID = request.PaypalAutoGeneratedId;
                        response.Reservation.PaymentGatewayName = "Paypal";
                        response.Reservation.PaymentGatewayTransactionDateTime = DateTime.Parse(responsePaypal.Timestamp);
                        response.Reservation.PaymentGatewayTransactionStatusCode = responsePaypal.Ack.Trim().ToUpper();

                        response.Succeed();
                    }
                    else
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("Paypal Object", responsePaypal);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - Failed Creating Recurring Payment"),
                                                    LogSeverity.High, arguments);
                    }
                }
            }
            catch (Exception ex)
            {
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("Paypal Object", responsePaypal);
                arguments.Add("Exception", ex.StackTrace);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - Failed Creating Recurring Payment"),
                                            LogSeverity.High, arguments);
            }

            return response;
        }

        /// <summary>
        /// RESTful implementation of the CancelAndRefundRecurringBilling operation.
        /// This operation cancel a Recurring payment, refund if paid
        /// </summary>
        /// <remarks>
        /// <para>Required Parameters:</para>
        /// <para>- PaymentGatewayTransactionId</para>
        /// <para>- ProfileId</para>
        /// <para>- IsPartialRefund</para> 
        /// <para>- Reservation</para>
        /// <para>Optional Parameters:</para>
        /// <para>- Action [CANCEL, SUSPEND, REACTIVATE]</para>
        /// <para>- Note</para>
        /// </remarks>
        /// <param name="request">The request containing the criteria</param>
        /// <returns>An CancelAndRefundRecurringBillingResponse that contains the status of the operation.</returns>
        public CancelAndRefundRecurringBillingResponse CancelAndRefundRecurringBilling(CancelAndRefundRecurringBillingRequest request)
        {
            CancelAndRefundRecurringBillingResponse response = new CancelAndRefundRecurringBillingResponse();

            ValidateCancelRecurringBillingRequest(response, request);
            if (response.Errors.Any())
                return response;

            Initialize(request.Reservation.Property_UID);

            response.Result = true;

            try
            {
                if (_config == null)
                {
                    Dictionary<string, object> arguments = new Dictionary<string, object>();
                    arguments.Add("PropertyId", _propertyId);
                    this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.InvalidPayPalConfiguration.ToString()), LogSeverity.High, arguments);

                    response.Errors.Add(Errors.InvalidPayPalConfiguration.ToContractError());
                    response.Result = false;
                    return response;
                }

                // Refund Transactions if reservation was inserted
                if (request.Reservation.UID <= 0)
                {
                    response.Result = false;
                    response.Errors.Add(Errors.ReservationDoesNotExist.ToContractError());
                    return response;
                }

                var paymentGatewayFactory = Resolve<IPaymentGatewayFactory>().Paypal(_config);
                var action = request.Action == Reservation.BL.Constants.PayPalAction.UNKNOW ? string.Empty : request.Action.ToString();

                if (!RecurringPaymentsRefund(paymentGatewayFactory, request.ProfileId, request.Reservation, action, request.PaymentGatewayTransactionId))
                {
                    response.Result = false;
                    return response;
                }

                response.Succeed();
            }
            catch (Exception ex)
            {
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("Reservation Number", request.Reservation.Number);
                arguments.Add("Paypal Profile Id", request.ProfileId);
                arguments.Add("Exception", ex.StackTrace);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.FailedCancellingRecurringPayment.ToString()),
                                            LogSeverity.High, arguments);
                response.Result = false;
            }

            return response;
        }

        /// <summary>
        /// RESTful implementation of the RefundPayment operation.
        /// This operation refund Paypal Payment
        /// </summary>
        /// <remarks>
        /// <para>Required Parameters:</para>
        /// <para>- TransactionId</para>
        /// <para>- PaypalTransactionId</para>
        /// <para>- RefundType [OTHER,FULL,PARTIAL,EXTERNALDISPUTE]</para> 
        /// <para>- RefundAmount</para>
        /// <para>- ReservationCurrency</para>
        /// <para>- ReservationNumber</para>
        /// </remarks>
        /// <param name="request">The request containing the criteria</param>
        /// <returns>An RefundPaymentResponse that contains the status of the operation.</returns>
        public RefundPaymentResponse RefundPayment(RefundPaymentRequest request)
        {
            var response = new RefundPaymentResponse();
            response.Result = false;

            ValidateRefundPayment(response, request);
            if (response.Errors.Any())
                return response;

            Initialize(request.PropertyId);

            try
            {
                using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Reservations))
                {
                    var paymentRepo = RepositoryFactory.GetPaymentGatewayTransactionRepository(unitOfWork);
                    if (_config == null)
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("PropertyId", _propertyId);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.InvalidPayPalConfiguration.ToString()),
                                                    LogSeverity.High, arguments);
                        response.Errors.Add(Errors.InvalidPayPalConfiguration.ToContractError());
                        return response;
                    }

                    // Get Paypal CurrencyCode
                    var paypalCurrencyId = string.Empty;
                    var currencyRepo = RepositoryFactory.GetOBCurrencyRepository();
                    var currency = currencyRepo.ListCurrencies(new Contracts.Requests.ListCurrencyRequest { UIDs = new List<long> { request.ReservationCurrency } }).FirstOrDefault();
                    if (currency != null && !string.IsNullOrEmpty(currency.PaypalCurrencyCode))
                        paypalCurrencyId = currency.PaypalCurrencyCode;
                    else
                        paypalCurrencyId = "174";

                    var paymentGatewayFactory = Resolve<IPaymentGatewayFactory>().Paypal(_config);
                    var responsePaypal = paymentGatewayFactory.RefundTransactionAPIOperation(request.PaypalTransactionId, request.RefundType.ToString(), request.RefundAmount, paypalCurrencyId);

                    // Log Transation
                    var transaction = paymentRepo.FindOne(x => x.UID == (long)request.TransactionId);
                    if (transaction != null)
                    {
                        transaction.RefundTransactionID = responsePaypal.RefundTransactionID;
                        transaction.TransactionStatus = responsePaypal.Ack.Trim().ToUpper();
                        
                        unitOfWork.Save();
                        this.LogTransactionDetails(transaction.UID, "RefundTransaction", responsePaypal.Ack.Trim().ToUpper(), responsePaypal.ResponseJson, responsePaypal.RequestJson, responsePaypal.RefundTransactionID);
                    }

                    if (responsePaypal.Ack.Trim().ToUpper().Equals("SUCCESS"))
                    {
                        response.Result = true;
                        response.Succeed();
                    }
                    else
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("Paypal Object", responsePaypal);
                        arguments.Add("Reservation Number", request.ReservationNumber);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.FailedRefundCapturedPayment.ToString()),
                                                    LogSeverity.High, arguments);
                    }
                }
            }
            catch (Exception ex)
            {
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("Paypal Object", response);
                arguments.Add("Reservation Number", request.ReservationNumber);
                arguments.Add("Exception", ex.StackTrace);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.FailedRefundCapturedPayment.ToString()),
                                            LogSeverity.High, arguments);
            }

            return response;
        }

        /// <summary>
        /// RESTful implementation of the GetPayPalPaymentURL operation.
        /// This operation get paypal payment url.
        /// </summary>
        /// <param name="request">A GetPayPalPaymentURLRequest object containing the criteria</param>
        /// <returns>A GetPayPalPaymentURLResponse containing the URL and Token</returns>
        public GetPayPalPaymentURLResponse GetPayPalPaymentURL(Reservation.BL.Contracts.Requests.GetPayPalPaymentURLRequest request)
        {
            var response = new GetPayPalPaymentURLResponse();

            try
            {
               
                string PayPalToken = this.PaypalStartPayment(request);

                if (!string.IsNullOrEmpty(PayPalToken))
                {
                    bool isTestMode = false;
                    bool.TryParse(System.Web.Configuration.WebConfigurationManager.AppSettings["PaypalIsInTestMode"].ToString(), out isTestMode);
                    var redirectUrl = isTestMode ? System.Web.Configuration.WebConfigurationManager.AppSettings["PaypalTestRedirect"].ToString() : System.Web.Configuration.WebConfigurationManager.AppSettings["PaypalLiveRedirect"].ToString();

                    response.Result = redirectUrl + PayPalToken;
                    response.Token = PayPalToken;
                    response.Succeed();
                }
                else
                {
                    Logger.Warn("PayPalToken null");
                }
            }
            catch (Exception ex)
            {
                response.Failed();
                Logger.Error(ex);
            }

            return response;
        }

        public LogTransactionResponse LogPaypalTransaction(Reservation.BL.Contracts.Requests.LogTransactionRequest request)
        {
            var response = new LogTransactionResponse();
            try
            {
                if (request != null)
                {
                    if (request.LogType == Reservation.BL.Constants.LogTransactionType.LogTransaction)
                    {
                        response.TransactionUID = LogTransaction(new SetExpressCheckoutRequest { UniqueId = request.UniqueId }, OtherConverter.Convert(request.response), request.isTestMode);
                        response.Succeed();
                    }
                    else if (request.LogType == Reservation.BL.Constants.LogTransactionType.LogTransactionDetails)
                    {
                        LogTransactionDetails(request.transactionId, request.requestType, request.responseCode, request.responseJson, request.requestJson, request.refundTransactionId);
                        response.Succeed();
                    }
                    else if (request.LogType == Reservation.BL.Constants.LogTransactionType.LogTransactionDetailsByPaypalAutoGeneratedId)
                    {
                        LogTransactionDetailsByPaypalAutoGeneratedId(request.paypalAutoGeneratedId, request.requestType, request.responseCode, request.responseJson, request.requestJson);
                        response.Succeed();
                    }
                }
            }
            catch (Exception ex)
            {
                response.Failed();
                Logger.Error(ex);
            }

            return response;
        }

        /// <summary>
        /// Cancel a Recurring payment, refund if paid
        /// </summary>
        /// <param name="paypalAutoGeneratedId"></param>
        /// <param name="profileId"></param>
        /// <param name="action">CANCEL, SUSPEND, REACTIVATE</param>
        /// <param name="note"></param>
        /// <returns></returns>
        public bool CancelAndRefundRecurringBilling(long paymentGatewayTransactionId, string profileId, bool isPartialRefund, contractsReservations.Reservation reservation, string action = "", string note = "")
        {
            var result = true;
            try
            {
                Initialize(reservation.Property_UID);

                if (_config == null)
                {
                    Dictionary<string, object> arguments = new Dictionary<string, object>();
                    arguments.Add("PropertyId", _propertyId);
                    this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.InvalidPayPalConfiguration.ToString()),
                                                LogSeverity.High, arguments);
                    return false;
                }

                Paypal paypalSrv = new Paypal(_config);

                // Refund Transactions if reservation was inserted
                if (reservation.UID > 0)
                {
                    if (!RecurringPaymentsRefund(paypalSrv, profileId, reservation, action, paymentGatewayTransactionId))
                        return false;
                }
            }
            catch (Exception ex)
            {
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("Reservation Number", reservation.Number);
                arguments.Add("Paypal Profile Id", profileId);
                arguments.Add("Exception", ex.StackTrace);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.FailedCancellingRecurringPayment.ToString()),
                                            LogSeverity.High, arguments);
                result = false;
            }

            return result;
        }

        /// <summary>
        /// Refund Paypal Payment
        /// </summary>
        /// <returns></returns>
        public bool RefundPayment(contractsReservations.Reservation reservation, string refundType, string refundAmount, string transactionIdFromProfileIdOperation = null)
        {
            var response = new RefundTransactionResponse();
            var result = false;

            Initialize(reservation.Property_UID);
            try
            {
                using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Reservations))
                {
                    var paymentRepo = RepositoryFactory.GetPaymentGatewayTransactionRepository(unitOfWork);

                    if (_config == null)
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("PropertyId", _propertyId);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.InvalidPayPalConfiguration.ToString()),
                                                    LogSeverity.High, arguments);
                        return result;
                    }

                    // Get Paypal CurrencyCode
                    var paypalCurrencyId = string.Empty;
                    var currencyRepo = RepositoryFactory.GetOBCurrencyRepository();
                    var currency = currencyRepo.ListCurrencies(new Contracts.Requests.ListCurrencyRequest { UIDs = new List<long> { reservation.ReservationBaseCurrency_UID.Value } }).FirstOrDefault();
                    if (currency != null && !string.IsNullOrEmpty(currency.PaypalCurrencyCode))
                        paypalCurrencyId = currency.PaypalCurrencyCode;
                    else
                        paypalCurrencyId = "174";

                    var paymentGatewayFactory = Resolve<IPaymentGatewayFactory>().Paypal(_config);

                    var transactionId = !string.IsNullOrEmpty(transactionIdFromProfileIdOperation) ? transactionIdFromProfileIdOperation : reservation.PaymentGatewayTransactionID;
                    response = paymentGatewayFactory.RefundTransactionAPIOperation(transactionId, refundType.ToString(), refundAmount, paypalCurrencyId);

                    // Log Transation
                    var transaction = paymentRepo.FindOne(x => x.UID == reservation.PaymentGatewayTransactionUID.Value);
                    if (transaction != null)
                    {
                        transaction.RefundTransactionID = response.RefundTransactionID;
                        transaction.TransactionStatus = response.Ack.Trim().ToUpper();

                        unitOfWork.Save();
                        this.LogTransactionDetails(transaction.UID, "RefundTransaction", response.Ack.Trim().ToUpper(), response.ResponseJson, response.RequestJson, response.RefundTransactionID);
                    }

                    if (response.Ack.Trim().ToUpper().Equals("SUCCESS"))
                    {
                        result = true;
                    }
                    else
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("Paypal Object", response);
                        arguments.Add("Reservation Number", reservation.Number);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - Failed Refund Captured Payment"),
                                                    LogSeverity.High, arguments);                        

                        result = false;
                    }
                }
            }
            catch (Exception ex)
            {
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("Paypal Object", response);
                arguments.Add("Reservation Number", reservation.Number);
                arguments.Add("Exception", ex.StackTrace);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - Failed Refund Captured Payment"),
                                            LogSeverity.High, arguments);
                result = false;
            }

            return result;
        }

        /// <summary>
        /// Refund Paypal Recurring Payments
        /// </summary>
        /// <returns></returns>
        public bool RefundRecurringPayment(string transactionId, string refundType, string refundAmount, long reservationCurrency, long propertyId)
        {
            var response = new RefundTransactionResponse();
            var result = false;

            Initialize(propertyId);
            try
            {
                using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Reservations))
                {
                    var paymentRepo = RepositoryFactory.GetRepository<PaymentGatewayTransaction>(unitOfWork);
                    var currencyRepo = RepositoryFactory.GetOBCurrencyRepository();
                    if (_config == null)
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("PropertyId", _propertyId);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.InvalidPayPalConfiguration.ToString()),
                                                    LogSeverity.High, arguments);
                        return result;
                    }

                    // Get Paypal CurrencyCode
                    var paypalCurrencyId = string.Empty;
                    var currency = currencyRepo.ListCurrencies(new Contracts.Requests.ListCurrencyRequest { UIDs = new List<long> { reservationCurrency } }).FirstOrDefault();
                    if (currency != null && !string.IsNullOrEmpty(currency.PaypalCurrencyCode))
                        paypalCurrencyId = currency.PaypalCurrencyCode;
                    else
                        paypalCurrencyId = "174";

                    response = new Paypal(_config).RefundTransactionAPIOperation(transactionId, refundType.ToString(), refundAmount, paypalCurrencyId);

                    // Log Transation
                    var transaction = paymentRepo.FindOne(x => x.TransactionID == transactionId);
                    if (transaction != null)
                    {
                        transaction.RefundTransactionID = response.RefundTransactionID;
                        transaction.TransactionStatus = response.Ack.Trim().ToUpper();
                        paymentRepo.Update(transaction);
                        unitOfWork.Save();
                        this.LogTransactionDetails(transaction.UID, "RefundTransaction", response.Ack.Trim().ToUpper(), response.ResponseJson, response.RequestJson, response.RefundTransactionID);
                    }

                    if (response.Ack.Trim().ToUpper().Equals("SUCCESS"))
                    {
                        result = true;
                    }
                    else
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("Paypal Object", response);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - Failed Refund Captured Payment"),
                                                    LogSeverity.High, arguments);
                        result = false;
                    }
                }
            }
            catch (Exception ex)
            {
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("Paypal Object", response);
                arguments.Add("Exception", ex.StackTrace);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - Failed Refund Captured Payment"),
                                            LogSeverity.High, arguments);
                result = false;
            }

            return result;
        }


        public string PaypalStartPayment(Reservation.BL.Contracts.Requests.GetPayPalPaymentURLRequest request)
        {
            SetExpressCheckoutResponse response = new SetExpressCheckoutResponse();
            var result = string.Empty;

            try
            {
                this.Initialize(request.Reservation.Property_UID);

                if (_config == null)
                {
                    Dictionary<string, object> arguments = new Dictionary<string, object>();
                    arguments.Add("PropertyId", _propertyId);
                    this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception(Errors.InvalidPayPalConfiguration.ToString()),
                                                LogSeverity.High, arguments);
                    return result;
                }

                SetExpressCheckoutRequest requestSetExpressCheckout = this.FillExpressCheckoutRequest(request.PropertyName, request.Reservation, request.ReservationRoom, request.LanguageUID.Value, request.ReturnUrl, request.LanguageIso);
                requestSetExpressCheckout.UniqueId = request.UniqueId;

                response = new Paypal(_config).SetExpressCheckoutAPIOperation(requestSetExpressCheckout);

                // Log Transation
                var transactionId = this.LogTransaction(requestSetExpressCheckout, response, _isTestMode);
                this.LogTransactionDetails(transactionId, "SetExpressCheckout", response.Ack.Trim().ToUpper(), response.ResponseJson, response.RequestJson);

                if (response.Ack.Trim().ToUpper().Equals("SUCCESS"))
                    result = response.Token;
                else
                {
                    Dictionary<string, object> arguments = new Dictionary<string, object>();
                    arguments.Add("Paypal Object", response);
                    arguments.Add("Paypal Transaction UID", transactionId);
                    this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - Set ExpreesCheckout Failed"),
                                                LogSeverity.High, arguments);
                    result = string.Empty;
                }
            }
            catch (Exception ex)
            {
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("objReservation", request.Reservation);
                arguments.Add("objReservationRoom", request.ReservationRoom);
                arguments.Add("PaypalObject", response);
                arguments.Add("Exception", ex.StackTrace);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - SetExpressCheckout Error"), LogSeverity.High, arguments);
                result = string.Empty;
            }

            return result;
        }

        /// <summary>
        /// Verify if authorization was successfull
        /// </summary>
        /// <param name="token"></param>
        /// <param name="paypalAutoGeneratedId"></param>
        /// <param name="objReservation"></param>
        /// <param name="objReservationRoom"></param>
        /// <returns></returns>
        public string PaypalVerifyAuthorization(string token, string paypalAutoGeneratedId, contractsReservations.Reservation objReservation, List<contractsReservations.ReservationRoom> objReservationRoom)
        {
            GetExpressCheckoutResponse response = new GetExpressCheckoutResponse();
            var result = string.Empty;

            try
            {
                Initialize(objReservation.Property_UID);

                if (_config == null)
                {
                    Dictionary<string, object> arguments = new Dictionary<string, object>();
                    arguments.Add("PropertyId", _propertyId);
                    this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - Property Configurations Not Defined"),
                                                LogSeverity.High, arguments);
                }

                response = new Paypal(_config).GetExpressCheckoutDetailsAPIOperation(token);

                // Log Transation
                this.LogTransactionDetailsByPaypalAutoGeneratedId(paypalAutoGeneratedId, "GetExpressCheckout", response.Ack.Trim().ToUpper(), response.ResponseJson, response.RequestJson);

                if (response.Ack.Trim().ToUpper().Equals("SUCCESS") && !string.IsNullOrEmpty(response.PayerID))
                {
                    return response.PayerID;
                }
            }
            catch (Exception ex)
            {
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("objReservation", objReservation);
                arguments.Add("objReservationRoom", objReservationRoom);
                arguments.Add("PaypalObject", response);
                arguments.Add("Exception", ex.StackTrace);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - GetExpressCheckout Error"), LogSeverity.High, arguments);
            }

            return result;
        }

        #region HELPERS

        /// <summary>
        /// Get Transaction By Profile Id
        /// </summary>
        /// <param name="paypalSrv"></param>
        /// <param name="profileId"></param>
        /// <param name="reservation"></param>
        /// <returns></returns>
        private PaymentTransactionSearch GetTransactionsByProfileId(IPaypal paypalSrv, string profileId, contractsReservations.Reservation reservation)
        {
            var transactions = paypalSrv.TransactionSearchByProfileIdAPIOperation(profileId, (DateTime)reservation.CreatedDate);
            if (!transactions.Ack.Trim().ToUpper().Equals("SUCCESS"))
            {
                Dictionary<string, object> arguments = new Dictionary<string, object>();
                arguments.Add("Reservation Number", reservation.Number);
                arguments.Add("Paypal Profile Id", profileId);
                this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(),
                    new Exception("Paypal - Failed Getting Recurring Payments Transactions"), LogSeverity.High, arguments);
            }

            return transactions;
        }

        /// <summary>
        /// Get Guest amount paid for the reservation in paypal
        /// </summary>
        /// <param name="paypalSrv"></param>
        /// <param name="transactions"></param>
        /// <returns></returns>
        private decimal GetPaypalAlreadyPaidValue(IPaypal paypalSrv, PaymentTransactionSearch transactions, contractsReservations.Reservation reservation)
        {
            var paidValue = transactions.Transactions.Sum(x => x.GrossAmount);

            // Get Refunds Value
            decimal valueRefunded = 0;
            foreach (var item in transactions.Transactions)
            {
                if (item.Status.Trim().ToUpper() == "CREATED" || item.Status.Trim().ToUpper() == "UPDATED" || item.GrossAmount <= 0)
                    continue;

                var allTransactions = paypalSrv.TransactionSearchByTransactionIdAPIOperation(item.TransactionID, (DateTime)reservation.CreatedDate);
                if (allTransactions.Ack.Trim().ToUpper().Equals("SUCCESS"))
                {
                    valueRefunded = allTransactions.Transactions.Where(x => x.Type.Trim().ToUpper().Equals("REFUND")).Sum(x => x.GrossAmount);
                }
                else
                {
                    Dictionary<string, object> arguments = new Dictionary<string, object>();
                    arguments.Add("Reservation Number", reservation.Number);
                    arguments.Add("Paypal Error", allTransactions.Errors?.ToString());
                    this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(),
                        new Exception("Paypal - Failed Getting Guest paid value on paypal"), LogSeverity.High, arguments);

                    return -1;
                }
            }

            return paidValue - valueRefunded;
        }

        /// <summary>
        /// Fill Express Checkout Request
        /// </summary>
        /// <param name="objReservation"></param>
        /// <param name="objReservationRoom"></param>
        /// <returns></returns>
        private SetExpressCheckoutRequest FillExpressCheckoutRequest(string propertyName, contractsReservations.Reservation objReservation,
                            List<contractsReservations.ReservationRoom> objReservationRoom, long languageId,
                            string returnUrl = "", string cancelUrl = "", string languageIso = "US")
        {
            var currencyRepo = RepositoryFactory.GetOBCurrencyRepository();
            SetExpressCheckoutRequest request = new SetExpressCheckoutRequest();
            request.LocalCode = languageIso.Length >= 2 ? languageIso.Substring(0, 2).ToUpper() : "US";
            var interestRate = objReservation.InterestRate != null ? (decimal)(objReservation.InterestRate / 100) + 1 : 1;

            // Used to prepare redirect to Paypal Website
            // Remove Paypal Tags if there are any
            if (!string.IsNullOrEmpty(returnUrl))
            {
                Uri uri = new Uri(returnUrl);
                var nameValues = HttpUtility.ParseQueryString(HttpUtility.HtmlDecode(uri.Query));
                nameValues.Remove("gateway");
                nameValues.Remove("PaypalCanceled");
                nameValues.Remove("token");
                nameValues.Remove("PayerID");

                var url = string.Empty;
                if (string.IsNullOrEmpty(uri.Query))
                    url = uri.AbsoluteUri + "?";
                else
                    url = uri.AbsoluteUri.Replace(uri.Query, "?") + nameValues.ToString();

                request.ReturnUrl = url + "&gateway=Paypal";
                request.CancelUrl = url + "&gateway=Paypal&PaypalCanceled=true";
            }

            // Get Paypal CurrencyCode
            var currency = currencyRepo.ListCurrencies(new Contracts.Requests.ListCurrencyRequest { UIDs = new List<long> { objReservation.ReservationBaseCurrency_UID.Value } }).FirstOrDefault();
            if (currency != null && !string.IsNullOrEmpty(currency.PaypalCurrencyCode))
                request.PaypalCurrencyId = currency.PaypalCurrencyCode;
            else
                request.PaypalCurrencyId = "174";

            request.ItemDetails = new List<ItemDetail>();

            var description = new StringBuilder();
            description.Append(propertyName + " - Email: " + objReservation.GuestEmail);

            decimal itemsTotal = 0;
            foreach (var room in objReservationRoom)
            {
                var requestInfo = _paymentGatewayManagerPOCO.GetInfoForPaypalRequest((long)room.Rate_UID, (long)room.RoomType_UID, languageId);
                var item = new ItemDetail();
                item.Name = requestInfo["ProductName"];
                var tmpTax = room.TotalTax.HasValue ? ((room.TotalTax / objReservation.PropertyBaseCurrencyExchangeRate) * interestRate) : 0;
                var amount = Math.Round(((decimal)(((room.ReservationRoomsTotalAmount / objReservation.PropertyBaseCurrencyExchangeRate) * interestRate) - tmpTax)), 2);
                item.Amount = amount.ToString("0.00", CultureInfo.InvariantCulture);
                item.Description = Resources.Resources.lblCheckIn + ": " + ((DateTime)room.DateFrom).ToShortDateString() + " / " + Resources.Resources.lblCheckOut + ": " + ((DateTime)room.DateTo).ToShortDateString();
                item.Quantity = 1;

                itemsTotal += amount;
                request.ItemDetails.Add(item);
            }

            request.ItemsTotalAmount = Math.Round(itemsTotal, 2).ToString("0.00", CultureInfo.InvariantCulture);

            var totalTax = objReservation.TotalTax.HasValue ? Math.Round(((decimal)(objReservation.TotalTax / objReservation.PropertyBaseCurrencyExchangeRate) * interestRate), 2) : 0;
            request.TotalTax = totalTax.ToString("0.00", CultureInfo.InvariantCulture);

            var totalAmount = itemsTotal + totalTax;
            request.TotalAmount = totalAmount.ToString("0.00", CultureInfo.InvariantCulture);

            // Partial Payments
            request.IsRecurringPayments = objReservation.IsPartialPayment.HasValue ? objReservation.IsPartialPayment.Value : false;
            request.BillingAgreementDescription = description.ToString();

            return request;
        }


        /// <summary>
        /// Update Recurring Profile installment Value
        /// </summary>
        /// <param name="paypalSrv"></param>
        /// <param name="profileId"></param>
        /// <param name="paymentGatewayTransactionId"></param>
        /// <param name="action"></param>
        /// <param name="note"></param>
        /// <returns></returns>
        private bool UpdateRecurringProfile(IPaypal paypalSrv, string profileId, long paymentGatewayTransactionId, contractsReservations.Reservation reservation, string action = "", string note = "")
        {
            var result = false;
            var response = paypalSrv.ManageRecurringProfileAPIOperation(profileId, action, note);

            using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Reservations))
            {
                var paymentRepo = RepositoryFactory.GetPaymentGatewayTransactionRepository(unitOfWork);

                // Log Transation
                var transaction = paymentRepo.FindOne(x => x.UID == paymentGatewayTransactionId);
                if (transaction != null)
                {
                    transaction.PaypalProfileID = response.ProfileId;
                    transaction.TransactionStatus = response.Ack.Trim().ToUpper();
                    
                    unitOfWork.Save();
                    this.LogTransactionDetails(transaction.UID, "ManageRecurringPaymentsProfileStatusResponse(" + action + ")", response.Ack.Trim().ToUpper(), response.ResponseJson, response.RequestJson);
                }

                if (response.Ack.Trim().ToUpper().Equals("SUCCESS") && !string.IsNullOrEmpty(response.ProfileId))
                {
                    result = true;
                }
                else
                {
                    Dictionary<string, object> arguments = new Dictionary<string, object>();
                    arguments.Add("Paypal Manage Profile Object", response);
                    arguments.Add("Reservation Number", reservation.Number);
                    this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(), new Exception("Paypal - Failed Cancelling Recurring Payment Profile"),
                                                LogSeverity.High, arguments);

                    result = false;
                }
            }

            return result;
        }

        /// <summary>
        /// Refund Recurring Transactions
        /// </summary>
        /// <param name="paypalSrv"></param>
        /// <param name="profileId"></param>
        /// <param name="reservation"></param>
        /// <param name="action"></param>
        /// <returns></returns>
        private bool RecurringPaymentsRefund(IPaypal paypalSrv, string profileId, contractsReservations.Reservation reservation, string action, long paymentGatewayTransactionId)
        {
            // Get All Transactions
            var transactions = this.GetTransactionsByProfileId(paypalSrv, profileId, reservation);
            if (transactions.Ack.Trim().ToUpper().Equals("SUCCESS"))
            {                
                // Full refund of all transactions
                if (action.Equals("CANCEL"))
                {
                    if (this.FullRecurringPaymentsRefund(paypalSrv, transactions, reservation))
                    {
                        if (this.UpdateRecurringProfile(paypalSrv, profileId, paymentGatewayTransactionId, reservation, action))
                            return true;
                        else
                        {
                            Dictionary<string, object> arguments = new Dictionary<string, object>();
                            arguments.Add("Reservation Number", reservation.Number);
                            arguments.Add("Paypal Profile Id", profileId);
                            this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(),
                                        new Exception("Paypal - Failed Update Recurring Profile(Reservation Cancelation) (See Paypal Profile Id)"), LogSeverity.High, arguments);

                            return false;
                        }
                    }
                    else
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("Reservation Number", reservation.Number);
                        arguments.Add("Paypal Profile Id", profileId);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(),
                                    new Exception("Paypal - Failed Refunding Full Recurring Payments(Reservation Cancelation) (See Paypal Profile Id)"), LogSeverity.High, arguments);

                        return false;
                    }
                }
                // Partial Refund (Room Cancelation)
                else
                {
                    if (this.PartialRecurringPaymentsRefund(paypalSrv, transactions, reservation, profileId, paymentGatewayTransactionId, action))
                        return true;
                    else
                    {
                        Dictionary<string, object> arguments = new Dictionary<string, object>();
                        arguments.Add("Reservation Number", reservation.Number);
                        arguments.Add("Paypal Profile Id", profileId);
                        this.Resolve<ILogEmail>().SendEmail(System.Reflection.MethodBase.GetCurrentMethod(),
                                    new Exception("Paypal - Failed Refunding Partial Recurring Payments(Reservation Update) (See Paypal Profile Id)"), LogSeverity.High, arguments);

                        return false;
                    }
                }
            }
            else
                return false;
        }

        /// <summary>
        /// Partial Refund of Installment
        /// </summary>
        /// <param name="paypalSrv"></param>
        /// <param name="transactions"></param>
        /// <param name="reservation"></param>
        /// <returns></returns>
        private bool PartialRecurringPaymentsRefund(IPaypal paypalSrv, PaymentTransactionSearch transactions, contractsReservations.Reservation reservation, string profileId, long paymentGatewayTransactionId, string action)
        {
            var paidValue = GetPaypalAlreadyPaidValue(paypalSrv, transactions, reservation);

            if (paidValue < 0)
                return false;

            decimal reservationRemainingAmount = (decimal)(reservation.TotalAmount / reservation.PropertyBaseCurrencyExchangeRate);

            // Adjust Parcels
            if (paidValue < reservationRemainingAmount)
            {
                using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Reservations))
                {
                    var paymentRepo = RepositoryFactory.GetPaymentGatewayTransactionRepository(unitOfWork);
                    var currencyRepo = RepositoryFactory.GetOBCurrencyRepository();

                    var noOfInstallments = ((reservation.NoOfInstallment ?? 1) - transactions.Transactions.Count(x => x.Status.Trim().ToUpper() == "COMPLETED"));

                    decimal installmentAmount = (decimal)((reservationRemainingAmount - paidValue) / (noOfInstallments > 0 ? noOfInstallments : 1));
                    // Get Paypal CurrencyCode
                    var paypalCurrencyId = string.Empty;
                    var currency = currencyRepo.ListCurrencies(new Contracts.Requests.ListCurrencyRequest { UIDs = new List<long> { (long)reservation.ReservationBaseCurrency_UID } }).FirstOrDefault();
                    if (currency != null && !string.IsNullOrEmpty(currency.PaypalCurrencyCode))
                        paypalCurrencyId = currency.PaypalCurrencyCode;
                    else
                        paypalCurrencyId = "174";

                    var update = paypalSrv.UpdateRecurringPaymentsProfileAPIOperation(profileId, installmentAmount.ToString("0.00", CultureInfo.InvariantCulture), paypalCurrencyId);

                    // Log Transation
                    var transaction = paymentRepo.FindOne(x => x.UID == paymentGatewayTransactionId);
                    if (transaction != null)
                    {
                        transaction.PaypalProfileID = update.ProfileID;
                        transaction.TransactionStatus = update.Ack.Trim().ToUpper();
                        
                        unitOfWork.Save();
                        this.LogTransactionDetails(transaction.UID, "UpdateRecurringPaymentsProfile(Insatallment Amount = " + installmentAmount + ")", update.Ack.Trim().ToUpper(), update.ResponseJson, update.RequestJson);
                    }

                    if (string.IsNullOrEmpty(update.ProfileID))
                        return false;
                }
            }
            else if (paidValue >= reservationRemainingAmount)
            {
                // Refund Exceeded Amount and Cancel Remaining Installments
                var refundValue = (decimal)(paidValue - reservationRemainingAmount);
                if (refundValue > 0)
                {
                    foreach (var item in transactions.Transactions)
                    {
                        if (refundValue <= 0)
                            break;

                        if (item.Status.Trim().ToUpper() == "CREATED" || item.Status.Trim().ToUpper() == "UPDATED" || item.GrossAmount <= 0)
                            continue;

                        var refundResult = true;

                        var transaction = paypalSrv.GetTransactionDetails(item.TransactionID);
                        if (transaction.Ack.Trim().ToUpper().Equals("SUCCESS"))
                        {
                            if (transaction.TransactionInfo.PaymentStatus.Trim().ToUpper() == "COMPLETED" && item.GrossAmount > 0)
                            {
                                if (transaction.TransactionInfo.GrossAmount > refundValue)
                                {
                                    refundResult = this.RefundPayment(reservation,
                                            OB.Reservation.BL.Constants.PaypalRefundType.PARTIAL.ToString(),
                                            refundValue.ToString("0.00", CultureInfo.InvariantCulture), item.TransactionID);

                                    if (!refundResult)
                                        return false;

                                    refundValue -= refundValue;
                                }
                                else
                                {
                                    refundResult = this.RefundPayment(reservation,
                                            OB.Reservation.BL.Constants.PaypalRefundType.FULL.ToString(),
                                            item.GrossAmount.ToString("0.00", CultureInfo.InvariantCulture), item.TransactionID);

                                    if (!refundResult)
                                        return false;

                                    refundValue = refundValue - item.GrossAmount;
                                }
                            }
                            else if (transaction.TransactionInfo.PaymentStatus.Trim().ToUpper() == "PARTIALLYREFUNDED" && item.GrossAmount > 0)
                            {
                                decimal totalRefunded = 0;
                                var allTransactions = paypalSrv.TransactionSearchByTransactionIdAPIOperation(item.TransactionID, (DateTime)reservation.CreatedDate);
                                if (allTransactions.Ack.Trim().ToUpper().Equals("SUCCESS"))
                                {
                                    totalRefunded = allTransactions.Transactions.Where(x => x.Type.Trim().ToUpper().Equals("REFUND")).Sum(x => x.GrossAmount);
                                }

                                if (transaction.TransactionInfo.GrossAmount - totalRefunded > refundValue)
                                {
                                    refundResult = this.RefundPayment(reservation,
                                                OB.Reservation.BL.Constants.PaypalRefundType.PARTIAL.ToString(),
                                                refundValue.ToString("0.00", CultureInfo.InvariantCulture), item.TransactionID);

                                    if (!refundResult)
                                        return false;

                                    refundValue -= refundValue;
                                }
                                else
                                {
                                    refundResult = this.RefundPayment(reservation,
                                            OB.Reservation.BL.Constants.PaypalRefundType.FULL.ToString(),
                                            (item.GrossAmount - totalRefunded).ToString("0.00", CultureInfo.InvariantCulture), item.TransactionID);

                                    if (!refundResult)
                                        return false;

                                    refundValue = refundValue - (item.GrossAmount - totalRefunded);
                                }
                            }
                        }
                        else
                            return false;
                    }
                }

                if (!this.UpdateRecurringProfile(paypalSrv, profileId, paymentGatewayTransactionId, reservation, "CANCEL"))
                    return false;
            }

            return true;
        }

        /// <summary>
        /// Full Refund of all Installments
        /// </summary>
        /// <param name="paypalSrv"></param>
        /// <param name="transactions"></param>
        /// <param name="reservation"></param>
        /// <returns></returns>
        private bool FullRecurringPaymentsRefund(IPaypal paypalSrv, PaymentTransactionSearch transactions, contractsReservations.Reservation reservation)
        {
            foreach (var item in transactions.Transactions)
            {
                if (item.Status.Trim().ToUpper() == "CREATED" || item.Status.Trim().ToUpper() == "UPDATED" || item.GrossAmount <= 0)
                    continue;

                var refundResult = true;

                var transaction = paypalSrv.GetTransactionDetails(item.TransactionID);
                if (transaction.Ack.Trim().ToUpper().Equals("SUCCESS"))
                {
                    if (transaction.TransactionInfo.PaymentStatus.Trim().ToUpper() == "COMPLETED" && item.GrossAmount > 0)
                    {
                        refundResult = this.RefundPayment(reservation,
                                    OB.Reservation.BL.Constants.PaypalRefundType.FULL.ToString(),
                                    item.GrossAmount.ToString("0.00", CultureInfo.InvariantCulture), item.TransactionID);

                        if (!refundResult)
                            return false;
                    }
                    else if (transaction.TransactionInfo.PaymentStatus.Trim().ToUpper() == "PARTIALLYREFUNDED" && item.GrossAmount > 0)
                    {
                        decimal totalRefunded = 0;
                        var allTransactions = paypalSrv.TransactionSearchByTransactionIdAPIOperation(item.TransactionID, (DateTime)reservation.CreatedDate);
                        if (allTransactions.Ack.Trim().ToUpper().Equals("SUCCESS"))
                        {
                            totalRefunded = allTransactions.Transactions.Where(x => x.Type.Trim().ToUpper().Equals("REFUND")).Sum(x => x.GrossAmount);
                        }

                        if (totalRefunded != item.GrossAmount)
                            refundResult = this.RefundPayment(reservation,
                                        OB.Reservation.BL.Constants.PaypalRefundType.PARTIAL.ToString(),
                                        (item.GrossAmount - totalRefunded).ToString("0.00", CultureInfo.InvariantCulture), item.TransactionID);

                        if (!refundResult)
                            return false;
                    }
                }
                else
                    return false;
            }

            return true;
        }

        private void ValidateCaptureRequest(CapturePaymentResponse response, CapturePaymentRequest request)
        {
            if (string.IsNullOrEmpty(request.PayerId))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.PayerId)));

            if (string.IsNullOrEmpty(request.Token))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.Token)));

            if (string.IsNullOrEmpty(request.PaypalAutoGeneratedId))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.PaypalAutoGeneratedId)));

            if (request.Reservation == null)
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.Reservation)));

            if (request.ReservationRooms == null || !request.ReservationRooms.Any())
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.ReservationRooms)));
        }

        private void ValidatePaypalInstallmentsAuthorizationRequest(PaypalVerifyInstallmentsAuthorizationResponse response, PaypalVerifyInstallmentsAuthorizationRequest request)
        {
            if (string.IsNullOrEmpty(request.Token))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.Token)));

            if (string.IsNullOrEmpty(request.PaypalAutoGeneratedId))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.PaypalAutoGeneratedId)));
        }

        private void ValidateRecurringBillingRequest(CreateRecurringBillingResponse response, CreateRecurringBillingRequest request)
        {
            if (string.IsNullOrEmpty(request.PropertyName))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.PropertyName)));

            if (string.IsNullOrEmpty(request.Token))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.Token)));

            if (string.IsNullOrEmpty(request.PaypalAutoGeneratedId))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.PaypalAutoGeneratedId)));

            if (request.Reservation == null)
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.Reservation)));

            if (request.ReservationRooms == null || !request.ReservationRooms.Any())
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.ReservationRooms)));

            if(!request.LanguageUID.HasValue || (request.LanguageUID.HasValue && request.LanguageUID <= 0))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.LanguageUID)));
        }

        private void ValidateCancelRecurringBillingRequest(CancelAndRefundRecurringBillingResponse response, CancelAndRefundRecurringBillingRequest request)
        {
            if (request.PaymentGatewayTransactionId <= 0)
                response.Errors.Add(Errors.InvalidParameter.ToContractError(nameof(request.PaymentGatewayTransactionId)));

            if (string.IsNullOrEmpty(request.ProfileId))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.ProfileId)));

            if (request.Reservation == null)
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.Reservation)));
        }

        private void ValidateRefundPayment(RefundPaymentResponse response, RefundPaymentRequest request)
        {
            if (!request.TransactionId.HasValue)
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.TransactionId)));

            if (string.IsNullOrEmpty(request.PaypalTransactionId))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.PaypalTransactionId)));

            if (string.IsNullOrEmpty(request.RefundAmount))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.RefundAmount)));

            if (request.ReservationCurrency <= 0)
                response.Errors.Add(Errors.InvalidParameter.ToContractError(nameof(request.ReservationCurrency)));

            if (string.IsNullOrEmpty(request.ReservationNumber))
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.ReservationNumber)));

            if (request.PropertyId <= 0)
                response.Errors.Add(Errors.RequiredParameter.ToContractError(nameof(request.PropertyId)));

        }

        #endregion HELPERS

        #region LOG

        /// <summary>
        /// Log Transaction
        /// </summary>
        /// <param name="request"></param>
        /// <param name="isTestMode"></param>
        /// <returns></returns>
        private long LogTransaction(SetExpressCheckoutRequest request, SetExpressCheckoutResponse response, bool isTestMode)
        {
            using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Payments))
            {
                var transactionRepo = RepositoryFactory.GetRepository<PaymentGatewayTransaction>(unitOfWork);

                // Create Transation
                PaymentGatewayTransaction transaction = new PaymentGatewayTransaction
                {
                    PaymentGatewayAutoGeneratedUID = request.UniqueId,
                    PaymentGatewayName = "Paypal",
                    Property = _propertyId,
                    OrderType = "Sale",
                    TransactionEnviroment = isTestMode ? "TEST" : "LIVE",
                    ServerDate = DateTime.UtcNow,
                    TransactionType = "Sale",
                    PaymentGatewayOrderID = response.Token
                };

                // Set Errors
                if (response.Errors != null)
                    foreach (var item in response.Errors)
                    {
                        transaction.TransactionErrorMessage += "Code: " + item.ErrorCode + " - " + item.LongMessage + ";";
                    }

                transactionRepo.Add(transaction);
                unitOfWork.Save();

                return transaction.UID;
            }
        }

        /// <summary>
        /// Log Transation Details
        /// </summary>
        /// <param name="transactionId"></param>
        /// <param name="requestType"></param>
        /// <param name="response"></param>
        private void LogTransactionDetails(long transactionId, string requestType, string responseCode, string responseJson, string requestJson, string refundTransactionId = null)
        {
            using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Payments))
            {
                var transactionRepo = RepositoryFactory.GetRepository<PaymentGatewayTransactionsDetail>(unitOfWork);

                PaymentGatewayTransactionsDetail transactionDetails = new PaymentGatewayTransactionsDetail
                {
                    PaymentGatewayTransactionId = transactionId,
                    RequestJson = requestJson,
                    ResponseJson = responseJson,
                    ResponseCode = responseCode,
                    RequestType = requestType,
                    RefundTransactionID = refundTransactionId
                };

                transactionRepo.Add(transactionDetails);
                unitOfWork.Save();
            }
        }

        /// <summary>
        /// Log Transation Details
        /// </summary>
        /// <param name="transactionId"></param>
        /// <param name="requestType"></param>
        /// <param name="response"></param>
        private void LogTransactionDetailsByPaypalAutoGeneratedId(string paypalAutoGeneratedId, string requestType, string responseCode, string responseJson, string requestJson)
        {
            using (var unitOfWork = SessionFactory.GetUnitOfWork(DomainScopes.Payments))
            {
                var transactionRepo = RepositoryFactory.GetPaymentGatewayTransactionRepository(unitOfWork);
                var transactionDetailsRepo = RepositoryFactory.GetRepository<PaymentGatewayTransactionsDetail>(unitOfWork);

                var transaction = transactionRepo.FirstOrDefault(x => x.PaymentGatewayAutoGeneratedUID == paypalAutoGeneratedId);
                if (transaction == null)
                    return;

                PaymentGatewayTransactionsDetail transactionDetails = new PaymentGatewayTransactionsDetail
                {
                    PaymentGatewayTransactionId = transaction.UID,
                    RequestJson = requestJson,
                    ResponseJson = responseJson,
                    ResponseCode = responseCode,
                    RequestType = requestType
                };

                transactionDetailsRepo.Add(transactionDetails);
                unitOfWork.Save();
            }
        }

        #endregion
    }
}
