using System;

namespace OB.Reservation.BL.Contracts.Data
{
    public partial class PaymentResultMessage
    {
        public PaymentResultMessage()
        {
        }

        public bool IsTransactionValid { get; set; }

        public string PaymentGatewayTransactionStatusCode { get; set; }

        public string PaymentGatewayName { get; set; }

        public string PaymentGatewayProcessorName { get; set; }

        public string PaymentGatewayTransactionID { get; set; }

        public decimal PaymentAmountCaptured { get; set; }

        //[Key]
        public string PaymentGatewayOrderID { get; set; }

        public string PaymentGatewayTransactionType { get; set; }

        public DateTime PaymentGatewayTransactionDateTime { get; set; }

        public string PaymentGatewayAutoGeneratedUID { get; set; }

        public string TransactionMessage { get; set; }

        public string ErrorMessage { get; set; }

        public int? Error { get; set; }
    }
}