using OB.BL.Operations.Interfaces;
using OB.Reservation.BL.Contracts.Requests;
using OB.Reservation.BL.Contracts.Responses;
using OB.REST.Services.Attributes;
using System;
using System.Collections.Generic;
using System.Security.Permissions;
using System.Web.Http;

namespace OB.REST.Services.Controllers
{
    public class PaypalGatewayController : BaseController
    {
        private IPaypalGatewayManagerPOCO _paypalGatewayManager;

        public PaypalGatewayController(IPaypalGatewayManagerPOCO paypalGatewayManager)
        {
            _paypalGatewayManager = paypalGatewayManager;
        }

        /// <summary>
        /// RESTful implementation of the GetPayPalPaymentURL operation.
        /// This operation get paypal payment url.
        /// </summary>
        /// <param name="request">A GetPayPalPaymentURLRequest object containing the criteria</param>
        /// <returns>A GetPayPalPaymentURLResponse containing the URL and Token</returns>
        [AcceptVerbs("POST")]
        [RequiresPermission("Admin")]
        [System.Web.Http.Description.ApiExplorerSettings(IgnoreApi = true)]
        public GetPayPalPaymentURLResponse GetPayPalPaymentURL(GetPayPalPaymentURLRequest request)
        {
            return _paypalGatewayManager.GetPayPalPaymentURL(request);
        }

        [AcceptVerbs("POST")]
        [RequiresPermission("Admin")]
        [System.Web.Http.Description.ApiExplorerSettings(IgnoreApi = true)]
        public LogTransactionResponse LogPaypalTransaction(LogTransactionRequest request)
        {
            return _paypalGatewayManager.LogPaypalTransaction(request);
        }

        /// <summary>
        /// RESTful implementation of the CapturePayment operation.
        /// This operation capture Paypal Payment
        /// </summary>
        /// <remarks>
        /// <para>Required Parameters:</para>
        /// <para>- PayerId</para>
        /// <para>- Token</para>
        /// <para>- PaypalAutoGeneratedId</para>
        /// <para>- Reservation</para>
        /// <para>- ReservationRooms</para>
        /// </remarks>
        /// <param name="request">The request containing the criteria</param>
        /// <returns>An CreateRecurringBillingResponse that contains the PaypalTransation Id of the operation.</returns>
        [AcceptVerbs("POST")]
        [RequiresPermission("Admin")]
        public CapturePaymentResponse CapturePayment(CapturePaymentRequest request)
        {
            return _paypalGatewayManager.CapturePayment(request);
        }

        /// <summary>
        /// RESTful implementation of the PaypalVerifyInstallmentsAuthorization operation.
        /// This operation verify if authorization was successfull
        /// </summary>
        /// <remarks>
        /// <para>Required Parameters:</para>
        /// <para>- Token</para>
        /// <para>- PaypalAutoGeneratedId</para>
        /// <para>Optional Parameters:</para>
        /// <para>- Reservation</para>
        /// <para>- ReservationRooms</para>
        /// </remarks>
        /// <param name="request">The request containing the criteria</param>
        /// <returns>An PaypalVerifyInstallmentsAuthorizationResponse that contains the status of the operation.</returns>
        [AcceptVerbs("POST")]
        [RequiresPermission("Admin")]
        public PaypalVerifyInstallmentsAuthorizationResponse PaypalVerifyInstallmentsAuthorization(PaypalVerifyInstallmentsAuthorizationRequest request)
        {
            return _paypalGatewayManager.PaypalVerifyInstallmentsAuthorization(request);
        }

        /// <summary>
        /// Create Recurring Billing 
        /// </summary>
        /// <returns></returns>
        /// 
        /// <summary>
        /// RESTful implementation of the CreateRecurringBilling operation.
        /// This operation create a recurring billing 
        /// </summary>
        /// <remarks>
        /// <para>Required Parameters:</para>
        /// <para>- Token</para>
        /// <para>- PropertyName</para>
        /// <para>- PaypalAutoGeneratedId</para> 
        /// <para>- Reservation</para>
        /// <para>- ReservationRooms</para>
        /// </remarks>
        /// <param name="request">The request containing the criteria</param>
        /// <returns>An PaypalVerifyInstallmentsAuthorizationResponse that contains the status of the operation.</returns>
        [AcceptVerbs("POST")]
        [RequiresPermission("Admin")]
        public CreateRecurringBillingResponse CreateRecurringBilling(CreateRecurringBillingRequest request)
        {
            return _paypalGatewayManager.CreateRecurringBilling(request);
        }


        /// <summary>
        /// RESTful implementation of the CancelAndRefundRecurringBilling operation.
        /// This operation cancel a Recurring payment, refund if paid
        /// </summary>
        /// <remarks>
        /// <para>Required Parameters:</para>
        /// <para>- PaymentGatewayTransactionId</para>
        /// <para>- ProfileId</para>
        /// <para>- IsPartialRefund</para> 
        /// <para>- Reservation</para>
        /// <para>Optional Parameters:</para>
        /// <para>- Action [CANCEL, SUSPEND, REACTIVATE]</para>
        /// <para>- Note</para>
        /// </remarks>
        /// <param name="request">The request containing the criteria</param>
        /// <returns>An CancelAndRefundRecurringBillingResponse that contains the status of the operation.</returns>
        [AcceptVerbs("POST")]
        [RequiresPermission("Admin")]
        public CancelAndRefundRecurringBillingResponse CancelAndRefundRecurringBilling(CancelAndRefundRecurringBillingRequest request)
        {
            return _paypalGatewayManager.CancelAndRefundRecurringBilling(request);
        }


        /// <summary>
        /// RESTful implementation of the RefundPayment operation.
        /// This operation refund Paypal Payment
        /// </summary>
        /// <remarks>
        /// <para>Required Parameters:</para>
        /// <para>- TransactionId</para>
        /// <para>- PaypalTransactionId</para>
        /// <para>- RefundType [OTHER,FULL,PARTIAL,EXTERNALDISPUTE]</para> 
        /// <para>- RefundAmount</para>
        /// <para>- ReservationCurrency</para>
        /// <para>- ReservationNumber</para>
        /// </remarks>
        /// <param name="request">The request containing the criteria</param>
        /// <returns>An RefundPaymentResponse that contains the status of the operation.</returns>
        [AcceptVerbs("POST")]
        [RequiresPermission("Admin")]
        public RefundPaymentResponse RefundPayment(RefundPaymentRequest request)
        {
            return _paypalGatewayManager.RefundPayment(request);
        }
    }
}