using OB.DL.Common.QueryResultObjects;
using OB.Domain.Payments;
using PaymentGatewaysLibrary;
using System.Collections.Generic;
using OB.Reservation.BL.Contracts.Requests;
using OB.Reservation.BL.Contracts.Responses;

namespace OB.BL.Operations.Interfaces
{
    public interface IPaymentGatewayManagerPOCO
    {

        void LogPaymentTransactionInformationCustom(OB.BL.Contracts.Data.Payments.PaymentGatewayConfiguration config, PaymentMessageResult result, string guestInfo);

        #region PAYPAL

        Dictionary<string, string> GetPaypalConfig(long propertyId, bool isTestMode);
        PaymentGatewayTransaction GetPaymentGatewayTransactionByPaymentGatewayAutoGeneratedUID(string paymentGatewayAutoGeneratedUID);
        Dictionary<string, string> GetInfoForPaypalRequest(long rateId, long roomId, long languageId);

        #endregion

        InsertPaymentGatewayTransationResponse InsertPaymentGatewayTransation(InsertPaymentGatewayTransationRequest request);
        UpdatePaymentGatewayTransationResponse UpdatePaymentGatewayTransation(UpdatePaymentGatewayTransationRequest request);
        InsertPaymentGatewayTransationDetailsResponse InsertPaymentGatewayTransationDetails(InsertPaymentGatewayTransationDetailsRequest request);
        UpdatePaymentGatewayTransationDetailsResponse UpdatePaymentGatewayTransationDetails(UpdatePaymentGatewayTransationDetailsRequest request);

    }
}
