using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace OB.Reservation.BL.Contracts.Requests
{
    [DataContract]
    public class ListPaymentGatewayTransactionsRequest : RequestBase
    {
        [DataMember]
        public List<long> UIDs { get; set; }

        [DataMember]
        public List<string> PaymentGatewayNames { get; set; }

        [DataMember]
        public List<long> PropertyUIDs { get; set; }

        [DataMember]
        public List<string> PaymentGatewayOrderIDs { get; set; }

        [DataMember]
        public List<string> PaymentGatewayAutoGeneratedUIDs { get; set; }

        [DataMember]
        public List<string> TransactionIDs { get; set; }

        [DataMember]
        public List<string> TransactionCodes { get; set; }

        [DataMember]
        public List<string> TransactionStatus { get; set; }

        [DataMember]
        public List<string> TransactionTypes { get; set; }

        [DataMember]
        public List<string> RefundTransactionIDs { get; set; }

        [DataMember]
        public List<string> PaypalProfileIDs { get; set; }

        [DataMember]
        public List<string> TransactionRequests { get; set; }
    }
}
