//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.DL.Model.Reservations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using OB.Domain.Reservations;
    using System.CodeDom.Compiler;
        
    [GeneratedCode("OB TM T4 Domain Object template","1.0")]
    internal partial class ReservationsContext : DbContext
    {
        public ReservationsContext()
            : base("name=ReservationsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CancelReservationReason> CancelReservationReasons { get; set; }
        public virtual DbSet<LostReservation> LostReservations { get; set; }
        public virtual DbSet<ReservationPartialPaymentDetail> ReservationPartialPaymentDetails { get; set; }
        public virtual DbSet<ReservationPaymentDetail> ReservationPaymentDetails { get; set; }
        public virtual DbSet<ReservationRoomChild> ReservationRoomChilds { get; set; }
        public virtual DbSet<ReservationRoomDetail> ReservationRoomDetails { get; set; }
        public virtual DbSet<ReservationRoomDetailsAppliedIncentive> ReservationRoomDetailsAppliedIncentives { get; set; }
        public virtual DbSet<ReservationRoomDetailsAppliedPromotionalCode> ReservationRoomDetailsAppliedPromotionalCodes { get; set; }
        public virtual DbSet<ReservationRoomExtra> ReservationRoomExtras { get; set; }
        public virtual DbSet<ReservationRoomExtrasAvailableDate> ReservationRoomExtrasAvailableDates { get; set; }
        public virtual DbSet<ReservationRoomExtrasSchedule> ReservationRoomExtrasSchedules { get; set; }
        public virtual DbSet<ReservationRoom> ReservationRooms { get; set; }
        public virtual DbSet<ReservationRoomTaxPolicy> ReservationRoomTaxPolicies { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<ReservationsHistory> ReservationsHistories { get; set; }
        public virtual DbSet<ReservationStatus> ReservationStatuses { get; set; }
        public virtual DbSet<ReservationStatusLanguage> ReservationStatusLanguages { get; set; }
        public virtual DbSet<ReservationTransactionStatu> ReservationTransactionStatus { get; set; }
        public virtual DbSet<TokenizedCreditCardsReadsPerMonth> TokenizedCreditCardsReadsPerMonths { get; set; }
        public virtual DbSet<VisualState> VisualStates { get; set; }
        public virtual DbSet<ReservationRoomFilter> ReservationRoomFilters { get; set; }
        public virtual DbSet<CancelReservationReasonLanguage> CancelReservationReasonLanguages { get; set; }
        public virtual DbSet<ReservationsAdditionalData> ReservationsAdditionalDatas { get; set; }
        public virtual DbSet<ReservationFilter> ReservationFilters { get; set; }
    }
}
