using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;
using OB.BL.Contracts.Data.ProactiveActions;
using OB.Domain.Reservations;
using OB.Reservation.BL.Contracts.Data.CRM;
using Ploeh.SemanticComparison;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using contractReservation = OB.Reservation.BL.Contracts.Data.Reservations;
using crmOB = OB.BL.Contracts.Data.CRM;
using domainReservation = OB.Domain.Reservations;

namespace OB.BL.Operations.Helper
{
    static class ReservationAssert
    {
        public const int SLEEP_TIME = 5000;

        #region ASSERT DOMAIN RESERVATION

        public static void AssertAllReservationObjects(Helper.ReservationData expectedData, Helper.ReservationData databaseData, bool ignoreRecursiveObjects = false, bool verifyPolicies = false)
        {
            // asserts
            AssertReservationDetail(expectedData.reservationDetail, databaseData.reservationDetail);
            AssertGuest(expectedData.guest, databaseData.guest);
            AssertReservationRooms(expectedData.reservationRooms, databaseData.reservationRooms, verifyPolicies: verifyPolicies);
            //AssertReservationRoomDetails(expectedData.reservationRoomDetails, databaseData.reservationRoomDetails);
            AssertGuestActivity(expectedData.guestActivityObj, databaseData.guestActivityObj);
            AssertReservationRoomExtra(expectedData.reservationRoomExtras, databaseData.reservationRoomExtras, true);
            AssertReservationRoomChild(expectedData.reservationRoomChild, databaseData.reservationRoomChild);
            AssertReservationPaymentDetail(expectedData.reservationPaymentDetail, databaseData.reservationPaymentDetail);
            AssertReservationRoomExtrasSchedule(expectedData.reservationExtraSchedule, databaseData.reservationExtraSchedule);
        }

        public static void AssertReservationDetail(domainReservation.Reservation expectedResult, domainReservation.Reservation result)
        {
            var comparer = new Likeness<domainReservation.Reservation, domainReservation.Reservation>(result);

            comparer = comparer
                .Without(x => x.UID)
                .Without(x => x.InternalNotesHistory)
                .Without(x => x.Guest_UID)
                .Without(x => x.CreatedDate)
                .Without(x => x.ModifyDate)
                .Without(x => x.ReservationPartialPaymentDetails)
                .Without(x => x.ReservationPaymentDetails)
                .Without(x => x.Revision)
                .Without(x => x.ReservationRooms)
                .Without(x => x.PaymentGatewayTransactionDateTime);
            comparer.ShouldEqual(expectedResult);

            Assert.IsTrue(result.CreatedDate.HasValue == expectedResult.CreatedDate.HasValue && result.CreatedDate.Value.Date == expectedResult.CreatedDate.Value.Date);
            Assert.IsTrue(result.ModifyDate.HasValue == expectedResult.ModifyDate.HasValue);
            Assert.IsTrue(result.ModifyDate.HasValue ? result.ModifyDate.Value.Date == expectedResult.ModifyDate.Value.Date : true);
            Assert.IsTrue(!string.IsNullOrEmpty(result.Number));
        }

        public static void AssertReservationDetailPaymentGateway(domainReservation.Reservation expectedResult, domainReservation.Reservation result)
        {
            var comparer = new Likeness<domainReservation.Reservation, domainReservation.Reservation>(result);

            comparer = comparer
                .Without(x => x.UID)
                .Without(x => x.InternalNotesHistory)
                .Without(x => x.Guest_UID)
                .Without(x => x.TransferLocation_UID)
                .Without(x => x.CreatedDate)
                .Without(x => x.ModifyDate)
                .Without(x => x.PaymentGatewayTransactionID)
                .Without(x => x.PaymentGatewayOrderID)
                .Without(x => x.PaymentGatewayAutoGeneratedUID)
                .Without(x => x.PaymentGatewayTransactionDateTime)
                .Without(x => x.BESpecialRequests1_UID)
                .Without(x => x.BESpecialRequests2_UID)
                .Without(x => x.BESpecialRequests3_UID)
                .Without(x => x.BESpecialRequests4_UID)
                .Without(x => x.ReservationPartialPaymentDetails)
                .Without(x => x.ReservationPaymentDetails)
                .Without(x => x.Revision)
                .Without(x => x.ReservationRooms);
            comparer.ShouldEqual(expectedResult);


            Assert.IsTrue(expectedResult.InternalNotesHistory == null || (expectedResult.InternalNotesHistory != null && (result.InternalNotesHistory.Contains(expectedResult.InternalNotesHistory))));
            Assert.IsTrue(result.CreatedDate.HasValue == expectedResult.CreatedDate.HasValue && result.CreatedDate.Value.Date == expectedResult.CreatedDate.Value.Date);
            Assert.IsTrue(result.ModifyDate.HasValue == expectedResult.ModifyDate.HasValue);
            Assert.IsTrue(result.ModifyDate.HasValue ? result.ModifyDate.Value.Date == expectedResult.ModifyDate.Value.Date : true);
            Assert.IsTrue(!string.IsNullOrEmpty(result.Number));

            Assert.IsTrue(result.PaymentGatewayTransactionDateTime.HasValue && result.PaymentGatewayTransactionDateTime.Value.Date == DateTime.UtcNow.Date);
            Assert.IsTrue(!string.IsNullOrEmpty(result.PaymentGatewayOrderID));
            Assert.IsTrue(!string.IsNullOrEmpty(result.PaymentGatewayAutoGeneratedUID));
        }

        public static void AssertGuest(crmOB.Guest expectedResult, crmOB.Guest result)
        {
            if (expectedResult.UID == 0)
            {
                var comparer = new Likeness<crmOB.Guest, crmOB.Guest>(result);
                comparer
                    .Without(x => x.UID)
                    .Without(x => x.UserPassword)
                    .Without(x => x.CreateDate)
                    .Without(x => x.ModifyDate)
                    //.Without(x => x.GuestsExternalSources)
                    .Without(x => x.GuestSocialProviders)
                    .Without(x => x.GuestActivities)
                    .Without(x => x.GuestCategory_UID)
                    .Without(x => x.GuestFavoriteExtras)
                    .Without(x => x.GuestFavoriteSpecialRequests)
                    .ShouldEqual(expectedResult);
            }
            else
            {
                var comparer = new Likeness<crmOB.Guest, crmOB.Guest>(result).OmitAutoComparison();
                comparer
                    .WithDefaultEquality(x => x.FirstName)
                    .WithDefaultEquality(x => x.LastName)
                    .WithDefaultEquality(x => x.Email)
                    .ShouldEqual(expectedResult);
            }
        }

        public static void AssertReservationRooms(List<ReservationRoom> expectedResult, List<ReservationRoom> result, bool verifyPolicies = false)
        {
            var comparer = new Likeness<List<ReservationRoom>, List<ReservationRoom>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                ReservationRoom expectedEntry = expectedResult.ElementAt(i);
                ReservationRoom entry = result.ElementAt(i);

                var entryComparer = new Likeness<ReservationRoom, ReservationRoom>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.Reservation_UID)
                    .Without(x => x.CreatedDate)
                    .Without(x => x.ModifiedDate)
                    .Without(x => x.ReservationRoomChilds)
                    .Without(x => x.ReservationRoomDetails)
                    .Without(x => x.ReservationRoomExtras)
                    .Without(x => x.ReservationRoomTaxPolicies)
                    .Without(x => x.Reservation)
                    .Without(x => x.CancellationPolicy)
                    .Without(x => x.DepositPolicy)
                    .Without(x => x.OtherPolicy)
                    .Without(x => x.Revision)
                    .ShouldEqual(expectedEntry);

                if (verifyPolicies)
                {
                    Assert.IsTrue(entry.CancellationPolicy == expectedEntry.CancellationPolicy, "different cancellation policies");
                    Assert.IsTrue(entry.DepositPolicy == expectedEntry.DepositPolicy, "different deposit policies");
                    Assert.IsTrue(entry.OtherPolicy == expectedEntry.OtherPolicy, "different other policies");
                }
            }
        }

        public static void AssertReservationRoomDetails(List<domainReservation.ReservationRoomDetail> expectedResult, List<domainReservation.ReservationRoomDetail> result)
        {
            expectedResult = expectedResult.OrderBy(x => x.ReservationRoom_UID).ThenBy(x => x.Date).ToList();
            result = result.OrderBy(x => x.ReservationRoom_UID).ThenBy(x => x.Date).ToList();

            var comparer = new Likeness<List<domainReservation.ReservationRoomDetail>, List<domainReservation.ReservationRoomDetail>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                domainReservation.ReservationRoomDetail expectedEntry = expectedResult.ElementAt(i);
                domainReservation.ReservationRoomDetail entry = result.ElementAt(i);

                var entryComparer = new Likeness<domainReservation.ReservationRoomDetail, domainReservation.ReservationRoomDetail>(entry);
                entryComparer
                        .Without(x => x.UID)
                        .Without(x => x.ReservationRoom_UID)
                        .Without(x => x.CreatedDate)
                        .Without(x => x.ModifiedDate)
                        .Without(x => x.ReservationRoom)
                        .Without(x => x.ReservationRoomDetailsAppliedIncentives)
                        .Without(x => x.ReservationRoomDetailsAppliedPromotionalCodes)
                        //.Without(x => x.Revision)
                        .ShouldEqual(expectedEntry);

                AssertReservationRoomDetailsAppliedIncentives(expectedEntry.ReservationRoomDetailsAppliedIncentives.ToList(), entry.ReservationRoomDetailsAppliedIncentives.ToList());
            }
        }

        public static void AssertReservationRoomDetailsAppliedIncentives(List<domainReservation.ReservationRoomDetailsAppliedIncentive> expectedResult, List<domainReservation.ReservationRoomDetailsAppliedIncentive> result)
        {
            var comparer = new Likeness<List<domainReservation.ReservationRoomDetailsAppliedIncentive>, List<domainReservation.ReservationRoomDetailsAppliedIncentive>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                domainReservation.ReservationRoomDetailsAppliedIncentive expectedEntry = expectedResult.ElementAt(i);
                domainReservation.ReservationRoomDetailsAppliedIncentive entry = result.ElementAt(i);

                var entryComparer = new Likeness<domainReservation.ReservationRoomDetailsAppliedIncentive, domainReservation.ReservationRoomDetailsAppliedIncentive>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.ReservationRoomDetails_UID)
                    .Without(x => x.ReservationRoomDetail)
                    //.Without(x => x.Revision)
                    .ShouldEqual(expectedEntry);
            }
        }

        public static void AssertReservationRoomExtrasSchedule(List<ReservationRoomExtrasSchedule> expectedResult, List<ReservationRoomExtrasSchedule> result)
        {
            var comparer = new Likeness<List<ReservationRoomExtrasSchedule>, List<ReservationRoomExtrasSchedule>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                ReservationRoomExtrasSchedule expectedEntry = expectedResult.ElementAt(i);
                ReservationRoomExtrasSchedule entry = result.ElementAt(i);

                var entryComparer = new Likeness<ReservationRoomExtrasSchedule, ReservationRoomExtrasSchedule>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.ReservationRoomExtra_UID)
                    .Without(x => x.CreatedDate)
                    .Without(x => x.ModifiedDate)
                    .Without(x => x.ReservationRoomExtra)
                    .Without(x => x.Revision)
                    .ShouldEqual(expectedEntry);

                // assert not nulls
                Assert.IsTrue(entry.ReservationRoomExtra_UID > 0);
                Assert.IsTrue(entry.CreatedDate.HasValue);
                Assert.IsTrue(entry.ModifiedDate.HasValue);

            }
        }

        public static void AssertReservationRoomExtrasAvailableDates(List<ReservationRoomExtrasAvailableDate> expectedResult, List<ReservationRoomExtrasAvailableDate> result)
        {
            var comparer = new Likeness<List<ReservationRoomExtrasAvailableDate>, List<ReservationRoomExtrasAvailableDate>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                ReservationRoomExtrasAvailableDate expectedEntry = expectedResult.ElementAt(i);
                ReservationRoomExtrasAvailableDate entry = result.ElementAt(i);

                var entryComparer = new Likeness<ReservationRoomExtrasAvailableDate, ReservationRoomExtrasAvailableDate>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.ReservationRoomExtra_UID)
                    .Without(x => x.ReservationRoomExtra)
                    .Without(x => x.Revision)
                    .ShouldEqual(expectedEntry);

                // assert not nulls
                Assert.IsTrue(entry.ReservationRoomExtra_UID > 0);
            }
        }

        public static void AssertReservationPaymentDetail(ReservationPaymentDetail expectedResult, ReservationPaymentDetail result)
        {
            if (expectedResult == null && result == null)
                return;

            var comparer = new Likeness<ReservationPaymentDetail, ReservationPaymentDetail>(result);
            comparer
                .Without(x => x.UID)
                .Without(x => x.CardNumber)
                .Without(x => x.CVV)
                .Without(x => x.HashCode)
                .Without(x => x.Reservation_UID)
                .Without(x => x.CreatedDate)
                .Without(x => x.ModifiedDate)
                .Without(x => x.CreatedDate)
                .ShouldEqual(expectedResult);

            Assert.IsTrue(!string.IsNullOrEmpty(result.CardNumber));
            Assert.IsTrue(!string.IsNullOrEmpty(result.CVV));
            Assert.IsTrue(Encoding.Unicode.GetString(expectedResult.HashCode) == Encoding.Unicode.GetString(result.HashCode));

        }

        public static void AssertReservationRoomChild(List<ReservationRoomChild> expectedResult, List<ReservationRoomChild> result)
        {
            var comparer = new Likeness<List<ReservationRoomChild>, List<ReservationRoomChild>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                ReservationRoomChild expectedEntry = expectedResult.ElementAt(i);
                ReservationRoomChild entry = result.ElementAt(i);

                var entryComparer = new Likeness<ReservationRoomChild, ReservationRoomChild>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.ReservationRoom_UID)
                    .Without(x => x.ReservationRoom)
                    //.Without(x => x.Revision)
                    .ShouldEqual(expectedEntry);

                // assert not nulls
                Assert.IsTrue(entry.ReservationRoom_UID > 0);
            }
        }

        public static void AssertReservationRoomExtra(List<ReservationRoomExtra> expectedResult, List<ReservationRoomExtra> result, bool ignoreRecursiveObjects = false)
        {
            var comparer = new Likeness<List<ReservationRoomExtra>, List<ReservationRoomExtra>>(result);

            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                ReservationRoomExtra expectedEntry = expectedResult.ElementAt(i);
                ReservationRoomExtra entry = result.ElementAt(i);

                var entryComparer = new Likeness<ReservationRoomExtra, ReservationRoomExtra>(entry);
                if (ignoreRecursiveObjects)
                {
                    entryComparer
                        .Without(x => x.UID)
                        .Without(x => x.ReservationRoom_UID)
                        .Without(x => x.CreatedDate)
                        .Without(x => x.ReservationRoom_UID)
                        .Without(x => x.ReservationRoomExtrasAvailableDates)
                        .Without(x => x.ReservationRoomExtrasSchedules)
                        .Without(x => x.ReservationRoom)  //was already verified before in the code
                        //.Without(x => x.Revision)
                        .ShouldEqual(expectedEntry);
                }
                else
                {
                    entryComparer
                        .Without(x => x.UID)
                        .Without(x => x.ReservationRoom_UID)
                        .Without(x => x.CreatedDate)
                        .Without(x => x.ReservationRoom_UID)
                        .Without(x => x.ReservationRoomExtrasAvailableDates)
                        .Without(x => x.ReservationRoomExtrasSchedules)
                        //.Without(x => x.Revision)
                        .ShouldEqual(expectedEntry);
                }
            }
        }

        public static void AssertGuestActivity(List<GuestActivity> expectedResult, List<GuestActivity> result)
        {
            var comparer = new Likeness<List<GuestActivity>, List<GuestActivity>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                GuestActivity expectedEntry = expectedResult.ElementAt(i);
                GuestActivity entry = result.ElementAt(i);

                var entryComparer = new Likeness<GuestActivity, GuestActivity>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.Guest_UID)
                    .ShouldEqual(expectedEntry);
            }
        }

        public static void AssertObjectValue(object obj, Expression<Func<object>> expr, object expectedValue)
        {
            var member = expr.Body as MemberExpression;
            var propName = member.Member.Name;

            var propInfo = obj.GetType().GetProperty(propName);
            var propValue = propInfo.GetValue(obj);


            Assert.AreEqual(expectedValue, propValue);
        }

        #endregion

        #region Assert Async operations
        //public static void AssertValidAsyncCalls(ReservationData expectedData, ReservationData databaseData)
        //{
        //    // wait for all async calls to execute
        //    Thread.Sleep(SLEEP_TIME);

        //    // check reservation emails
        //    AssertValidReservationEmails(expectedData, expectedData);

        //    // check extras emails

        //    // check close sales

        //    // check notify connectors

        //    // check tpi credit limit

        //    // check log

        //    // check occ levels

        //    // check real inventory
        //}

        public static void AssertPropertyQueue(PropertyQueue expectedResult, PropertyQueue databaseResult)
        {
            var comparer = new Likeness<PropertyQueue, PropertyQueue>(databaseResult);
            comparer
                .Without(x => x.UID)
                .Without(x => x.Date)
                .Without(x => x.PropertyEvent_UID)
                .ShouldEqual(expectedResult);

            Assert.AreEqual(expectedResult.Date.Date, databaseResult.Date.Date);
        }

        // assert negative tpi credit (positive and negative)

        // assert maxipago transaction log (positive and negative)

        // assert extra email (positive and negative)
        #endregion

        #region ASSERT CONTRACT RESERVATION

        public static void AssertAllReservationObjects(contractReservation.Reservation expectedData, contractReservation.Reservation databaseData)
        {
            // asserts
            AssertReservationDetail(expectedData, databaseData);
            AssertGuest(expectedData.Guest, databaseData.Guest);
            AssertReservationRooms(expectedData.ReservationRooms.ToList(), databaseData.ReservationRooms.ToList());
            //AssertReservationRoomDetails(expectedData.reservationRoomDetails, databaseData.reser);
            //AssertGuestActivity(expectedData.guestActivityObj, databaseData.guestActivityObj);
            //AssertReservationRoomExtra(expectedData.reservationRoomExtras, databaseData.reservationRoomExtras);
            //AssertReservationRoomChild(expectedData.reservationRoomChild, databaseData.reservationRoomChild);
            AssertReservationPaymentDetail(expectedData.ReservationPaymentDetail, databaseData.ReservationPaymentDetail);
            //AssertReservationRoomExtrasSchedule(expectedData.reservationExtraSchedule, databaseData.reservationExtraSchedule);
        }

        public static void AssertAllReservationObjectsForMainGuestChange(contractReservation.Reservation oldReservation, contractReservation.Reservation modifiedReservation)
        {
            // asserts
            ReservationAssert.AssertReservationDetailExceptGuestAndStatus(oldReservation, modifiedReservation);
            try
            {
                ReservationAssert.AssertGuest(oldReservation.Guest, modifiedReservation.Guest);
                Assert.Fail(); // raises AssertionException
            }
            catch (Exception)
            {
                // Catches the assertion exception, and the test passes
            }
            ReservationAssert.AssertReservationRoomsExceptStatus(oldReservation.ReservationRooms.ToList(), modifiedReservation.ReservationRooms.ToList());
            ReservationAssert.AssertReservationPaymentDetail(oldReservation.ReservationPaymentDetail, modifiedReservation.ReservationPaymentDetail);
        }

        public static void AssertAllReservationObjectsForRoomsGuestChange(contractReservation.Reservation oldReservation, contractReservation.Reservation modifiedReservation)
        {
            // asserts
            ReservationAssert.AssertReservationDetailExceptStatus(oldReservation, modifiedReservation);
            ReservationAssert.AssertGuest(oldReservation.Guest, modifiedReservation.Guest);
            ReservationAssert.AssertReservationRoomsExceptStatusAndGuest(oldReservation.ReservationRooms.ToList(), modifiedReservation.ReservationRooms.ToList());
            ReservationAssert.AssertReservationPaymentDetail(oldReservation.ReservationPaymentDetail, modifiedReservation.ReservationPaymentDetail);
        }

        public static void AssertReservationDetailWithGuestChange(contractReservation.Reservation expectedResult, contractReservation.Reservation result)
        {
            var comparer = new Likeness<contractReservation.Reservation, contractReservation.Reservation>(result);

            comparer = comparer
                .Without(x => x.UID)
                .Without(x => x.InternalNotesHistory)
                //.Without(x => x.Guest_UID)
                .Without(x => x.CreatedDate)
                .Without(x => x.ModifyDate)
                .Without(x => x.ReservationPartialPaymentDetails)
                .Without(x => x.ReservationPaymentDetail)
                .Without(x => x.ReservationRooms)
                .Without(x => x.Guest)
                .Without(x => x.ReservationAdditionalData);
            comparer.ShouldEqual(expectedResult);

            Assert.IsTrue(JsonConvert.SerializeObject(result.ReservationAdditionalData) == JsonConvert.SerializeObject(expectedResult.ReservationAdditionalData));
            Assert.IsTrue(expectedResult.InternalNotesHistory == null || (expectedResult.InternalNotesHistory != null && (result.InternalNotesHistory.Contains(expectedResult.InternalNotesHistory))));
            Assert.IsTrue(result.CreatedDate.HasValue == expectedResult.CreatedDate.HasValue && result.CreatedDate.Value.Date == expectedResult.CreatedDate.Value.Date);
            Assert.IsTrue(result.ModifyDate.HasValue == expectedResult.ModifyDate.HasValue);
            Assert.IsTrue(result.ModifyDate.HasValue ? result.ModifyDate.Value.Date == expectedResult.ModifyDate.Value.Date : true);
            Assert.IsTrue(!string.IsNullOrEmpty(result.Number));
        }
        
        public static void AssertReservationDetail(contractReservation.Reservation expectedResult, contractReservation.Reservation result)
        {
            var comparer = new Likeness<contractReservation.Reservation, contractReservation.Reservation>(result);

            comparer = comparer
                .Without(x => x.UID)
                .Without(x => x.InternalNotesHistory)
                //.Without(x => x.Guest_UID)
                .Without(x => x.CreatedDate)
                .Without(x => x.ModifyDate)
                .Without(x => x.ReservationPartialPaymentDetails)
                .Without(x => x.ReservationPaymentDetail)
                .Without(x => x.ReservationRooms)
                .Without(x => x.Guest)
                .Without(x => x.ReservationAdditionalData)
                .Without(x => x.Channel)
                .Without(x => x.PropertyBaseCurrencySymbol)
                .Without(x => x.ReservationBaseCurrencyExchangeRate)
                .Without(x => x.ReservationBaseCurrencySymbol);
            comparer.ShouldEqual(expectedResult);

            Assert.IsTrue(JsonConvert.SerializeObject(result.ReservationAdditionalData) == JsonConvert.SerializeObject(expectedResult.ReservationAdditionalData));
            Assert.IsTrue(expectedResult.InternalNotesHistory == null || (expectedResult.InternalNotesHistory != null && (result.InternalNotesHistory.Contains(expectedResult.InternalNotesHistory))));
            Assert.IsTrue(result.CreatedDate.HasValue == expectedResult.CreatedDate.HasValue && result.CreatedDate.Value.Date == expectedResult.CreatedDate.Value.Date);
            Assert.IsTrue(result.ModifyDate.HasValue == expectedResult.ModifyDate.HasValue);
            Assert.IsTrue(result.ModifyDate.HasValue ? result.ModifyDate.Value.Date == expectedResult.ModifyDate.Value.Date : true);
            Assert.IsTrue(!string.IsNullOrEmpty(result.Number));
        }

        public static void AssertReservationDetailExceptStatus(contractReservation.Reservation expectedResult, contractReservation.Reservation result)
        {
            var comparer = new Likeness<contractReservation.Reservation, contractReservation.Reservation>(result);

            comparer = comparer
                .Without(x => x.UID)
                .Without(x => x.InternalNotesHistory)
                //.Without(x => x.Guest_UID)
                .Without(x => x.CreatedDate)
                .Without(x => x.ModifyDate)
                .Without(x => x.ReservationPartialPaymentDetails)
                .Without(x => x.ReservationPaymentDetail)
                .Without(x => x.ReservationRooms)
                .Without(x => x.Guest)
                .Without(x => x.ReservationAdditionalData)
                .Without(x => x.Status)
                .Without(x => x.Channel)
                .Without(x => x.PropertyBaseCurrencySymbol)
                .Without(x => x.ReservationBaseCurrencyExchangeRate)
                .Without(x => x.ReservationBaseCurrencySymbol);
            comparer.ShouldEqual(expectedResult);

            Assert.IsTrue(JsonConvert.SerializeObject(result.ReservationAdditionalData) == JsonConvert.SerializeObject(expectedResult.ReservationAdditionalData));
            Assert.IsTrue(expectedResult.InternalNotesHistory == null || (expectedResult.InternalNotesHistory != null && (result.InternalNotesHistory.Contains(expectedResult.InternalNotesHistory))));
            Assert.IsTrue(result.CreatedDate.HasValue == expectedResult.CreatedDate.HasValue && result.CreatedDate.Value.Date == expectedResult.CreatedDate.Value.Date);
            Assert.IsTrue(result.ModifyDate.HasValue == expectedResult.ModifyDate.HasValue);
            Assert.IsTrue(result.ModifyDate.HasValue ? result.ModifyDate.Value.Date == expectedResult.ModifyDate.Value.Date : true);
            Assert.IsTrue(!string.IsNullOrEmpty(result.Number));
        }

        public static void AssertReservationDetailExceptGuestAndStatus(contractReservation.Reservation expectedResult, contractReservation.Reservation result)
        {
            var comparer = new Likeness<contractReservation.Reservation, contractReservation.Reservation>(result);

            comparer = comparer
                .Without(x => x.UID)
                .Without(x => x.InternalNotesHistory)
                //.Without(x => x.Guest_UID)
                .Without(x => x.CreatedDate)
                .Without(x => x.ModifyDate)
                .Without(x => x.ReservationPartialPaymentDetails)
                .Without(x => x.ReservationPaymentDetail)
                .Without(x => x.ReservationRooms)
                .Without(x => x.Guest)
                .Without(x => x.ReservationAdditionalData)
                .Without(x => x.Status)
                .Without(x => x.GuestFirstName)
                .Without(x => x.GuestLastName)
                .Without(x => x.Channel)
                .Without(x => x.PropertyBaseCurrencySymbol)
                .Without(x => x.ReservationBaseCurrencyExchangeRate)
                .Without(x => x.ReservationBaseCurrencySymbol)
                .Without(x => x.GuestEmail)
                .Without(x => x.GuestPhone)
                .Without(x => x.GuestIDCardNumber)
                .Without(x => x.GuestCountry_UID)
                .Without(x => x.GuestCity)
                .Without(x => x.GuestState_UID);
            comparer.ShouldEqual(expectedResult);

            Assert.IsTrue(JsonConvert.SerializeObject(result.ReservationAdditionalData) == JsonConvert.SerializeObject(expectedResult.ReservationAdditionalData));
            Assert.IsTrue(expectedResult.InternalNotesHistory == null || (expectedResult.InternalNotesHistory != null && (result.InternalNotesHistory.Contains(expectedResult.InternalNotesHistory))));
            Assert.IsTrue(result.CreatedDate.HasValue == expectedResult.CreatedDate.HasValue && result.CreatedDate.Value.Date == expectedResult.CreatedDate.Value.Date);
            Assert.IsTrue(result.ModifyDate.HasValue == expectedResult.ModifyDate.HasValue);
            Assert.IsTrue(result.ModifyDate.HasValue ? result.ModifyDate.Value.Date == expectedResult.ModifyDate.Value.Date : true);
            Assert.IsTrue(!string.IsNullOrEmpty(result.Number));
        }

        public static void AssertReservationDetailPaymentGateway(contractReservation.Reservation expectedResult, contractReservation.Reservation result)
        {
            var comparer = new Likeness<contractReservation.Reservation, contractReservation.Reservation>(result);

            comparer = comparer
                .Without(x => x.UID)
                .Without(x => x.InternalNotesHistory)
                .Without(x => x.Guest_UID)
                .Without(x => x.TransferLocation_UID)
                .Without(x => x.CreatedDate)
                .Without(x => x.ModifyDate)
                .Without(x => x.PaymentGatewayTransactionID)
                .Without(x => x.PaymentGatewayOrderID)
                .Without(x => x.PaymentGatewayAutoGeneratedUID)
                .Without(x => x.PaymentGatewayTransactionDateTime)
                .Without(x => x.BESpecialRequests1_UID)
                .Without(x => x.BESpecialRequests2_UID)
                .Without(x => x.BESpecialRequests3_UID)
                .Without(x => x.BESpecialRequests4_UID)
                .Without(x => x.ReservationPartialPaymentDetails)
                .Without(x => x.ReservationPaymentDetail)
                .Without(x => x.ReservationRooms);
            comparer.ShouldEqual(expectedResult);


            Assert.IsTrue(expectedResult.InternalNotesHistory == null || (expectedResult.InternalNotesHistory != null && (result.InternalNotesHistory.Contains(expectedResult.InternalNotesHistory))));
            Assert.IsTrue(result.CreatedDate.HasValue == expectedResult.CreatedDate.HasValue && result.CreatedDate.Value.Date == expectedResult.CreatedDate.Value.Date);
            Assert.IsTrue(result.ModifyDate.HasValue == expectedResult.ModifyDate.HasValue);
            Assert.IsTrue(result.ModifyDate.HasValue ? result.ModifyDate.Value.Date == expectedResult.ModifyDate.Value.Date : true);
            Assert.IsTrue(!string.IsNullOrEmpty(result.Number));

            Assert.IsTrue(result.PaymentGatewayTransactionDateTime.HasValue && result.PaymentGatewayTransactionDateTime.Value.Date == DateTime.UtcNow.Date);
            Assert.IsTrue(!string.IsNullOrEmpty(result.PaymentGatewayOrderID));
            Assert.IsTrue(!string.IsNullOrEmpty(result.PaymentGatewayAutoGeneratedUID));
        }

        public static void AssertGuest(Guest expectedResult, Guest result)
        {
            if (expectedResult.UID == 0)
            {
                var comparer = new Likeness<Guest, Guest>(result);
                comparer
                    .Without(x => x.UID)
                    .Without(x => x.UserPassword)
                    .Without(x => x.CreateDate)
                    .Without(x => x.ModifyDate)
                    //.Without(x => x.GuestsExternalSources)
                    //.Without(x => x.GuestActivities)
                    //.Without(x => x.GuestCategory)
                    //.Without(x => x.GuestFavoriteExtras)
                    //.Without(x => x.GuestFavoriteSpecialRequests)
                    .ShouldEqual(expectedResult);
            }
            else
            {
                var comparer = new Likeness<Guest, Guest>(result).OmitAutoComparison();
                comparer
                    .WithDefaultEquality(x => x.FirstName)
                    .WithDefaultEquality(x => x.LastName)
                    .WithDefaultEquality(x => x.Email)
                    .ShouldEqual(expectedResult);
            }
        }

        public static void AssertReservationRooms(List<contractReservation.ReservationRoom> expectedResult, List<contractReservation.ReservationRoom> result)
        {
            var comparer = new Likeness<List<contractReservation.ReservationRoom>, List<contractReservation.ReservationRoom>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                contractReservation.ReservationRoom expectedEntry = expectedResult.ElementAt(i);
                contractReservation.ReservationRoom entry = result.ElementAt(i);

                var entryComparer = new Likeness<contractReservation.ReservationRoom, contractReservation.ReservationRoom>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.Reservation_UID)
                    .Without(x => x.CreatedDate)
                    .Without(x => x.ModifiedDate)
                    .Without(x => x.ReservationRoomChilds)
                    .Without(x => x.ReservationRoomDetails)
                    .Without(x => x.ReservationRoomExtras)
                    .Without(x => x.ReservationRoomTaxPolicies)
                    //.Without(x => x.Reservation)
                    .Without(x => x.CancellationPolicy)
                    .Without(x => x.DepositPolicy)
                    .Without(x => x.OtherPolicy)
                    .Without(x => x.DateFrom)
                    .Without(x => x.DateTo)
                    .Without(x => x.RoomType)
                    .Without(x => x.Rate)
                    .Without(x => x.ReservationRoomAdditionalData)
                    .Without(x => x.ReservationRoomIncentivesPeriods)
                    .Without(x => x.ReservationRoomCancelationCost)
                    .ShouldEqual(expectedEntry);

                Assert.IsTrue(JsonConvert.SerializeObject(expectedEntry.ReservationRoomAdditionalData) == JsonConvert.SerializeObject(entry.ReservationRoomAdditionalData));
                Assert.IsTrue(expectedEntry.DateFrom.Value.Date == entry.DateFrom.Value.Date);
                Assert.IsTrue(expectedEntry.DateTo.Value.Date == entry.DateTo.Value.Date);
                AssertReservationRoomDetails(expectedEntry.ReservationRoomDetails.ToList(), entry.ReservationRoomDetails.ToList());
                AssertReservationRoomExtra(expectedEntry.ReservationRoomExtras.ToList(), entry.ReservationRoomExtras.ToList());
                AssertReservationRoomChild(expectedEntry.ReservationRoomChilds.ToList(), entry.ReservationRoomChilds.ToList());
            }
        }

        public static void AssertReservationRoomsExceptStatus(List<contractReservation.ReservationRoom> expectedResult, List<contractReservation.ReservationRoom> result)
        {
            var comparer = new Likeness<List<contractReservation.ReservationRoom>, List<contractReservation.ReservationRoom>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                contractReservation.ReservationRoom expectedEntry = expectedResult.ElementAt(i);
                contractReservation.ReservationRoom entry = result.ElementAt(i);

                var entryComparer = new Likeness<contractReservation.ReservationRoom, contractReservation.ReservationRoom>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.Reservation_UID)
                    .Without(x => x.CreatedDate)
                    .Without(x => x.ModifiedDate)
                    .Without(x => x.ReservationRoomChilds)
                    .Without(x => x.ReservationRoomDetails)
                    .Without(x => x.ReservationRoomExtras)
                    .Without(x => x.ReservationRoomTaxPolicies)
                    //.Without(x => x.Reservation)
                    .Without(x => x.CancellationPolicy)
                    .Without(x => x.DepositPolicy)
                    .Without(x => x.OtherPolicy)
                    .Without(x => x.DateFrom)
                    .Without(x => x.DateTo)
                    .Without(x => x.RoomType)
                    .Without(x => x.Rate)
                    .Without(x => x.ReservationRoomAdditionalData)
                    .Without(x => x.Status)
                    .Without(x => x.ReservationRoomIncentivesPeriods)
                    .Without(x => x.ReservationRoomCancelationCost)
                    .ShouldEqual(expectedEntry);

                Assert.IsTrue(JsonConvert.SerializeObject(expectedEntry.ReservationRoomAdditionalData) == JsonConvert.SerializeObject(entry.ReservationRoomAdditionalData));
                Assert.IsTrue(expectedEntry.DateFrom.Value.Date == entry.DateFrom.Value.Date);
                Assert.IsTrue(expectedEntry.DateTo.Value.Date == entry.DateTo.Value.Date);
                AssertReservationRoomDetails(expectedEntry.ReservationRoomDetails.ToList(), entry.ReservationRoomDetails.ToList());
                AssertReservationRoomExtra(expectedEntry.ReservationRoomExtras.ToList(), entry.ReservationRoomExtras.ToList());
                AssertReservationRoomChild(expectedEntry.ReservationRoomChilds.ToList(), entry.ReservationRoomChilds.ToList());
            }
        }

        public static void AssertReservationRoomsExceptStatusAndGuest(List<contractReservation.ReservationRoom> expectedResult, List<contractReservation.ReservationRoom> result)
        {
            var comparer = new Likeness<List<contractReservation.ReservationRoom>, List<contractReservation.ReservationRoom>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                contractReservation.ReservationRoom expectedEntry = expectedResult.ElementAt(i);
                contractReservation.ReservationRoom entry = result.ElementAt(i);

                var entryComparer = new Likeness<contractReservation.ReservationRoom, contractReservation.ReservationRoom>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.Reservation_UID)
                    .Without(x => x.CreatedDate)
                    .Without(x => x.ModifiedDate)
                    .Without(x => x.ReservationRoomChilds)
                    .Without(x => x.ReservationRoomDetails)
                    .Without(x => x.ReservationRoomExtras)
                    .Without(x => x.ReservationRoomTaxPolicies)
                    //.Without(x => x.Reservation)
                    .Without(x => x.CancellationPolicy)
                    .Without(x => x.DepositPolicy)
                    .Without(x => x.OtherPolicy)
                    .Without(x => x.DateFrom)
                    .Without(x => x.DateTo)
                    .Without(x => x.RoomType)
                    .Without(x => x.Rate)
                    .Without(x => x.ReservationRoomAdditionalData)
                    .Without(x => x.Status)
                    .Without(x => x.GuestName)
                    .Without(x => x.ReservationRoomIncentivesPeriods)
                    .Without(x => x.ReservationRoomCancelationCost)
                    .ShouldEqual(expectedEntry);

                Assert.IsTrue(JsonConvert.SerializeObject(expectedEntry.ReservationRoomAdditionalData) == JsonConvert.SerializeObject(entry.ReservationRoomAdditionalData));
                Assert.IsTrue(expectedEntry.DateFrom.Value.Date == entry.DateFrom.Value.Date);
                Assert.IsTrue(expectedEntry.DateTo.Value.Date == entry.DateTo.Value.Date);
                AssertReservationRoomDetails(expectedEntry.ReservationRoomDetails.ToList(), entry.ReservationRoomDetails.ToList());
                AssertReservationRoomExtra(expectedEntry.ReservationRoomExtras.ToList(), entry.ReservationRoomExtras.ToList());
                AssertReservationRoomChild(expectedEntry.ReservationRoomChilds.ToList(), entry.ReservationRoomChilds.ToList());
            }
        }
        
        public static void AssertReservationRoomDetails(List<contractReservation.ReservationRoomDetail> expectedResult, List<contractReservation.ReservationRoomDetail> result)
        {
            expectedResult = expectedResult.OrderBy(x => x.ReservationRoom_UID).ThenBy(x => x.Date).ToList();
            result = result.OrderBy(x => x.ReservationRoom_UID).ThenBy(x => x.Date).ToList();

            var comparer = new Likeness<List<contractReservation.ReservationRoomDetail>, List<contractReservation.ReservationRoomDetail>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                contractReservation.ReservationRoomDetail expectedEntry = expectedResult.ElementAt(i);
                contractReservation.ReservationRoomDetail entry = result.ElementAt(i);

                var entryComparer = new Likeness<contractReservation.ReservationRoomDetail, contractReservation.ReservationRoomDetail>(entry);
                entryComparer
                        .Without(x => x.UID)
                        .Without(x => x.ReservationRoom_UID)
                        .Without(x => x.CreatedDate)
                        .Without(x => x.ModifiedDate)
                        .Without(x => x.ReservationRoom)
                        .Without(x => x.ReservationRoomDetailsAppliedIncentives)
                        .Without(x => x.Rate)
                        .ShouldEqual(expectedEntry);

                var entryComparer2 = new Likeness<OB.Reservation.BL.Contracts.Data.Rates.Rate, OB.Reservation.BL.Contracts.Data.Rates.Rate>(entry.Rate);
                entryComparer2.ShouldEqual(expectedEntry.Rate);

                if (entry.ReservationRoomDetailsAppliedIncentives == null)
                    entry.ReservationRoomDetailsAppliedIncentives = Enumerable.Empty<contractReservation.ReservationRoomDetailsAppliedIncentive>().ToList();

                AssertReservationRoomDetailsAppliedIncentives(expectedEntry.ReservationRoomDetailsAppliedIncentives.ToList(), entry.ReservationRoomDetailsAppliedIncentives.ToList());
            }
        }

        public static void AssertReservationRoomDetailsAppliedIncentives(List<contractReservation.ReservationRoomDetailsAppliedIncentive> expectedResult,
            List<contractReservation.ReservationRoomDetailsAppliedIncentive> result)
        {
            var comparer = new Likeness<List<contractReservation.ReservationRoomDetailsAppliedIncentive>,
                List<contractReservation.ReservationRoomDetailsAppliedIncentive>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                contractReservation.ReservationRoomDetailsAppliedIncentive expectedEntry = expectedResult.ElementAt(i);
                contractReservation.ReservationRoomDetailsAppliedIncentive entry = result.ElementAt(i);

                var entryComparer = new Likeness<contractReservation.ReservationRoomDetailsAppliedIncentive,
                    contractReservation.ReservationRoomDetailsAppliedIncentive>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.ReservationRoomDetails_UID)
                    .Without(x => x.ReservationRoomDetail)
                    .Without(x => x.Incentive)
                    .ShouldEqual(expectedEntry);

                AssertReservationRoomDetailsAppliedIncentivesIncentive(expectedEntry.Incentive, entry.Incentive);
            }
        }

        //Added by ES
        public static void AssertReservationRoomDetailsAppliedIncentivesIncentive(OB.Reservation.BL.Contracts.Data.Properties.Incentive expectedResult,
            OB.Reservation.BL.Contracts.Data.Properties.Incentive result)
        {
            if (expectedResult == result)
                return;

            Assert.AreEqual(expectedResult.UID, result.UID, "result.UID = expectedResult.UID");
            Assert.AreEqual(expectedResult.IncentiveType, result.IncentiveType, "result.IncentiveType = expectedResult.IncentiveType");
            Assert.AreEqual(expectedResult.Property_UID, result.Property_UID, "result.Property_UID = expectedResult.Property_UID");
            Assert.AreEqual(expectedResult.Name, result.Name, "result.Name = expectedResult.Name");
            Assert.AreEqual(expectedResult.Days, result.Days, "result.Days = expectedResult.Days");
            Assert.AreEqual(expectedResult.FreeDays, result.FreeDays, "result.FreeDays = expectedResult.FreeDays");
            Assert.AreEqual(expectedResult.DiscountPercentage, result.DiscountPercentage, "result.DiscountPercentage = expectedResult.DiscountPercentage");
            Assert.AreEqual(expectedResult.IsDeleted, result.IsDeleted, "result.IsDeleted = expectedResult.IsDeleted");
            Assert.AreEqual(expectedResult.IsFreeDaysAtBegin, result.IsFreeDaysAtBegin, "result.IsFreeDaysAtBegin = expectedResult.IsFreeDaysAtBegin");
            Assert.AreEqual(expectedResult.CreatedDate, result.CreatedDate, "result.CreatedDate = expectedResult.CreatedDate");
            Assert.AreEqual(expectedResult.ModifiedDate, result.ModifiedDate, "result.ModifiedDate = expectedResult.ModifiedDate");
            Assert.AreEqual(expectedResult.Revision, result.Revision, "result.Revision = expectedResult.Revision");
            Assert.AreEqual(expectedResult.MinDays, result.MinDays, "result.MinDays = expectedResult.MinDays");
            Assert.AreEqual(expectedResult.MaxDays, result.MaxDays, "result.MaxDays = expectedResult.MaxDays");
            Assert.AreEqual(expectedResult.Hours, result.Hours, "result.Hours = expectedResult.Hours");
            Assert.AreEqual(expectedResult.IsBetweenNights, result.IsBetweenNights, "result.IsBetweenNights = expectedResult.IsBetweenNights");
            Assert.AreEqual(expectedResult.IsLastMinuteInHours, result.IsLastMinuteInHours, "result.IsLastMinuteInHours = expectedResult.IsLastMinuteInHours");
        }

        public static void AssertReservationRoomExtrasSchedule(List<contractReservation.ReservationRoomExtrasSchedule> expectedResult,
            List<contractReservation.ReservationRoomExtrasSchedule> result)
        {
            var comparer = new Likeness<List<contractReservation.ReservationRoomExtrasSchedule>,
                List<contractReservation.ReservationRoomExtrasSchedule>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                contractReservation.ReservationRoomExtrasSchedule expectedEntry = expectedResult.ElementAt(i);
                contractReservation.ReservationRoomExtrasSchedule entry = result.ElementAt(i);

                var entryComparer = new Likeness<contractReservation.ReservationRoomExtrasSchedule,
                    contractReservation.ReservationRoomExtrasSchedule>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.ReservationRoomExtra_UID)
                    .Without(x => x.CreatedDate)
                    .Without(x => x.ModifiedDate)
                    //.Without(x => x.ReservationRoomExtra)
                    .ShouldEqual(expectedEntry);

                // assert not nulls
                Assert.IsTrue(entry.ReservationRoomExtra_UID > 0);
                Assert.IsTrue(entry.CreatedDate.HasValue);
                Assert.IsTrue(entry.ModifiedDate.HasValue);

            }
        }

        public static void AssertReservationRoomExtrasAvailableDates(List<Contracts.Data.Reservations.ReservationRoomExtrasAvailableDate> expectedResult,
            List<Contracts.Data.Reservations.ReservationRoomExtrasAvailableDate> result)
        {
            var comparer = new Likeness<List<Contracts.Data.Reservations.ReservationRoomExtrasAvailableDate>,
                List<Contracts.Data.Reservations.ReservationRoomExtrasAvailableDate>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                Contracts.Data.Reservations.ReservationRoomExtrasAvailableDate expectedEntry = expectedResult.ElementAt(i);
                Contracts.Data.Reservations.ReservationRoomExtrasAvailableDate entry = result.ElementAt(i);

                var entryComparer = new Likeness<Contracts.Data.Reservations.ReservationRoomExtrasAvailableDate,
                    Contracts.Data.Reservations.ReservationRoomExtrasAvailableDate>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.ReservationRoomExtra_UID)
                    //.Without(x => x.ReservationRoomExtra)
                    .ShouldEqual(expectedEntry);

                // assert not nulls
                Assert.IsTrue(entry.ReservationRoomExtra_UID > 0);
            }
        }

        public static void AssertReservationPaymentDetail(contractReservation.ReservationPaymentDetail expectedResult, contractReservation.ReservationPaymentDetail result)
        {
            if (expectedResult == null && result == null)
                return;

            var comparer = new Likeness<contractReservation.ReservationPaymentDetail, contractReservation.ReservationPaymentDetail>(result);
            comparer
                .Without(x => x.UID)
                .Without(x => x.CardNumber)
                .Without(x => x.CVV)
                .Without(x => x.Reservation_UID)
                .Without(x => x.CreatedDate)
                .Without(x => x.ModifiedDate)
                //.Without(x => x.Reservation)
                .Without(x => x.CreatedDate)
                .ShouldEqual(expectedResult);

            Assert.IsTrue(!string.IsNullOrEmpty(result.CardNumber));
            Assert.IsTrue(!string.IsNullOrEmpty(result.CVV));
        }

        public static void AssertReservationRoomChild(List<contractReservation.ReservationRoomChild> expectedResult, 
            List<contractReservation.ReservationRoomChild> result)
        {
            var comparer = new Likeness<List<contractReservation.ReservationRoomChild>,
                List<contractReservation.ReservationRoomChild>>(result);
            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                contractReservation.ReservationRoomChild expectedEntry = expectedResult.OrderBy(x => x.ChildNo).ElementAt(i);
                contractReservation.ReservationRoomChild entry = result.OrderBy(x => x.ChildNo).ElementAt(i);

                var entryComparer = new Likeness<contractReservation.ReservationRoomChild,
                    contractReservation.ReservationRoomChild>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.ReservationRoom_UID)
                    .Without(x => x.ReservationRoom)
                    .ShouldEqual(expectedEntry);

                // assert not nulls
                Assert.IsTrue(entry.ReservationRoom_UID > 0);
            }
        }

        public static void AssertReservationRoomExtra(List<contractReservation.ReservationRoomExtra> expectedResult, List<contractReservation.ReservationRoomExtra> result)
        {
            var comparer = new Likeness<List<contractReservation.ReservationRoomExtra>, 
                List<contractReservation.ReservationRoomExtra>>(result);

            comparer
                .Without(x => x.Capacity)
                .ShouldEqual(expectedResult);

            for (int i = 0; i < expectedResult.Count; i++)
            {
                contractReservation.ReservationRoomExtra expectedEntry = expectedResult.ElementAt(i);
                contractReservation.ReservationRoomExtra entry = result.ElementAt(i);

                var entryComparer = new Likeness<contractReservation.ReservationRoomExtra,
                    contractReservation.ReservationRoomExtra>(entry);
                entryComparer
                    .Without(x => x.UID)
                    .Without(x => x.ReservationRoom_UID)
                    .Without(x => x.CreatedDate)
                    //.Without(x => x.ReservationRoom)
                    .Without(x => x.ReservationRoomExtrasAvailableDates)
                    .Without(x => x.ReservationRoomExtrasSchedules)
                    .ShouldEqual(expectedEntry);

                AssertReservationRoomExtrasSchedule(expectedEntry.ReservationRoomExtrasSchedules.ToList(), entry.ReservationRoomExtrasSchedules.ToList());
            }
        }

        //public static void AssertGuestActivity(List<Contracts.Data.Reservations.GuestActivity> expectedResult, List<Contracts.Data.Reservations.GuestActivity> result)
        //{
        //    var comparer = new Likeness<List<Contracts.Data.Reservations.GuestActivity>, List<Contracts.Data.Reservations.GuestActivity>>(result);
        //    comparer
        //        .Without(x => x.Capacity)
        //        .ShouldEqual(expectedResult);

        //    for (int i = 0; i < expectedResult.Count; i++)
        //    {
        //        Contracts.Data.Reservations.GuestActivity expectedEntry = expectedResult.ElementAt(i);
        //        Contracts.Data.Reservations.GuestActivity entry = result.ElementAt(i);

        //        var entryComparer = new Likeness<Contracts.Data.GuestActivity, Contracts.Data.Reservations.GuestActivity>(entry);
        //        entryComparer
        //            .Without(x => x.UID)
        //            .Without(x => x.Guest)
        //            .ShouldEqual(expectedEntry);
        //    }
        //}

        #endregion
    }
}
