using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace OB.Reservation.BL.Contracts.Data.Payments
{
    [DataContract]
    public class PaymentGatewayTransaction : ContractBase
    {
        [DataMember]
        public long UID { get; set; }

        [DataMember]
        public string PaymentGatewayName { get; set; }

        [DataMember]
        public long Property { get; set; }

        [DataMember]
        public string PaymentGatewayOrderID { get; set; }

        [DataMember]
        public string PaymentGatewayAutoGeneratedUID { get; set; }

        [DataMember]
        public decimal? OrderCaptured { get; set; }

        [DataMember]
        public string OrderType { get; set; }

        [DataMember]
        public string TransactionID { get; set; }

        [DataMember]
        public string TransactionCode { get; set; }

        [DataMember]
        public string TransactionStatus { get; set; }

        [DataMember]
        public string TransactionMessage { get; set; }

        [DataMember]
        public string TransactionErrorMessage { get; set; }

        [DataMember]
        public string XmlMessage { get; set; }

        [DataMember]
        public string TransactionType { get; set; }

        [DataMember]
        public string TransactionEnviroment { get; set; }

        [DataMember]
        public DateTime? ServerDate { get; set; }

        [DataMember]
        public string GuestInformation { get; set; }

        [DataMember]
        public string RefundTransactionID { get; set; }

        [DataMember]
        public string PaypalProfileID { get; set; }

        [DataMember]
        public string TransactionRequest { get; set; }

        [DataMember]
        public string IdOnSource { get; set; }

        [DataMember]
        public List<Payment> PaymentDetails { get; set; }
    }

    public class Payment
    {
        [DataMember]
        public string Id { get; set; }

        [DataMember]
        public string Installments { get; set; }

        [DataMember]
        public string AuthorizationCode { get; set; }

        [DataMember]
        public string Nsu { get; set; }

        [DataMember]
        public string Tid { get; set; }

        [DataMember]
        public bool Authentication3DS { get; set; }

        [DataMember]
        public string ProviderReturnMessage { get; set; }

        [DataMember]
        public DateTime? CaptureDate { get; set; }

        [DataMember]
        public DateTime? CancellationDate { get; set; }

        [DataMember]
        public decimal? Amount { get; set; }

        [DataMember]
        public string Currency { get; set; }

        [DataMember]
        public string Provider { get; set; } 

        [DataMember]
        public string Status { get; set; } 
    }
}
