//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BillingMandatoryFields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BillingMandatoryFields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OB.BL.Resources.BillingMandatoryFields", typeof(BillingMandatoryFields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation date is not within the range of dates Contract Begin and Contract End..
        /// </summary>
        public static string lblActivationDateRange {
            get {
                return ResourceManager.GetString("lblActivationDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Begin Date is required..
        /// </summary>
        public static string lblBeginDate {
            get {
                return ResourceManager.GetString("lblBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Currency.
        /// </summary>
        public static string lblBillingCurrency {
            get {
                return ResourceManager.GetString("lblBillingCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Fee.
        /// </summary>
        public static string lblBookingFee {
            get {
                return ResourceManager.GetString("lblBookingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Cancelled.
        /// </summary>
        public static string lblCancelledExtra {
            get {
                return ResourceManager.GetString("lblCancelledExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Currency.
        /// </summary>
        public static string lblCurrency {
            get {
                return ResourceManager.GetString("lblCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract End Date is required..
        /// </summary>
        public static string lblEndDate {
            get {
                return ResourceManager.GetString("lblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract End Date is less than Contract Begin Date..
        /// </summary>
        public static string lblEndDateLess {
            get {
                return ResourceManager.GetString("lblEndDateLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Extra Added.
        /// </summary>
        public static string lblNewExtra {
            get {
                return ResourceManager.GetString("lblNewExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid by.
        /// </summary>
        public static string lblPaidBy {
            get {
                return ResourceManager.GetString("lblPaidBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation date is required..
        /// </summary>
        public static string lblRequiredActivationDate {
            get {
                return ResourceManager.GetString("lblRequiredActivationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract number is required..
        /// </summary>
        public static string lblRequiredContractNumber {
            get {
                return ResourceManager.GetString("lblRequiredContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid by is required..
        /// </summary>
        public static string lblRequiredPaidByType {
            get {
                return ResourceManager.GetString("lblRequiredPaidByType", resourceCulture);
            }
        }
    }
}
