//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OB.BL.Resources.CustomErrorMessage", typeof(CustomErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Property Account Manager.
        /// </summary>
        public static string lblAccountManagerValidateProperty {
            get {
                return ResourceManager.GetString("lblAccountManagerValidateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Category..
        /// </summary>
        public static string lblActivityCategory {
            get {
                return ResourceManager.GetString("lblActivityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string lblAdult {
            get {
                return ResourceManager.GetString("lblAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Category..
        /// </summary>
        public static string lblAmenityCategorySelect {
            get {
                return ResourceManager.GetString("lblAmenityCategorySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Attraction Category..
        /// </summary>
        public static string lblAttractionCategory {
            get {
                return ResourceManager.GetString("lblAttractionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Language Name..
        /// </summary>
        public static string lblAttractionValidateLanguageName {
            get {
                return ResourceManager.GetString("lblAttractionValidateLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Sale date must be greater than Begin Sale date..
        /// </summary>
        public static string lblBeginEndSaleDate {
            get {
                return ResourceManager.GetString("lblBeginEndSaleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount must be less than 100%..
        /// </summary>
        public static string lblCampaignPerDiscount {
            get {
                return ResourceManager.GetString("lblCampaignPerDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be greater than Start Date..
        /// </summary>
        public static string lblCampaignValidateEndDate {
            get {
                return ResourceManager.GetString("lblCampaignValidateEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount must be greater than Zero..
        /// </summary>
        public static string lblCampaignValueDiscount {
            get {
                return ResourceManager.GetString("lblCampaignValueDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Language Name..
        /// </summary>
        public static string lblCancellationPolicyValidateLanguageName {
            get {
                return ResourceManager.GetString("lblCancellationPolicyValidateLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Day..
        /// </summary>
        public static string lblCanecellationPolicyValidDay {
            get {
                return ResourceManager.GetString("lblCanecellationPolicyValidDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Value.
        /// </summary>
        public static string lblChannelServiceValidateValue {
            get {
                return ResourceManager.GetString("lblChannelServiceValidateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than 100..
        /// </summary>
        public static string lblChannelServiceValueLassthan100 {
            get {
                return ResourceManager.GetString("lblChannelServiceValueLassthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel value must be greater than zero..
        /// </summary>
        public static string lblChannelvalueGreaterthanzero {
            get {
                return ResourceManager.GetString("lblChannelvalueGreaterthanzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel value must be less than or equal to 100%..
        /// </summary>
        public static string lblChannelvalueLessthan100 {
            get {
                return ResourceManager.GetString("lblChannelvalueLessthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string lblChild {
            get {
                return ResourceManager.GetString("lblChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child group price is Required..
        /// </summary>
        public static string lblChildTermPriceRequired {
            get {
                return ResourceManager.GetString("lblChildTermPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the Maximum Age invalid..
        /// </summary>
        public static string lblChildTermsAgeFrom {
            get {
                return ResourceManager.GetString("lblChildTermsAgeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the Minimum Age invalid..
        /// </summary>
        public static string lblChildTermsAgeTo {
            get {
                return ResourceManager.GetString("lblChildTermsAgeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the Minimum Age should be less than the Maximum Age..
        /// </summary>
        public static string lblChildTermsAgeToGreterthenAgeFrom {
            get {
                return ResourceManager.GetString("lblChildTermsAgeToGreterthenAgeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Value..
        /// </summary>
        public static string lblChildTermsValidValue {
            get {
                return ResourceManager.GetString("lblChildTermsValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value is less then 100..
        /// </summary>
        public static string lblChildTermsValueLessthan100 {
            get {
                return ResourceManager.GetString("lblChildTermsValueLessthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string lblClickHere {
            get {
                return ResourceManager.GetString("lblClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information does not exist in your language. Please contact the hotel for more information..
        /// </summary>
        public static string lblContentNotTranslated {
            get {
                return ResourceManager.GetString("lblContentNotTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Currency..
        /// </summary>
        public static string lblCurrencySelect {
            get {
                return ResourceManager.GetString("lblCurrencySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Language Name..
        /// </summary>
        public static string lblDepositPolicyValidateLanguageName {
            get {
                return ResourceManager.GetString("lblDepositPolicyValidateLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record with the same name already exists..
        /// </summary>
        public static string lblDuplicate {
            get {
                return ResourceManager.GetString("lblDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Language Name..
        /// </summary>
        public static string lblExtraServiceValidateLanguageName {
            get {
                return ResourceManager.GetString("lblExtraServiceValidateLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string lblFree {
            get {
                return ResourceManager.GetString("lblFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be greater than Start Date.
        /// </summary>
        public static string lblGroupCodeValidateDateTo {
            get {
                return ResourceManager.GetString("lblGroupCodeValidateDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be greater than Start Date.
        /// </summary>
        public static string lblGroupCodeValidateEndSell {
            get {
                return ResourceManager.GetString("lblGroupCodeValidateEndSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Guest Category..
        /// </summary>
        public static string lblGuestSelectCategory {
            get {
                return ResourceManager.GetString("lblGuestSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Country..
        /// </summary>
        public static string lblGuestSelectCountry {
            get {
                return ResourceManager.GetString("lblGuestSelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Currency..
        /// </summary>
        public static string lblGuestSelectCurrency {
            get {
                return ResourceManager.GetString("lblGuestSelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Language..
        /// </summary>
        public static string lblguestSelectLanguages {
            get {
                return ResourceManager.GetString("lblguestSelectLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid value..
        /// </summary>
        public static string lblInvoiceSettingDetailValidateValue {
            get {
                return ResourceManager.GetString("lblInvoiceSettingDetailValidateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than 100%..
        /// </summary>
        public static string lblInvoiceSettingDetailValueLessthan100 {
            get {
                return ResourceManager.GetString("lblInvoiceSettingDetailValueLessthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Property..
        /// </summary>
        public static string lblInvoiceSettingValidateProperty {
            get {
                return ResourceManager.GetString("lblInvoiceSettingValidateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence must be greater than zero!.
        /// </summary>
        public static string lblInvoiceSettingValidateRecurrence {
            get {
                return ResourceManager.GetString("lblInvoiceSettingValidateRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid VAT..
        /// </summary>
        public static string lblInvoiceSettingValidateVat {
            get {
                return ResourceManager.GetString("lblInvoiceSettingValidateVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT must be less than 100%!.
        /// </summary>
        public static string lblInvoiceSettingVatLassthan100 {
            get {
                return ResourceManager.GetString("lblInvoiceSettingVatLassthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Quantity..
        /// </summary>
        public static string lblInvoiceValidateQuantity {
            get {
                return ResourceManager.GetString("lblInvoiceValidateQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Value..
        /// </summary>
        public static string lblInvoiceValidateValue {
            get {
                return ResourceManager.GetString("lblInvoiceValidateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Language Name..
        /// </summary>
        public static string lblOtherPolicyValidateLanguageName {
            get {
                return ResourceManager.GetString("lblOtherPolicyValidateLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value Maximum Days must be less than Days..
        /// </summary>
        public static string lblPackageDays {
            get {
                return ResourceManager.GetString("lblPackageDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select Rate for extended Package..
        /// </summary>
        public static string lblPackageExtendedRate {
            get {
                return ResourceManager.GetString("lblPackageExtendedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select Max Days when Package is extentible..
        /// </summary>
        public static string lblPackageMaxDays {
            get {
                return ResourceManager.GetString("lblPackageMaxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Rate..
        /// </summary>
        public static string lblPackageRateValidate {
            get {
                return ResourceManager.GetString("lblPackageRateValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date must be greater than From Date.
        /// </summary>
        public static string lblPackageValidateStartEndDate {
            get {
                return ResourceManager.GetString("lblPackageValidateStartEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date can not be of past..
        /// </summary>
        public static string lblPackagServiceValidateDate {
            get {
                return ResourceManager.GetString("lblPackagServiceValidateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both dates Valid From and Valid To are required for making Promotional Code valid between those dates.
        /// </summary>
        public static string lblPromotionCodesValidateDateValidFrom {
            get {
                return ResourceManager.GetString("lblPromotionCodesValidateDateValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Property Category.
        /// </summary>
        public static string lblPropertyCategory {
            get {
                return ResourceManager.GetString("lblPropertyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Property Client.
        /// </summary>
        public static string lblPropertyValidateClient {
            get {
                return ResourceManager.GetString("lblPropertyValidateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password don&apos;t match..
        /// </summary>
        public static string lblPswdNotMatch {
            get {
                return ResourceManager.GetString("lblPswdNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Minimum Occupation value must be greater than zero!.
        /// </summary>
        public static string lblRateLevelOccupancyFromGreaterthanzero {
            get {
                return ResourceManager.GetString("lblRateLevelOccupancyFromGreaterthanzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Minimum Occupation must be less than 100%.
        /// </summary>
        public static string lblRateLevelOccupancyFromLessthan100 {
            get {
                return ResourceManager.GetString("lblRateLevelOccupancyFromLessthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value Maximum Occupancy must be greater than zero!.
        /// </summary>
        public static string lblRateLevelOccupancyToGreaterthanzero {
            get {
                return ResourceManager.GetString("lblRateLevelOccupancyToGreaterthanzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value Maximum Occupancy must be less than 100%!.
        /// </summary>
        public static string lblRateLevelOccupancyToLessthan100 {
            get {
                return ResourceManager.GetString("lblRateLevelOccupancyToLessthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero!.
        /// </summary>
        public static string lblRateLevelValueGreaterthanzero {
            get {
                return ResourceManager.GetString("lblRateLevelValueGreaterthanzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than 100%..
        /// </summary>
        public static string lblRateLevelValueLessthan100 {
            get {
                return ResourceManager.GetString("lblRateLevelValueLessthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Start Date!.
        /// </summary>
        public static string lblRatesIncentiveDateFrom {
            get {
                return ResourceManager.GetString("lblRatesIncentiveDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an End Date!.
        /// </summary>
        public static string lblRatesIncentiveDateTo {
            get {
                return ResourceManager.GetString("lblRatesIncentiveDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be greater than Start Date..
        /// </summary>
        public static string lblRateTiersDateRange {
            get {
                return ResourceManager.GetString("lblRateTiersDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Language Name..
        /// </summary>
        public static string lblRateValidateLangName {
            get {
                return ResourceManager.GetString("lblRateValidateLangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully..
        /// </summary>
        public static string lblRecordUpdated {
            get {
                return ResourceManager.GetString("lblRecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record update failed..
        /// </summary>
        public static string lblRecordUpdatedFailed {
            get {
                return ResourceManager.GetString("lblRecordUpdatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed for below entities because of the Reference : .
        /// </summary>
        public static string lblReplicatePropertyFail {
            get {
                return ResourceManager.GetString("lblReplicatePropertyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is Required..
        /// </summary>
        public static string lblRequired {
            get {
                return ResourceManager.GetString("lblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number length does not match to card type..
        /// </summary>
        public static string lblResCardNumberLength {
            get {
                return ResourceManager.GetString("lblResCardNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be greater than zero..
        /// </summary>
        public static string lblReservationChildAge {
            get {
                return ResourceManager.GetString("lblReservationChildAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select guest..
        /// </summary>
        public static string lblReservationGuest {
            get {
                return ResourceManager.GetString("lblReservationGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Quantity must be greater than zero!.
        /// </summary>
        public static string lblReservationRoomQuantityGreaterthanzero {
            get {
                return ResourceManager.GetString("lblReservationRoomQuantityGreaterthanzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Allotment must be greater than zero!.
        /// </summary>
        public static string lblRoomAllomentGreterthenzero {
            get {
                return ResourceManager.GetString("lblRoomAllomentGreterthenzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Price must be greater than zero!.
        /// </summary>
        public static string lblRoomPriceGreterthenzero {
            get {
                return ResourceManager.GetString("lblRoomPriceGreterthenzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Quantiy should be greater than or equal to zero..
        /// </summary>
        public static string lblRoomQuantiy {
            get {
                return ResourceManager.GetString("lblRoomQuantiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Language Name..
        /// </summary>
        public static string lblRoomTypeValidateLanguageName {
            get {
                return ResourceManager.GetString("lblRoomTypeValidateLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value Maximum Occupancy must be greater than Minimum Occupancy..
        /// </summary>
        public static string lblRoomTypeValidateMaxOccupancy {
            get {
                return ResourceManager.GetString("lblRoomTypeValidateMaxOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value Maximum must be greater than Minimum..
        /// </summary>
        public static string lblRoomTypeValidateMaxValue {
            get {
                return ResourceManager.GetString("lblRoomTypeValidateMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Value must be less than or equal to 100%..
        /// </summary>
        public static string lblRoomvalueLessthan100 {
            get {
                return ResourceManager.GetString("lblRoomvalueLessthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Sales Document Detail..
        /// </summary>
        public static string lblSalesDocDetailValidate {
            get {
                return ResourceManager.GetString("lblSalesDocDetailValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not succeed from Invoice Value..
        /// </summary>
        public static string lblSalesDocDetailValue {
            get {
                return ResourceManager.GetString("lblSalesDocDetailValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Property.
        /// </summary>
        public static string lblSalesDocPropertyValue {
            get {
                return ResourceManager.GetString("lblSalesDocPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Sales DocumentType..
        /// </summary>
        public static string lblSalesDocumentSeriesValidateDocumentType {
            get {
                return ResourceManager.GetString("lblSalesDocumentSeriesValidateDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be greater than Start Date.
        /// </summary>
        public static string lblSalesDocumentSeriesValidateStartEndDate {
            get {
                return ResourceManager.GetString("lblSalesDocumentSeriesValidateStartEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one day for Update..
        /// </summary>
        public static string lblSelectOneDay {
            get {
                return ResourceManager.GetString("lblSelectOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Status..
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Through and Minimum or Maximum of Stay cannot be set at the same time..
        /// </summary>
        public static string lblStayThroughMsg {
            get {
                return ResourceManager.GetString("lblStayThroughMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Property Template..
        /// </summary>
        public static string lblSurveyPropertyTemplate {
            get {
                return ResourceManager.GetString("lblSurveyPropertyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value.
        /// </summary>
        public static string lblSystemDefultEventValidateValue {
            get {
                return ResourceManager.GetString("lblSystemDefultEventValidateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Templates Category..
        /// </summary>
        public static string lblSystemTemplateValidateCategory {
            get {
                return ResourceManager.GetString("lblSystemTemplateValidateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Language Name..
        /// </summary>
        public static string lblTaxPolicyValidateLanguageName {
            get {
                return ResourceManager.GetString("lblTaxPolicyValidateLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Value..
        /// </summary>
        public static string lblTaxPolicyValidValue {
            get {
                return ResourceManager.GetString("lblTaxPolicyValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value is less then 100..
        /// </summary>
        public static string lblTaxPolicyValueLessthan100 {
            get {
                return ResourceManager.GetString("lblTaxPolicyValueLessthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string lblTimeZone {
            get {
                return ResourceManager.GetString("lblTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to Unsubscribe from this notification..
        /// </summary>
        public static string lblUnsubscribe {
            get {
                return ResourceManager.GetString("lblUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Expiry Date must be greater than current date..
        /// </summary>
        public static string lblUserPasswordExpirydate {
            get {
                return ResourceManager.GetString("lblUserPasswordExpirydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Numeric Value is allowed..
        /// </summary>
        public static string lblValidateAmount {
            get {
                return ResourceManager.GetString("lblValidateAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The End of Time Breakfast must be greater than Start..
        /// </summary>
        public static string lblValidateBreakFeastHours {
            get {
                return ResourceManager.GetString("lblValidateBreakFeastHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out must be greater than Check-In..
        /// </summary>
        public static string lblValidateCheckInHours {
            get {
                return ResourceManager.GetString("lblValidateCheckInHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be greater than Start Date..
        /// </summary>
        public static string lblValidateCloseDate {
            get {
                return ResourceManager.GetString("lblValidateCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount must be greater than zero..
        /// </summary>
        public static string lblValidateDiscountGreaterthanZero {
            get {
                return ResourceManager.GetString("lblValidateDiscountGreaterthanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount must be less than 100%..
        /// </summary>
        public static string lblValidateDiscountLessthan100 {
            get {
                return ResourceManager.GetString("lblValidateDiscountLessthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select..
        /// </summary>
        public static string lblValidateDropDown {
            get {
                return ResourceManager.GetString("lblValidateDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs to be a valid Email..
        /// </summary>
        public static string lblValidateEmail {
            get {
                return ResourceManager.GetString("lblValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required..
        /// </summary>
        public static string lblValidateEmailaddress {
            get {
                return ResourceManager.GetString("lblValidateEmailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than zero..
        /// </summary>
        public static string lblValidateExtraPrice {
            get {
                return ResourceManager.GetString("lblValidateExtraPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have to add Rate related to this Group Code..
        /// </summary>
        public static string lblValidateGroupCodeRate {
            get {
                return ResourceManager.GetString("lblValidateGroupCodeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Free Days must be less than or equal to number of days..
        /// </summary>
        public static string lblValidateIncentiveFreeDays {
            get {
                return ResourceManager.GetString("lblValidateIncentiveFreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for Latitude..
        /// </summary>
        public static string lblValidateLat {
            get {
                return ResourceManager.GetString("lblValidateLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for Longitude..
        /// </summary>
        public static string lblValidateLon {
            get {
                return ResourceManager.GetString("lblValidateLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is required.
        /// </summary>
        public static string lblValidateMessages {
            get {
                return ResourceManager.GetString("lblValidateMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password don&apos;t match..
        /// </summary>
        public static string lblValidateNewPasswordandConfirmPassword {
            get {
                return ResourceManager.GetString("lblValidateNewPasswordandConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string lblValidateOldPassword {
            get {
                return ResourceManager.GetString("lblValidateOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password don&apos;t match..
        /// </summary>
        public static string lblValidatePasswordandRepeatPassword {
            get {
                return ResourceManager.GetString("lblValidatePasswordandRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Year can not be greater than current year..
        /// </summary>
        public static string lblValidatePropertyBuildYear {
            get {
                return ResourceManager.GetString("lblValidatePropertyBuildYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Year Renewal must be less than or equal to the Current Year..
        /// </summary>
        public static string lblValidatePropertyRenYear {
            get {
                return ResourceManager.GetString("lblValidatePropertyRenYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value Maximum Days must be greater than Minimum Days..
        /// </summary>
        public static string lblValidateRateRestriction {
            get {
                return ResourceManager.GetString("lblValidateRateRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception Close Hours must be greater than Reception Open Hours..
        /// </summary>
        public static string lblValidateReceptionHours {
            get {
                return ResourceManager.GetString("lblValidateReceptionHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Room Type.
        /// </summary>
        public static string lblValidateRoomType {
            get {
                return ResourceManager.GetString("lblValidateRoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity value must be greater than zero..
        /// </summary>
        public static string lblValidateRoomTypeQty {
            get {
                return ResourceManager.GetString("lblValidateRoomTypeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is required.
        /// </summary>
        public static string lblValidateSubject {
            get {
                return ResourceManager.GetString("lblValidateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL field is required.
        /// </summary>
        public static string lblValidateURl {
            get {
                return ResourceManager.GetString("lblValidateURl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter User Name..
        /// </summary>
        public static string lblValidateUserName {
            get {
                return ResourceManager.GetString("lblValidateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter User Password.
        /// </summary>
        public static string lblValidateUserPassword {
            get {
                return ResourceManager.GetString("lblValidateUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value filed is required.
        /// </summary>
        public static string lblValidateValue {
            get {
                return ResourceManager.GetString("lblValidateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select VAT.
        /// </summary>
        public static string lblValidateVAT {
            get {
                return ResourceManager.GetString("lblValidateVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From field is required.
        /// </summary>
        public static string lblValidFrom {
            get {
                return ResourceManager.GetString("lblValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To field is required.
        /// </summary>
        public static string lblValidTo {
            get {
                return ResourceManager.GetString("lblValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not exceed Sales Document Value..
        /// </summary>
        public static string lblValueExceed {
            get {
                return ResourceManager.GetString("lblValueExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero..
        /// </summary>
        public static string lblValueGreaterZero {
            get {
                return ResourceManager.GetString("lblValueGreaterZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date can not be of past..
        /// </summary>
        public static string lblVatValidateDate {
            get {
                return ResourceManager.GetString("lblVatValidateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you can&apos;t view the email correctly..
        /// </summary>
        public static string lblViewCampaign {
            get {
                return ResourceManager.GetString("lblViewCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
    }
}
