//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OB.BL.Resources.MetadataErrorMessages", typeof(MetadataErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation Year.
        /// </summary>
        public static string blRenovationYear {
            get {
                return ResourceManager.GetString("blRenovationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Manager.
        /// </summary>
        public static string lblAccountManager {
            get {
                return ResourceManager.GetString("lblAccountManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length must be between 6 and 20 characters..
        /// </summary>
        public static string lblAccountManagerLenPassword {
            get {
                return ResourceManager.GetString("lblAccountManagerLenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be maximum 50 characters..
        /// </summary>
        public static string lblAccountManagerLenUserName {
            get {
                return ResourceManager.GetString("lblAccountManagerLenUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string lblAccountManagerReqPassword {
            get {
                return ResourceManager.GetString("lblAccountManagerReqPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string lblAccountManagerReqUserName {
            get {
                return ResourceManager.GetString("lblAccountManagerReqUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Username..
        /// </summary>
        public static string lblAccountManegerEmail {
            get {
                return ResourceManager.GetString("lblAccountManegerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string lblActivity {
            get {
                return ResourceManager.GetString("lblActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad..
        /// </summary>
        public static string lblAd {
            get {
                return ResourceManager.GetString("lblAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        public static string lblAddress1 {
            get {
                return ResourceManager.GetString("lblAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Adt..
        /// </summary>
        public static string lblAdultMaxOccupancy {
            get {
                return ResourceManager.GetString("lblAdultMaxOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Adt..
        /// </summary>
        public static string lblAdultMinOccupancy {
            get {
                return ResourceManager.GetString("lblAdultMinOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string lblAge {
            get {
                return ResourceManager.GetString("lblAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Reservation.
        /// </summary>
        public static string lblAllReservation {
            get {
                return ResourceManager.GetString("lblAllReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amenities.
        /// </summary>
        public static string lblAmenity {
            get {
                return ResourceManager.GetString("lblAmenity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amenity name must be maximum 50 characters..
        /// </summary>
        public static string lblAmenityLenName {
            get {
                return ResourceManager.GetString("lblAmenityLenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amenity name is required..
        /// </summary>
        public static string lblAmenityReqName {
            get {
                return ResourceManager.GetString("lblAmenityReqName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name must be maximum 50 characters..
        /// </summary>
        public static string lblAttractionCategoryLenName {
            get {
                return ResourceManager.GetString("lblAttractionCategoryLenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is required..
        /// </summary>
        public static string lblAttractionCategoryReqName {
            get {
                return ResourceManager.GetString("lblAttractionCategoryReqName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid URL..
        /// </summary>
        public static string lblAttractionValidURL {
            get {
                return ResourceManager.GetString("lblAttractionValidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        public static string lblAuthorized {
            get {
                return ResourceManager.GetString("lblAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Language.
        /// </summary>
        public static string lblBaseLanguage {
            get {
                return ResourceManager.GetString("lblBaseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Type.
        /// </summary>
        public static string lblBoardType {
            get {
                return ResourceManager.GetString("lblBoardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Engine.
        /// </summary>
        public static string lblBookingEngine {
            get {
                return ResourceManager.GetString("lblBookingEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounced Email.
        /// </summary>
        public static string lblBouncedEmail {
            get {
                return ResourceManager.GetString("lblBouncedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Year.
        /// </summary>
        public static string lblBuildYear {
            get {
                return ResourceManager.GetString("lblBuildYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Events.
        /// </summary>
        public static string lblCalendarEvents {
            get {
                return ResourceManager.GetString("lblCalendarEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Policies.
        /// </summary>
        public static string lblCancellationPolicy {
            get {
                return ResourceManager.GetString("lblCancellationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be maximum 100 characters..
        /// </summary>
        public static string lblCancellationPolicyLanDescription {
            get {
                return ResourceManager.GetString("lblCancellationPolicyLanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Holder&apos;s name.
        /// </summary>
        public static string lblCardHolderName {
            get {
                return ResourceManager.GetString("lblCardHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Number.
        /// </summary>
        public static string lblCCNumber {
            get {
                return ResourceManager.GetString("lblCCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch..
        /// </summary>
        public static string lblCh {
            get {
                return ResourceManager.GetString("lblCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string lblChannels {
            get {
                return ResourceManager.GetString("lblChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any Rate Model..
        /// </summary>
        public static string lblChannelsServicesReqRateModel {
            get {
                return ResourceManager.GetString("lblChannelsServicesReqRateModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Comments.
        /// </summary>
        public static string lblClientComments {
            get {
                return ResourceManager.GetString("lblClientComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address1..
        /// </summary>
        public static string lblClientReqAdd1 {
            get {
                return ResourceManager.GetString("lblClientReqAdd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Company Name..
        /// </summary>
        public static string lblClientReqCompanyName {
            get {
                return ResourceManager.GetString("lblClientReqCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Client Name..
        /// </summary>
        public static string lblClientReqName {
            get {
                return ResourceManager.GetString("lblClientReqName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string lblCode {
            get {
                return ResourceManager.GetString("lblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string lblComments {
            get {
                return ResourceManager.GetString("lblComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string lblCondition {
            get {
                return ResourceManager.GetString("lblCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Category.
        /// </summary>
        public static string lblCorporateCategory {
            get {
                return ResourceManager.GetString("lblCorporateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string lblCreatedBy {
            get {
                return ResourceManager.GetString("lblCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string lblCreatedDate {
            get {
                return ResourceManager.GetString("lblCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string lblCurrency {
            get {
                return ResourceManager.GetString("lblCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        public static string lblCVV {
            get {
                return ResourceManager.GetString("lblCVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string lblDateFrom {
            get {
                return ResourceManager.GetString("lblDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string lblDateTo {
            get {
                return ResourceManager.GetString("lblDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string lblDays {
            get {
                return ResourceManager.GetString("lblDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be maximum 100 characters..
        /// </summary>
        public static string lblDepositePolicyLanName {
            get {
                return ResourceManager.GetString("lblDepositePolicyLanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Policies.
        /// </summary>
        public static string lblDepositPolicy {
            get {
                return ResourceManager.GetString("lblDepositPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string lblDiscount {
            get {
                return ResourceManager.GetString("lblDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string lblEndDate {
            get {
                return ResourceManager.GetString("lblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Sale.
        /// </summary>
        public static string lblEndSale {
            get {
                return ResourceManager.GetString("lblEndSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Sell.
        /// </summary>
        public static string lblEndSell {
            get {
                return ResourceManager.GetString("lblEndSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string lblExtra {
            get {
                return ResourceManager.GetString("lblExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Days.
        /// </summary>
        public static string lblFreeDays {
            get {
                return ResourceManager.GetString("lblFreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From  Date.
        /// </summary>
        public static string lblFromDate {
            get {
                return ResourceManager.GetString("lblFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS N.
        /// </summary>
        public static string lblGeoLocationLat {
            get {
                return ResourceManager.GetString("lblGeoLocationLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS W.
        /// </summary>
        public static string lblGeoLocationLng {
            get {
                return ResourceManager.GetString("lblGeoLocationLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Code.
        /// </summary>
        public static string lblGroupCode {
            get {
                return ResourceManager.GetString("lblGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Code is Required.
        /// </summary>
        public static string lblGroupCodeRequired {
            get {
                return ResourceManager.GetString("lblGroupCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name must be maximum 50 characters..
        /// </summary>
        public static string lblGuestLanFirestName {
            get {
                return ResourceManager.GetString("lblGuestLanFirestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name must be maximum 50 characters..
        /// </summary>
        public static string lblGuestLenLastName {
            get {
                return ResourceManager.GetString("lblGuestLenLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string lblGuestReqFirestName {
            get {
                return ResourceManager.GetString("lblGuestReqFirestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperLink.
        /// </summary>
        public static string lblHyperLink {
            get {
                return ResourceManager.GetString("lblHyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IATA.
        /// </summary>
        public static string lblIATA {
            get {
                return ResourceManager.GetString("lblIATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select incentive type..
        /// </summary>
        public static string lblIncentiveReqIncentiveType {
            get {
                return ResourceManager.GetString("lblIncentiveReqIncentiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interest rates.
        /// </summary>
        public static string lblInterestRates {
            get {
                return ResourceManager.GetString("lblInterestRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid: Credit Card info not found.
        /// </summary>
        public static string lblInvalid_CreditCardInfoNotFound {
            get {
                return ResourceManager.GetString("lblInvalid_CreditCardInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Credit Card info failed.
        /// </summary>
        public static string lblInvalid_GettingCardInfoFailed {
            get {
                return ResourceManager.GetString("lblInvalid_GettingCardInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to see credit card on booking print.
        /// </summary>
        public static string lblInvalid_NotAllowedToPrint {
            get {
                return ResourceManager.GetString("lblInvalid_NotAllowedToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid: Does not have reservation access.
        /// </summary>
        public static string lblInvalid_ReservationAccessDenied {
            get {
                return ResourceManager.GetString("lblInvalid_ReservationAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid: Reservation does not exists.
        /// </summary>
        public static string lblInvalid_ReservationNotFound {
            get {
                return ResourceManager.GetString("lblInvalid_ReservationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid: User not found.
        /// </summary>
        public static string lblInvalid_UserNotFound {
            get {
                return ResourceManager.GetString("lblInvalid_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number days Invalid..
        /// </summary>
        public static string lblInvalidDays {
            get {
                return ResourceManager.GetString("lblInvalidDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string lblIsActive {
            get {
                return ResourceManager.GetString("lblIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Percentage.
        /// </summary>
        public static string lblIsPercentage {
            get {
                return ResourceManager.GetString("lblIsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language name must be maximum 50 characters..
        /// </summary>
        public static string lblLanguagesLanName {
            get {
                return ResourceManager.GetString("lblLanguagesLanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language name is required..
        /// </summary>
        public static string lblLanguagesReqName {
            get {
                return ResourceManager.GetString("lblLanguagesReqName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Age.
        /// </summary>
        public static string lblMaxAge {
            get {
                return ResourceManager.GetString("lblMaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Days.
        /// </summary>
        public static string lblMaximumDays {
            get {
                return ResourceManager.GetString("lblMaximumDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be maximum 250 characters..
        /// </summary>
        public static string lblMaxLengthDescription {
            get {
                return ResourceManager.GetString("lblMaxLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be maximum 50 characters..
        /// </summary>
        public static string lblMaxLengthName {
            get {
                return ResourceManager.GetString("lblMaxLengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID must be maximum 50 characters..
        /// </summary>
        public static string lblMaxLengthUserId {
            get {
                return ResourceManager.GetString("lblMaxLengthUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password must be maximum 50 characters..
        /// </summary>
        public static string lblMaxLengthUserPassword {
            get {
                return ResourceManager.GetString("lblMaxLengthUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Number Of Days.
        /// </summary>
        public static string lblMaxNumberOfDays {
            get {
                return ResourceManager.GetString("lblMaxNumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Value.
        /// </summary>
        public static string lblMaxValue {
            get {
                return ResourceManager.GetString("lblMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Media.
        /// </summary>
        public static string lblMultiMedia {
            get {
                return ResourceManager.GetString("lblMultiMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Email.
        /// </summary>
        public static string lblNotificationEmail {
            get {
                return ResourceManager.GetString("lblNotificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. Of Rooms.
        /// </summary>
        public static string lblNrOfRooms {
            get {
                return ResourceManager.GetString("lblNrOfRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Hotels.
        /// </summary>
        public static string lblNumberOfHotels {
            get {
                return ResourceManager.GetString("lblNumberOfHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers are not allowed..
        /// </summary>
        public static string lblNumbersNotAllowed {
            get {
                return ResourceManager.GetString("lblNumbersNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupancy From.
        /// </summary>
        public static string lblOccupancyFrom {
            get {
                return ResourceManager.GetString("lblOccupancyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupancy To.
        /// </summary>
        public static string lblOccupancyTo {
            get {
                return ResourceManager.GetString("lblOccupancyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Policies.
        /// </summary>
        public static string lblOtherPolicy {
            get {
                return ResourceManager.GetString("lblOtherPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateFrom is required..
        /// </summary>
        public static string lblPackagesReqDateFrom {
            get {
                return ResourceManager.GetString("lblPackagesReqDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTo is required..
        /// </summary>
        public static string lblPackagesReqDateTo {
            get {
                return ResourceManager.GetString("lblPackagesReqDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcel.
        /// </summary>
        public static string lblParcel {
            get {
                return ResourceManager.GetString("lblParcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Payment.
        /// </summary>
        public static string lblPartialPayment {
            get {
                return ResourceManager.GetString("lblPartialPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Expiry.
        /// </summary>
        public static string lblPasswordExpiry {
            get {
                return ResourceManager.GetString("lblPasswordExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string lblPaymentMethod {
            get {
                return ResourceManager.GetString("lblPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage is required..
        /// </summary>
        public static string lblPercentageRequired {
            get {
                return ResourceManager.GetString("lblPercentageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string lblPostalCode {
            get {
                return ResourceManager.GetString("lblPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Invoicing Email..
        /// </summary>
        public static string lblPropertiesValidInvoiceEmail {
            get {
                return ResourceManager.GetString("lblPropertiesValidInvoiceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Reservation Email..
        /// </summary>
        public static string lblPropertiesValidResevationEmail {
            get {
                return ResourceManager.GetString("lblPropertiesValidResevationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string lblProperty {
            get {
                return ResourceManager.GetString("lblProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Category.
        /// </summary>
        public static string lblPropertyCategory {
            get {
                return ResourceManager.GetString("lblPropertyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string lblQuestion {
            get {
                return ResourceManager.GetString("lblQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates.
        /// </summary>
        public static string lblRate {
            get {
                return ResourceManager.GetString("lblRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string lblRateName {
            get {
                return ResourceManager.GetString("lblRateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence.
        /// </summary>
        public static string lblRecurrence {
            get {
                return ResourceManager.GetString("lblRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay Email.
        /// </summary>
        public static string lblReplayEmail {
            get {
                return ResourceManager.GetString("lblReplayEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Country..
        /// </summary>
        public static string lblReqCountry {
            get {
                return ResourceManager.GetString("lblReqCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is required..
        /// </summary>
        public static string lblReqCurrency {
            get {
                return ResourceManager.GetString("lblReqCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Adress is required..
        /// </summary>
        public static string lblReqEmail {
            get {
                return ResourceManager.GetString("lblReqEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter tag!.
        /// </summary>
        public static string lblRequierdTag {
            get {
                return ResourceManager.GetString("lblRequierdTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is required!.
        /// </summary>
        public static string lblRequierdUserId {
            get {
                return ResourceManager.GetString("lblRequierdUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password is required!.
        /// </summary>
        public static string lblRequierdUserPassword {
            get {
                return ResourceManager.GetString("lblRequierdUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string lblRequired {
            get {
                return ResourceManager.GetString("lblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From is Required..
        /// </summary>
        public static string lblRequiredDateFrom {
            get {
                return ResourceManager.GetString("lblRequiredDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To is Required..
        /// </summary>
        public static string lblRequiredDateTo {
            get {
                return ResourceManager.GetString("lblRequiredDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string lblRequiredDescription {
            get {
                return ResourceManager.GetString("lblRequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is required..
        /// </summary>
        public static string lblRequiredEnddate {
            get {
                return ResourceManager.GetString("lblRequiredEnddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Image..
        /// </summary>
        public static string lblRequiredImage {
            get {
                return ResourceManager.GetString("lblRequiredImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string lblRequiredName {
            get {
                return ResourceManager.GetString("lblRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select property..
        /// </summary>
        public static string lblRequiredProperty {
            get {
                return ResourceManager.GetString("lblRequiredProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select rate tier..
        /// </summary>
        public static string lblRequiredRateTier {
            get {
                return ResourceManager.GetString("lblRequiredRateTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is required..
        /// </summary>
        public static string lblRequiredStartdate {
            get {
                return ResourceManager.GetString("lblRequiredStartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required..
        /// </summary>
        public static string lblRequiredValue {
            get {
                return ResourceManager.GetString("lblRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Quantity.
        /// </summary>
        public static string lblRoomQuantity {
            get {
                return ResourceManager.GetString("lblRoomQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Types.
        /// </summary>
        public static string lblRoomType {
            get {
                return ResourceManager.GetString("lblRoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type.
        /// </summary>
        public static string lblRoomTypeName {
            get {
                return ResourceManager.GetString("lblRoomTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Through.
        /// </summary>
        public static string lblStayThrough {
            get {
                return ResourceManager.GetString("lblStayThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string lblSubject {
            get {
                return ResourceManager.GetString("lblSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string lblTag {
            get {
                return ResourceManager.GetString("lblTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Policies.
        /// </summary>
        public static string lblTaxPolicy {
            get {
                return ResourceManager.GetString("lblTaxPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string lblToDate {
            get {
                return ResourceManager.GetString("lblToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Occupancy.
        /// </summary>
        public static string lblTotalOccupancy {
            get {
                return ResourceManager.GetString("lblTotalOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rooms.
        /// </summary>
        public static string lblTotalRooms {
            get {
                return ResourceManager.GetString("lblTotalRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPI category description must be maximum 250 characters..
        /// </summary>
        public static string lblTPICategoryLanDescription {
            get {
                return ResourceManager.GetString("lblTPICategoryLanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPI category name must be maximum 50 characters..
        /// </summary>
        public static string lblTPICategoryLanName {
            get {
                return ResourceManager.GetString("lblTPICategoryLanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPI category name is required..
        /// </summary>
        public static string lblTPICategoryReqName {
            get {
                return ResourceManager.GetString("lblTPICategoryReqName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1 must be maximum 250 characters..
        /// </summary>
        public static string lblTplLanAdd1 {
            get {
                return ResourceManager.GetString("lblTplLanAdd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City must be maximum 50 characters..
        /// </summary>
        public static string lblTplLanCity {
            get {
                return ResourceManager.GetString("lblTplLanCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IATA must be maximum 50 characters..
        /// </summary>
        public static string lblTplLanIATA {
            get {
                return ResourceManager.GetString("lblTplLanIATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone must be maximum 50 characters..
        /// </summary>
        public static string lblTplLanPhone {
            get {
                return ResourceManager.GetString("lblTplLanPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code must be maximum 50 characters..
        /// </summary>
        public static string lblTplLanPostalcode {
            get {
                return ResourceManager.GetString("lblTplLanPostalcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1 is required..
        /// </summary>
        public static string lblTplReqAdd1 {
            get {
                return ResourceManager.GetString("lblTplReqAdd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required..
        /// </summary>
        public static string lblTplReqCity {
            get {
                return ResourceManager.GetString("lblTplReqCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required..
        /// </summary>
        public static string lblTplReqPhone {
            get {
                return ResourceManager.GetString("lblTplReqPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code is required..
        /// </summary>
        public static string lblTplReqPostalcode {
            get {
                return ResourceManager.GetString("lblTplReqPostalcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username(abc@gmail.com).
        /// </summary>
        public static string lblTplValidateUserName {
            get {
                return ResourceManager.GetString("lblTplValidateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string lblURL {
            get {
                return ResourceManager.GetString("lblURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   USD.
        /// </summary>
        public static string lblUSD {
            get {
                return ResourceManager.GetString("lblUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string lblUserID {
            get {
                return ResourceManager.GetString("lblUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password.
        /// </summary>
        public static string lblUserPassword {
            get {
                return ResourceManager.GetString("lblUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Security Code(CVV)..
        /// </summary>
        public static string lblValidateCVV {
            get {
                return ResourceManager.GetString("lblValidateCVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Email Address..
        /// </summary>
        public static string lblValidateEmail {
            get {
                return ResourceManager.GetString("lblValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        public static string lblValidFrom {
            get {
                return ResourceManager.GetString("lblValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone..
        /// </summary>
        public static string lblValidPhone {
            get {
                return ResourceManager.GetString("lblValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone ext..
        /// </summary>
        public static string lblValidPhoneExt {
            get {
                return ResourceManager.GetString("lblValidPhoneExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string lblValue {
            get {
                return ResourceManager.GetString("lblValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string lblVAT {
            get {
                return ResourceManager.GetString("lblVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number.
        /// </summary>
        public static string lblVATNumber {
            get {
                return ResourceManager.GetString("lblVATNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string lblWebsite {
            get {
                return ResourceManager.GetString("lblWebsite", resourceCulture);
            }
        }
    }
}
