//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OB.BL.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at the beginning.
        /// </summary>
        public static string atthebeginning {
            get {
                return ResourceManager.GetString("atthebeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at the end.
        /// </summary>
        public static string attheend {
            get {
                return ResourceManager.GetString("attheend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Cancelled.
        /// </summary>
        public static string BookingCanceledEmailSubjectEmail {
            get {
                return ResourceManager.GetString("BookingCanceledEmailSubjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Reservation.
        /// </summary>
        public static string CancelationText {
            get {
                return ResourceManager.GetString("CancelationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ChannelMappingTypeAll {
            get {
                return ResourceManager.GetString("ChannelMappingTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations Only.
        /// </summary>
        public static string ChannelMappingTypeReservationsOnly {
            get {
                return ResourceManager.GetString("ChannelMappingTypeReservationsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} reached the credit limit of {1}.
        /// </summary>
        public static string CreditLimitMsg {
            get {
                return ResourceManager.GetString("CreditLimitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Night.
        /// </summary>
        public static string FreeNight {
            get {
                return ResourceManager.GetString("FreeNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad..
        /// </summary>
        public static string lblAd {
            get {
                return ResourceManager.GetString("lblAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string lblAdded {
            get {
                return ResourceManager.GetString("lblAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allot.
        /// </summary>
        public static string lblAllot {
            get {
                return ResourceManager.GetString("lblAllot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Stay.
        /// </summary>
        public static string lblAllStay {
            get {
                return ResourceManager.GetString("lblAllStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price/Availability.
        /// </summary>
        public static string lblARQ {
            get {
                return ResourceManager.GetString("lblARQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string lblAt {
            get {
                return ResourceManager.GetString("lblAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Dates.
        /// </summary>
        public static string lblAvailableDates {
            get {
                return ResourceManager.GetString("lblAvailableDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounced email.
        /// </summary>
        public static string lblBouncedEmail {
            get {
                return ResourceManager.GetString("lblBouncedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        public static string lblBRQ {
            get {
                return ResourceManager.GetString("lblBRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string lblCancelled {
            get {
                return ResourceManager.GetString("lblCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch..
        /// </summary>
        public static string lblCh {
            get {
                return ResourceManager.GetString("lblCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in.
        /// </summary>
        public static string lblCheckIn {
            get {
                return ResourceManager.GetString("lblCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out.
        /// </summary>
        public static string lblCheckOut {
            get {
                return ResourceManager.GetString("lblCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Sales.
        /// </summary>
        public static string lblCloseSales {
            get {
                return ResourceManager.GetString("lblCloseSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string lblCopy {
            get {
                return ResourceManager.GetString("lblCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reached the credit limit of {1}.
        /// </summary>
        public static string lblCreditLimitReached {
            get {
                return ResourceManager.GetString("lblCreditLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string lblExtra {
            get {
                return ResourceManager.GetString("lblExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Dates.
        /// </summary>
        public static string lblExtraSchedule {
            get {
                return ResourceManager.GetString("lblExtraSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From email.
        /// </summary>
        public static string lblFromEmail {
            get {
                return ResourceManager.GetString("lblFromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From name.
        /// </summary>
        public static string lblFromName {
            get {
                return ResourceManager.GetString("lblFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates.
        /// </summary>
        public static string lblGRRQ {
            get {
                return ResourceManager.GetString("lblGRRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included.
        /// </summary>
        public static string lblIncluded {
            get {
                return ResourceManager.GetString("lblIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interest rates.
        /// </summary>
        public static string lblInterestRate {
            get {
                return ResourceManager.GetString("lblInterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string lblMobile {
            get {
                return ResourceManager.GetString("lblMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string lblModified {
            get {
                return ResourceManager.GetString("lblModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string lblMove {
            get {
                return ResourceManager.GetString("lblMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr./Mrs..
        /// </summary>
        public static string lblMrMrs {
            get {
                return ResourceManager.GetString("lblMrMrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string lblNotes {
            get {
                return ResourceManager.GetString("lblNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sales.
        /// </summary>
        public static string lblOpenSales {
            get {
                return ResourceManager.GetString("lblOpenSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string lblOperator {
            get {
                return ResourceManager.GetString("lblOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string lblPackages {
            get {
                return ResourceManager.GetString("lblPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial payment.
        /// </summary>
        public static string lblPartialPayment {
            get {
                return ResourceManager.GetString("lblPartialPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type.
        /// </summary>
        public static string lblPaymentType {
            get {
                return ResourceManager.GetString("lblPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Assignment.
        /// </summary>
        public static string lblPropertyAssignment {
            get {
                return ResourceManager.GetString("lblPropertyAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Property.
        /// </summary>
        public static string lblPRQ {
            get {
                return ResourceManager.GetString("lblPRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string lblPublic {
            get {
                return ResourceManager.GetString("lblPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price/Availability.
        /// </summary>
        public static string lblRARQ {
            get {
                return ResourceManager.GetString("lblRARQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min {0} night(s).
        /// </summary>
        public static string lblRateRestriction1 {
            get {
                return ResourceManager.GetString("lblRateRestriction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay {0} day(s).
        /// </summary>
        public static string lblRateRestriction2 {
            get {
                return ResourceManager.GetString("lblRateRestriction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed on arrival.
        /// </summary>
        public static string lblRateRestriction3 {
            get {
                return ResourceManager.GetString("lblRateRestriction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed on departure.
        /// </summary>
        public static string lblRateRestriction4 {
            get {
                return ResourceManager.GetString("lblRateRestriction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Release Days.
        /// </summary>
        public static string lblRateRestriction5 {
            get {
                return ResourceManager.GetString("lblRateRestriction5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        public static string lblRateRestriction6 {
            get {
                return ResourceManager.GetString("lblRateRestriction6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string lblRateRestriction7 {
            get {
                return ResourceManager.GetString("lblRateRestriction7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max {0} day(s).
        /// </summary>
        public static string lblRateRestriction8 {
            get {
                return ResourceManager.GetString("lblRateRestriction8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates.
        /// </summary>
        public static string lblRates {
            get {
                return ResourceManager.GetString("lblRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Rooms.
        /// </summary>
        public static string lblRDRQ {
            get {
                return ResourceManager.GetString("lblRDRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string lblRemoved {
            get {
                return ResourceManager.GetString("lblRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply email.
        /// </summary>
        public static string lblReplyEmail {
            get {
                return ResourceManager.GetString("lblReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        public static string lblRestrictionAllocation {
            get {
                return ResourceManager.GetString("lblRestrictionAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string lblRestrictionBlocked {
            get {
                return ResourceManager.GetString("lblRestrictionBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also called Stop Sales. Even with available rooms to sell, the rate could have stop sales for a determined date, allowing other more attractive (and more pricey) rates to take reservations, thus augmenting revenue..
        /// </summary>
        public static string lblRestrictionBlockedDesc {
            get {
                return ResourceManager.GetString("lblRestrictionBlockedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed on arrival.
        /// </summary>
        public static string lblRestrictionClosedOnArrival {
            get {
                return ResourceManager.GetString("lblRestrictionClosedOnArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This restriction means that the booking engine should not allow for bookings to start on days with this restriction. The reservation should start one or more days earlier or later..
        /// </summary>
        public static string lblRestrictionClosedOnArrivalDesc {
            get {
                return ResourceManager.GetString("lblRestrictionClosedOnArrivalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed on departure.
        /// </summary>
        public static string lblRestrictionClosedOnDeparture {
            get {
                return ResourceManager.GetString("lblRestrictionClosedOnDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as Closed on Arrival, but for ending reservation date.Guests should not set as end date a day with this restriction, instead should end a day earlier or later (if doesn’t have this restriction too)..
        /// </summary>
        public static string lblRestrictionClosedOnDepartureDesc {
            get {
                return ResourceManager.GetString("lblRestrictionClosedOnDepartureDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Length of Stay.
        /// </summary>
        public static string lblRestrictionMaxDays {
            get {
                return ResourceManager.GetString("lblRestrictionMaxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of nights a guest must stay at the hotel. If rate MaxLOS is 3 then the Booking Engine should not allow reservations for more than 3 nights..
        /// </summary>
        public static string lblRestrictionMaxDaysDesc {
            get {
                return ResourceManager.GetString("lblRestrictionMaxDaysDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Length of Stay.
        /// </summary>
        public static string lblRestrictionMinDays {
            get {
                return ResourceManager.GetString("lblRestrictionMinDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum number of nights a guest must stay at the hotel. If rate MinLOS is 3 then the Booking Engine should not allow reservations for 1 or 2 nights..
        /// </summary>
        public static string lblRestrictionMinDaysDesc {
            get {
                return ResourceManager.GetString("lblRestrictionMinDaysDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release days.
        /// </summary>
        public static string lblRestrictionReleaseDays {
            get {
                return ResourceManager.GetString("lblRestrictionReleaseDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also called cut-off days. Means the rate must only be booked with n days in advance. After the release days are passed, the rate is not bookable. So for a Release Days of 30, means the rate should be booked a month (30 days) before starting, so for a rate that starts on 1st August, the reservations should be possible only up to 1st July..
        /// </summary>
        public static string lblRestrictionReleaseDaysDesc {
            get {
                return ResourceManager.GetString("lblRestrictionReleaseDaysDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay through.
        /// </summary>
        public static string lblRestrictionStayThrough {
            get {
                return ResourceManager.GetString("lblRestrictionStayThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Means the guest has to stay through the defined days to be able to book the rate. For example if stay through is from 3 August to 5 August, the Booking Engine should allow reservations from day 2 and before, and that end on day 6 or after. So, a reservation on the 3rd to the 7th August will not be accepted. A reservation from 1st August to 7th will be accepted..
        /// </summary>
        public static string lblRestrictionStayThroughDesc {
            get {
                return ResourceManager.GetString("lblRestrictionStayThroughDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string lblRoom {
            get {
                return ResourceManager.GetString("lblRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Rates.
        /// </summary>
        public static string lblRRQ {
            get {
                return ResourceManager.GetString("lblRRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms/Rates.
        /// </summary>
        public static string lblRTRQ {
            get {
                return ResourceManager.GetString("lblRTRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale closed.
        /// </summary>
        public static string lblSaleClosed {
            get {
                return ResourceManager.GetString("lblSaleClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Agent.
        /// </summary>
        public static string lblTravelAgent {
            get {
                return ResourceManager.GetString("lblTravelAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string lblUnspecified {
            get {
                return ResourceManager.GetString("lblUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your booking was cancelled..
        /// </summary>
        public static string msgCanceledBookingIntroductoryText {
            get {
                return ResourceManager.GetString("msgCanceledBookingIntroductoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your booking was changed. Please check the details..
        /// </summary>
        public static string msgChangedBookingIntroductoryText {
            get {
                return ResourceManager.GetString("msgChangedBookingIntroductoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Changed.
        /// </summary>
        public static string msgChangedBookingSubject {
            get {
                return ResourceManager.GetString("msgChangedBookingSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;TOTAL ({0})&lt;br/&gt;The payment for this reservation will be in {0}.&lt;/strong&gt;&lt;br/&gt;(The prices displayed in {1} are indicative and based on today&apos;s exchange rate).
        /// </summary>
        public static string msgDifferentCurrencies {
            get {
                return ResourceManager.GetString("msgDifferentCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to included.
        /// </summary>
        public static string msgIncluded {
            get {
                return ResourceManager.GetString("msgIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: this information does not exists in this language! Please contact the hotel..
        /// </summary>
        public static string msgInfoNotAvailable {
            get {
                return ResourceManager.GetString("msgInfoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for choosing our hotel!.
        /// </summary>
        public static string msgNewBookingGuestIntroductoryText {
            get {
                return ResourceManager.GetString("msgNewBookingGuestIntroductoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Booking.
        /// </summary>
        public static string msgNewBookingGuestSubject {
            get {
                return ResourceManager.GetString("msgNewBookingGuestSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for request a reservation! We will answer as soon as possible..
        /// </summary>
        public static string msgNewRequestGuestIntroductoryText {
            get {
                return ResourceManager.GetString("msgNewRequestGuestIntroductoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string msgNewRequestGuestSubject {
            get {
                return ResourceManager.GetString("msgNewRequestGuestSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Canceled.
        /// </summary>
        public static string msgRequestCanceledEmailSubject {
            get {
                return ResourceManager.GetString("msgRequestCanceledEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request was canceled..
        /// </summary>
        public static string msgRequestCanceledIntroductoryText {
            get {
                return ResourceManager.GetString("msgRequestCanceledIntroductoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Refused.
        /// </summary>
        public static string msgRequestRefusedEmailSubject {
            get {
                return ResourceManager.GetString("msgRequestRefusedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but we could not meet your request. Our sincere apologies and contact us if you need any informations..
        /// </summary>
        public static string msgRequestRefusedIntroductoryText {
            get {
                return ResourceManager.GetString("msgRequestRefusedIntroductoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your Client Area.
        /// </summary>
        public static string NewGuestDetailMailSubject {
            get {
                return ResourceManager.GetString("NewGuestDetailMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Rules.
        /// </summary>
        public static string OccAllRulesApplied {
            get {
                return ResourceManager.GetString("OccAllRulesApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close sales.
        /// </summary>
        public static string OccCloseSales {
            get {
                return ResourceManager.GetString("OccCloseSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation.
        /// </summary>
        public static string OccCorrelation {
            get {
                return ResourceManager.GetString("OccCorrelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error applying rules..
        /// </summary>
        public static string OccError {
            get {
                return ResourceManager.GetString("OccError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string OccException {
            get {
                return ResourceManager.GetString("OccException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupancy.
        /// </summary>
        public static string OccLevel {
            get {
                return ResourceManager.GetString("OccLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string OccReservationNumber {
            get {
                return ResourceManager.GetString("OccReservationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string OccRoom {
            get {
                return ResourceManager.GetString("OccRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update rates.
        /// </summary>
        public static string OccUpdateRates {
            get {
                return ResourceManager.GetString("OccUpdateRates", resourceCulture);
            }
        }
    }
}
