using System.Collections.Generic;
using System.Linq;
using OB.Api.Core;
using OB.DL.Common.Impl;
using OB.Domain.Payments;
using OB.DL.Common.Repositories.Interfaces.Entity;
using OB.DL.Common.Criteria;

namespace OB.DL.Common.Repositories.Impl.Entity
{
    internal class PaymentGatewayTransactionRepository : Repository<PaymentGatewayTransaction>, IPaymentGatewayTransactionRepository
    {
        public PaymentGatewayTransactionRepository(IObjectContext context)
            : base(context)
        {
        }

        public IEnumerable<PaymentGatewayTransaction> FindByCriteria(ListPaymentGatewayTransactionsCriteria criteria)
        {
            var result = GetQuery();

            if (criteria.Ids != null && criteria.Ids.Count > 0)
                result = result.Where(x => criteria.Ids.Contains(x.UID));

            if (criteria.PaymentGatewayNames != null && criteria.PaymentGatewayNames.Count > 0)
                result = result.Where(x => criteria.PaymentGatewayNames.Contains(x.PaymentGatewayName));

            if (criteria.PropertyIds != null && criteria.PropertyIds.Count > 0)
                result = result.Where(x => criteria.PropertyIds.Contains(x.Property));

            if (criteria.PaymentGatewayOrderIds != null && criteria.PaymentGatewayOrderIds.Count > 0)
                result = result.Where(x => criteria.PaymentGatewayOrderIds.Contains(x.PaymentGatewayOrderID));

            if (criteria.PaymentGatewayAutoGeneratedIds != null && criteria.PaymentGatewayAutoGeneratedIds.Count > 0)
                result = result.Where(x => criteria.PaymentGatewayAutoGeneratedIds.Contains(x.PaymentGatewayAutoGeneratedUID));

            if (criteria.TransactionIds != null && criteria.TransactionIds.Count > 0)
                result = result.Where(x => criteria.TransactionIds.Contains(x.TransactionID));

            if (criteria.TransactionCodes != null && criteria.TransactionCodes.Count > 0)
                result = result.Where(x => criteria.TransactionCodes.Contains(x.TransactionCode));

            if (criteria.TransactionStatus != null && criteria.TransactionStatus.Count > 0)
                result = result.Where(x => criteria.TransactionStatus.Contains(x.TransactionStatus));

            if (criteria.TransactionTypes != null && criteria.TransactionTypes.Count > 0)
                result = result.Where(x => criteria.TransactionTypes.Contains(x.TransactionType));

            if (criteria.RefundTransactionIds != null && criteria.RefundTransactionIds.Count > 0)
                result = result.Where(x => criteria.RefundTransactionIds.Contains(x.RefundTransactionID));

            if (criteria.PaypalProfileIds != null && criteria.PaypalProfileIds.Count > 0)
                result = result.Where(x => criteria.PaypalProfileIds.Contains(x.PaypalProfileID));

            if (criteria.TransactionRequests != null && criteria.TransactionRequests.Count > 0)
                result = result.Where(x => criteria.TransactionRequests.Contains(x.TransactionRequest));

            return result;
        }

    }
}
