//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OB.BL.Operations.HtmlTemplateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HtmlTemplateService.HtmlTemplateServiceSoap")]
    public interface HtmlTemplateServiceSoap {
        
        // CODEGEN: Generating message contract since element name culture from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHtmlTemplateByCode", ReplyAction="*")]
        OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeResponse GetHtmlTemplateByCode(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHtmlTemplateByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeResponse> GetHtmlTemplateByCodeAsync(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name culture from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHtmlTemplateByCodeWithArgs", ReplyAction="*")]
        OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsResponse GetHtmlTemplateByCodeWithArgs(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHtmlTemplateByCodeWithArgs", ReplyAction="*")]
        System.Threading.Tasks.Task<OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsResponse> GetHtmlTemplateByCodeWithArgsAsync(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequest request);
        
        // CODEGEN: Generating message contract since element name templateName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHtml", ReplyAction="*")]
        OB.BL.Operations.HtmlTemplateService.GetHtmlResponse GetHtml(OB.BL.Operations.HtmlTemplateService.GetHtmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHtml", ReplyAction="*")]
        System.Threading.Tasks.Task<OB.BL.Operations.HtmlTemplateService.GetHtmlResponse> GetHtmlAsync(OB.BL.Operations.HtmlTemplateService.GetHtmlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHtmlTemplateByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHtmlTemplateByCode", Namespace="http://tempuri.org/", Order=0)]
        public OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequestBody Body;
        
        public GetHtmlTemplateByCodeRequest() {
        }
        
        public GetHtmlTemplateByCodeRequest(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHtmlTemplateByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int templatecode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string culture;
        
        public GetHtmlTemplateByCodeRequestBody() {
        }
        
        public GetHtmlTemplateByCodeRequestBody(int templatecode, string culture) {
            this.templatecode = templatecode;
            this.culture = culture;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHtmlTemplateByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHtmlTemplateByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeResponseBody Body;
        
        public GetHtmlTemplateByCodeResponse() {
        }
        
        public GetHtmlTemplateByCodeResponse(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHtmlTemplateByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHtmlTemplateByCodeResult;
        
        public GetHtmlTemplateByCodeResponseBody() {
        }
        
        public GetHtmlTemplateByCodeResponseBody(string GetHtmlTemplateByCodeResult) {
            this.GetHtmlTemplateByCodeResult = GetHtmlTemplateByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHtmlTemplateByCodeWithArgsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHtmlTemplateByCodeWithArgs", Namespace="http://tempuri.org/", Order=0)]
        public OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequestBody Body;
        
        public GetHtmlTemplateByCodeWithArgsRequest() {
        }
        
        public GetHtmlTemplateByCodeWithArgsRequest(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHtmlTemplateByCodeWithArgsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int templatecode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string culture;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg1;
        
        public GetHtmlTemplateByCodeWithArgsRequestBody() {
        }
        
        public GetHtmlTemplateByCodeWithArgsRequestBody(int templatecode, string culture, string arg1) {
            this.templatecode = templatecode;
            this.culture = culture;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHtmlTemplateByCodeWithArgsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHtmlTemplateByCodeWithArgsResponse", Namespace="http://tempuri.org/", Order=0)]
        public OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsResponseBody Body;
        
        public GetHtmlTemplateByCodeWithArgsResponse() {
        }
        
        public GetHtmlTemplateByCodeWithArgsResponse(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHtmlTemplateByCodeWithArgsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHtmlTemplateByCodeWithArgsResult;
        
        public GetHtmlTemplateByCodeWithArgsResponseBody() {
        }
        
        public GetHtmlTemplateByCodeWithArgsResponseBody(string GetHtmlTemplateByCodeWithArgsResult) {
            this.GetHtmlTemplateByCodeWithArgsResult = GetHtmlTemplateByCodeWithArgsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHtmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHtml", Namespace="http://tempuri.org/", Order=0)]
        public OB.BL.Operations.HtmlTemplateService.GetHtmlRequestBody Body;
        
        public GetHtmlRequest() {
        }
        
        public GetHtmlRequest(OB.BL.Operations.HtmlTemplateService.GetHtmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHtmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string templateName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string culture;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string optionalArg1;
        
        public GetHtmlRequestBody() {
        }
        
        public GetHtmlRequestBody(string templateName, string culture, string optionalArg1) {
            this.templateName = templateName;
            this.culture = culture;
            this.optionalArg1 = optionalArg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHtmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHtmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public OB.BL.Operations.HtmlTemplateService.GetHtmlResponseBody Body;
        
        public GetHtmlResponse() {
        }
        
        public GetHtmlResponse(OB.BL.Operations.HtmlTemplateService.GetHtmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHtmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHtmlResult;
        
        public GetHtmlResponseBody() {
        }
        
        public GetHtmlResponseBody(string GetHtmlResult) {
            this.GetHtmlResult = GetHtmlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HtmlTemplateServiceSoapChannel : OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HtmlTemplateServiceSoapClient : System.ServiceModel.ClientBase<OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap>, OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap {
        
        public HtmlTemplateServiceSoapClient() {
        }
        
        public HtmlTemplateServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HtmlTemplateServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HtmlTemplateServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HtmlTemplateServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeResponse OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap.GetHtmlTemplateByCode(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequest request) {
            return base.Channel.GetHtmlTemplateByCode(request);
        }
        
        public string GetHtmlTemplateByCode(int templatecode, string culture) {
            OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequest inValue = new OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequest();
            inValue.Body = new OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequestBody();
            inValue.Body.templatecode = templatecode;
            inValue.Body.culture = culture;
            OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeResponse retVal = ((OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap)(this)).GetHtmlTemplateByCode(inValue);
            return retVal.Body.GetHtmlTemplateByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeResponse> OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap.GetHtmlTemplateByCodeAsync(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequest request) {
            return base.Channel.GetHtmlTemplateByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeResponse> GetHtmlTemplateByCodeAsync(int templatecode, string culture) {
            OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequest inValue = new OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequest();
            inValue.Body = new OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeRequestBody();
            inValue.Body.templatecode = templatecode;
            inValue.Body.culture = culture;
            return ((OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap)(this)).GetHtmlTemplateByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsResponse OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap.GetHtmlTemplateByCodeWithArgs(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequest request) {
            return base.Channel.GetHtmlTemplateByCodeWithArgs(request);
        }
        
        public string GetHtmlTemplateByCodeWithArgs(int templatecode, string culture, string arg1) {
            OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequest inValue = new OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequest();
            inValue.Body = new OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequestBody();
            inValue.Body.templatecode = templatecode;
            inValue.Body.culture = culture;
            inValue.Body.arg1 = arg1;
            OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsResponse retVal = ((OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap)(this)).GetHtmlTemplateByCodeWithArgs(inValue);
            return retVal.Body.GetHtmlTemplateByCodeWithArgsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsResponse> OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap.GetHtmlTemplateByCodeWithArgsAsync(OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequest request) {
            return base.Channel.GetHtmlTemplateByCodeWithArgsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsResponse> GetHtmlTemplateByCodeWithArgsAsync(int templatecode, string culture, string arg1) {
            OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequest inValue = new OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequest();
            inValue.Body = new OB.BL.Operations.HtmlTemplateService.GetHtmlTemplateByCodeWithArgsRequestBody();
            inValue.Body.templatecode = templatecode;
            inValue.Body.culture = culture;
            inValue.Body.arg1 = arg1;
            return ((OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap)(this)).GetHtmlTemplateByCodeWithArgsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OB.BL.Operations.HtmlTemplateService.GetHtmlResponse OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap.GetHtml(OB.BL.Operations.HtmlTemplateService.GetHtmlRequest request) {
            return base.Channel.GetHtml(request);
        }
        
        public string GetHtml(string templateName, string culture, string optionalArg1) {
            OB.BL.Operations.HtmlTemplateService.GetHtmlRequest inValue = new OB.BL.Operations.HtmlTemplateService.GetHtmlRequest();
            inValue.Body = new OB.BL.Operations.HtmlTemplateService.GetHtmlRequestBody();
            inValue.Body.templateName = templateName;
            inValue.Body.culture = culture;
            inValue.Body.optionalArg1 = optionalArg1;
            OB.BL.Operations.HtmlTemplateService.GetHtmlResponse retVal = ((OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap)(this)).GetHtml(inValue);
            return retVal.Body.GetHtmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OB.BL.Operations.HtmlTemplateService.GetHtmlResponse> OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap.GetHtmlAsync(OB.BL.Operations.HtmlTemplateService.GetHtmlRequest request) {
            return base.Channel.GetHtmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<OB.BL.Operations.HtmlTemplateService.GetHtmlResponse> GetHtmlAsync(string templateName, string culture, string optionalArg1) {
            OB.BL.Operations.HtmlTemplateService.GetHtmlRequest inValue = new OB.BL.Operations.HtmlTemplateService.GetHtmlRequest();
            inValue.Body = new OB.BL.Operations.HtmlTemplateService.GetHtmlRequestBody();
            inValue.Body.templateName = templateName;
            inValue.Body.culture = culture;
            inValue.Body.optionalArg1 = optionalArg1;
            return ((OB.BL.Operations.HtmlTemplateService.HtmlTemplateServiceSoap)(this)).GetHtmlAsync(inValue);
        }
    }
}
